### ISSUE TITLE
Syntax error in FLAGS. Unexpected token: NIL

### ISSUE THREAD

**Issue by johanncampbell** [jstedfast/MailKit#1042]
Hi. I suffered an internet outage when trying to set keywords on a mailbox. Upon reconnecting, I am now getting an exception as below:

Exception:

**Syntax error in FLAGS. Unexpected token: NIL**

Stack Trace:
   at MailKit.Net.Imap.ImapUtils.<ParseFlagsListAsync>d__42.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Imap.ImapEngine.<ProcessUntaggedResponseAsync>d__173.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Imap.ImapCommand.<StepAsync>d__83.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__174.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<RunAsync>d__175.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapFolder.<OpenAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WorkStation.Services.WorkStationsLabRequestEmailService.<StartupClientAsync>d__77.MoveNext() in ....

Steps To Reproduce:

Not easily reproducible in a test environment as it only occurred after an internet outage while saving keywords to server.

Protol Log:

S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: A00000000 AUTHENTICATE PLAIN AHRlc3QucmVxdWVzdHNAbWljcm9sYWJzLmNsb3VkACM1NEhpZGRlblZhbGxleQ==
S: A00000000 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY XDOVECOT LITERAL+ NOTIFY METADATA QUOTA] Logged in
C: A00000001 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000001 OK Namespace completed (0.001 + 0.000 secs).
C: A00000002 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasNoChildren) "/" INBOX
S: A00000002 OK List completed (0.012 + 0.000 + 0.011 secs).
C: A00000003 EXAMINE INBOX (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft FacilitySeen NIL) <-- issue seems to be here
S: * OK [PERMANENTFLAGS ()] Read-only mailbox.
S: * 25 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 1] First unseen.
S: * OK [UIDVALIDITY 1593265559] UIDs valid
S: * OK [UIDNEXT 27] Predicted next UID
S: * OK [HIGHESTMODSEQ 34] Highest
S: A00000003 OK [READ-ONLY] Examine completed (0.035 + 0.000 + 0.034 secs).

**Comment by jstedfast** [comment]
A `NIL` flag is invalid syntax. I'm not sure how you created that flag, but it shouldn't be there.

**Comment by jstedfast** [comment]
Added a work-around since it's pretty trivial to do so. Surprised that Dovecot of all IMAP servers has this bug (Dovecot is one of the better IMAP servers out there).

**Comment by johanncampbell** [comment]
Much gratitude for this quick fix
