### ISSUE TITLE
MailKit.Net.Imap.ImapProtocolException: Syntax error in BODYSTRUCTURE. Unexpected token: ')'

### ISSUE THREAD

**Issue by hanxiao123** [jstedfast/MailKit#1076]
**Describe the bug**

MailKit.Net.Imap.ImapProtocolException: Syntax error in BODYSTRUCTURE. Unexpected token: ')'
   at MailKit.Net.Imap.ImapUtils.ReadNStringTokenAsync(ImapEngine engine, String format, Boolean rfc2047, Boolean doAsync, CancellationToken cancellationToken)

**Platform **
 - OS: CentOS 8.1
 - .NET Framework:  .Net Core 3.1
 - MailKit Version: 2.9

When I retrive some gmail email, it can repeat the bug.the bug is very old,it seems never be solved.

**Comment by jstedfast** [comment]
Please get a protocol log - without it, I can't solve this problem.

Most likely (as with all of the other cases with similar bug reports to this), your IMAP server is buggy and is sending a malformed BODYSTRUCTURE response. Once I get a protocol log, hopefully I'll be able to implement a work-around in MailKit for your particular IMAP server.

I've been successful in implementing work-arounds in nearly every case where someone has provided a protocol log of the issue.

For more information on how to obtain a protocol log, see https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog

**Comment by hanxiao123** [comment]
Here is the error info and protocol log,thank you!please!
GetEmaliList:MailKit.Net.Imap.ImapProtocolException: Syntax error in BODYSTRUCTURE. Unexpected token: ')'
   at MailKit.Net.Imap.ImapUtils.ReadNStringTokenAsync(ImapEngine engine, String format, Boolean rfc2047, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseBodyAsync(ImapEngine engine, String format, String path, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseMultipartAsync(ImapEngine engine, String format, String path, String subtype, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseBodyAsync(ImapEngine engine, String format, String path, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.FetchSummaryItemsAsync(ImapEngine engine, MessageSummary message, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.FetchSummaryItemsAsync(ImapEngine engine, ImapCommand ic, Int32 index, Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.StepAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
   at MailKit.Net.Imap.ImapFolder.FetchAsync(IList`1 uids, MessageSummaryItems items, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.Fetch(IList`1 uids, MessageSummaryItems items, CancellationToken cancellationToken)
[102140774408.txt](https://github.com/jstedfast/MailKit/files/5243001/102140774408.txt)

**Comment by jstedfast** [comment]
The problem is on this line of the server response:

```
S: * 118531 FETCH (UID 122273 FLAGS (\Seen) INTERNALDATE "14-May-2020 15:49:48 +0800" RFC822.SIZE 1399 ENVELOPE ("Thu, 14 May 2020 15:49:46 +0800" "=?GBK?B?YXNkZg==?=" (("=?GBK?B?S2Ft?=" NIL "kam" "retevis.com")) (("=?GBK?B?S2Ft?=" NIL "kam" "retevis.com")) (("=?GBK?B?S2Ft?=" NIL "kam" "retevis.com")) (("=?GBK?B?MTA0NzY3MzkwMA==?=" NIL "1047673900" "qq.com")) NIL NIL NIL "<IFM3XSHIMAU4.MXK86G3J2SLT1@iZi5p26lz0e4rkZ>") BODYSTRUCTURE (( "RELATED" ("BOUNDARY" "=-T/JpEBrvLTSCFG7WU+0RMA==") NIL NIL)(("TEXT" "HTML" ("charset" "utf-8") NIL NIL "8BIT" 99 1 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "=-r
```

Specially, the problem is with this part of the response:

```
BODYSTRUCTURE (( "RELATED" ("BOUNDARY" "=-T/JpEBrvLTSCFG7WU+0RMA==") NIL NIL)
```

That is completely borked.

I'm not sure how to work around this. I think you'll need to send a bug report to QQMail's developers about this.
