### ISSUE TITLE
Resource temporarily Unavailable while connecting inside Docker on server

### ISSUE THREAD

**Issue by MrABoutin** [jstedfast/MailKit#1095]
Hi there,
I am using Mailkit to send confirmation email to newly created users in a .netCore Api inside a docker on a cloud server. There is a mail server on the same machine, not inside the docker nor inside its own docker, the mail server is managed with plesk and so is the SSL certificate.

When sending an email on my own machine, either debugging or inside a docker, I tested with 2 different mail server and everything works:

```c#
using (var smtp = new MailKit.Net.Smtp.SmtpClient())
                {
                    smtp.ServerCertificateValidationCallback = (s, c, h, e) => true;
                    
                    await smtp.ConnectAsync(HOSTNAME, 465, true);
                    await smtp.AuthenticateAsync(EMAIL, PASSWORD);
                    await smtp.SendAsync(message);
                    await smtp.DisconnectAsync(true);
                }
```

when using on the server, again tested with the local mail server or a remote mail server I get this error:
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
```

**Platform (please complete the following information):**
 - OS: Docker on Linux(DigitalOcean)
 - .NET Runtime: CoreCLR
 - .NET Framework: .NetCore 3.1
 - MailKit Version: 2.9.0

My guess is a problem to resolve the dns since the problem is triggered with he `.InternalGetHostByName`. All ports on the firewall were opened to test and still the same problem happened.

**Comment by jstedfast** [comment]
This is a problem in the .NET Core libraries. As you have discovered, the problem is with System.Net.Dns.GetHostByNameAsync() which is hitting that error.

The only thing I can do is exactly what you can do in your app which is to catch that exception and retry to connect.

MailKit chooses not to catch it and force a retry itself, because the more appropriate place to handle this error condition is in the app code that sits above MailKit.

Hope that helps!
