### ISSUE TITLE
Syntax error in IMAP server greeting. Unexpected token: [atom: 421]

### ISSUE THREAD

**Issue by gold22** [jstedfast/MailKit#1100]
**Describe the bug**
The library cannot parse the "421 Server is busy, try again later." response.

```
Connect to test@localhost:143
Connected to imap://localhost:143/
< 421 Server is busy, try again later.
```

**Platform:**
 - OS: Windows Server 2012
 - .NET Framework: .NET 4.5
 - MailKit Version: 2.5.2
- Mail server: SmarterMail 100.0.7523

**Actual behavior**

```
MailKit.Net.Imap.ImapProtocolException: Syntax error in IMAP server greeting. Unexpected token: [atom: 421]
```

**Expected behavior**
An exception that allows to handle the 421 error code.

**Additional context**

```
MailKit.Net.Imap.ImapProtocolException: Syntax error in IMAP server greeting. Unexpected token: [atom: 421]
   at MailKit.Net.Imap.ImapEngine.<ConnectAsync>d__150.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Imap.ImapClient.<ConnectAsync>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
```

**Comment by jstedfast** [comment]
There's no such thing as a 421 error code for IMAP.
