### ISSUE TITLE
AuthenticationException:421: 4.3.2 Service not active

### ISSUE THREAD

**Issue by RPJack** [jstedfast/MailKit#1106]
I used SmtpClient to send email a lot time,i have schedule to run job,it's ok!
but today, i got an error message twice unexpected:

2020-11-25 08:30:30.1746||FATAL|DataTransfer.Models.Repository.BackgroundRepository|
MailKit.Security.AuthenticationException: 421: 4.3.2 Service not active [TYAPR01CA0229.jpnprd01.prod.outlook.com] ---> MailKit.Net.Smtp.SmtpCommandException: 4.3.2 Service not active [TYAPR01CA0229.jpnprd01.prod.outlook.com]
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)

2020-11-25 09:30:30.1631||FATAL|DataTransfer.Models.Repository.BackgroundRepository|
MailKit.Security.AuthenticationException: 421: 4.3.2 Service not active [TYAPR01CA0229.jpnprd01.prod.outlook.com] ---> MailKit.Net.Smtp.SmtpCommandException: 4.3.2 Service not active [TYAPR01CA0229.jpnprd01.prod.outlook.com]
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)

**Platform**
 - OS: Linux 4.14.152-127.182.amzn2.x86_64
 - .NET Runtime: 3.1.401
 - MailKit Version: 2.1.2.0

**Additional context**
Complementary,my email server is hosting office365.com,it send a lot of email to @mjretail.co.jp or others.
it's applicable usually,just  unexpected twice time today.
i don't know it is outlook has some issue or mailkit or others,if you can give me some message,it will grateful!

**Comment by jstedfast** [comment]
SMTP error 421 is a server error that just means that the server is probably rebooting or something.
