### ISSUE TITLE
Vague error sending a basic text email

### ISSUE THREAD

**Issue by jjxtra** [jstedfast/MailKit#1153]
**Describe the bug**
Null reference exception with a path cannot be null error when calling SendAsync on smtpclient.

**Platform (please complete the following information):**
Ubuntu 20.04, .NET 5 latest release, latest mailkit nuget as of 2021-02-21

I looked through your `DataAsync` method and did not see anything obvious.

One thing is that the to address is being created with `MailboxAddresss.Parse` and seems to always have a email@domain.co.uk instead of a single top level domain extension. I've done many tests locally (on Windows) with those kinds of addresses and never see the exception, so maybe this is Ubuntu specific...

Not sure where the error is coming from and it is hard to reproduce. Some sort of try/catch might be helpful or parameter validation to help trace this down would sure be nice.

Code for sending is pretty straightforward:
```
MailboxAddress[] from = new MailboxAddress[] { MailboxAddress.Parse(config.EmailFrom) };
MailboxAddress[] to = new MailboxAddress[] { MailboxAddress.Parse(emailToSendTo) };
using SmtpClient client = new SmtpClient();
await client.ConnectAsync(config.EmailServer);
await client.AuthenticateAsync(config.EmailUser, config.EmailPassword);
MimeMessage msg = new MimeMessage();
msg.Sender = from[0];
msg.From.AddRange(from);
msg.To.AddRange(to);
msg.Subject = subject;
msg.Body = (new BodyBuilder { TextBody = body }).ToMessageBody();
await client.SendAsync(msg);
```

Stack trace
```
 ---> MailKit.Net.Smtp.SmtpCommandException: Internal Error: Path cannot be null. (Parameter 'path')
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Int64 size, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
```

**Comment by jjxtra** [comment]
This error message was actually coming back from the mail server itself, not from mailkit. Thanks for the helpful exception link to enable the protocol logger.
