### ISSUE TITLE
System.ObjectDisposedException only when calling the Async methods AND with attachment

### ISSUE THREAD

**Issue by dyesdyes** [jstedfast/MailKit#1189]
**Describe the bug**

I stumble upon an odd one IMO.

The following works:

```
using var client = new CustomMailKitSmtpClient();
if (_environmentHelper.IsDevelopment())
{
    client.CheckCertificateRevocation = false;
}

client.Connect(_options.Host, _options.Port, SecureSocketOptions.StartTlsWhenAvailable);

client.Authenticate(_options.Account, _options.Password);

client.Send(message);
client.Disconnect(true);
```

But the following doesn't work only if message has an attachment:

```
using var client = new CustomMailKitSmtpClient();
if (_environmentHelper.IsDevelopment())
{
    client.CheckCertificateRevocation = false;
}

await client.ConnectAsync(_options.Host, _options.Port, SecureSocketOptions.StartTlsWhenAvailable);

await client.AuthenticateAsync(_options.Account, _options.Password);

await client.SendAsync(message);
await client.DisconnectAsync(true);
```
Notice that the only difference is that I now use the async equivalent methods.

Note that this works fine for emails without attachments.

**Platform (please complete the following information):**
 - OS: Windows & Linux at least
 - .NET Runtime: 
 - .NET Framework: .Net Core 3.1
 - MailKit Version: 2.8.0

**Exception**

For emails with attachments, I get:

```
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.EnsureNotClosed()
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at MimeKit.MimeContent.WriteToAsync(Stream stream, CancellationToken cancellationToken)
   at MimeKit.MimeContent.DecodeToAsync(Stream stream, CancellationToken cancellationToken)
   at MimeKit.MimePart.WriteToAsync(FormatOptions options, Stream stream, Boolean contentOnly, CancellationToken cancellationToken)
   at MimeKit.Multipart.WriteToAsync(FormatOptions options, Stream stream, Boolean contentOnly, CancellationToken cancellationToken)
   at MimeKit.MimeMessage.WriteToAsync(FormatOptions options, Stream stream, Boolean headersOnly, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, Int64 size, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at Fifty.Messaging.Emails.SendInBlue.SmtpClient.FiftySmtpClient.SendMessageAsync(MimeMessage message) in C:\work\fifty\src\Fifty.Messaging\Emails\SendInBlue\SmtpClient\FiftySmtpClient.cs:line 123
```

**Expected behavior**
I would expect it not to throw an exception as I don't dispose the Stream.

**Protocol Logs**

See attached

[imap-email-not-working-with-attachment.log](https://github.com/jstedfast/MailKit/files/6263486/imap-email-not-working-with-attachment.log)
[imap-working-email-with-no-attachment.log](https://github.com/jstedfast/MailKit/files/6263506/imap-working-email-with-no-attachment.log)

**Comment by jstedfast** [comment]
Did you dispose the memory stream? This can only happen if your code disposed the attachment stream.

**Comment by dyesdyes** [comment]
Thanks! This was indeed the problem.
