### ISSUE TITLE
SmtpClient throws error: "connection failed because connected host has failed to respond 142.251.10.108:587'"

### ISSUE THREAD

**Issue by Yadunandanaacharya** [jstedfast/MailKit#1255]
Hi,

In config file I have used this: 
"Host": "smtp.gmail.com",
  "Port": 587,
"UseSSL": false,
  "UseStartTLS": true

While sending mail to my personal gmail id via Mailkit library I have used SmtpClient to send message

But when break point hits this line of code below:
client.Connect("smtp.gmail.com",587, MailKit.Security.SecureSocketOptions.StartTlsWhenAvailable)

It throws error like this:
System.Net.Internals.SocketExceptionFactory.ExtendedSocketException: 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 142.251.10.108:587'

I have connected to Open Vpn and turned off anti-virus.

Stack Trace:
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectSocket(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at EmailTester.MailRepository.SendEmail(String to, List`1 cc, String subject, String body, List`1 attachments) in D:\MailRepository.cs:line 66
   at EmailTester.Program.Main(String[] args) in D:\Program.cs:line 32

 - OS: Windows 10
 - .NET Framework:  .NET 4.5
 - MailKit Version: V2.15.0

Thanks

**Comment by jstedfast** [comment]
It means that the .NET Socket library could not connect to whatever host you asked it to connect to.

Why it can't connect is something you'll have to figure out on your own. Maybe the server is down or maybe your DNS server is down or maybe your network cable is unplugged. There's a million possibilities and there's no way for me to help you.

**Comment by Yadunandanaacharya** [comment]
Ok, thanks. I'll check them.
