### ISSUE TITLE
Unable to Disconnect client gracefully using DisconnectAsync(true)

### ISSUE THREAD

**Issue by jatinrajbhatia** [jstedfast/MailKit#1278]
Whenever I am trying to disconnect client using DisconnectAsync(true), I am getting the below error:
I am using Mailkit version 2.15.0
```
ClientDisconnect method()==> Exception Message:  The ReadAsync method cannot be called when another read operation is pending., Exception String: System.NotSupportedException:  The ReadAsync method cannot be called when another read operation is pending.
         at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
         at MailKit.Net.Pop3.Pop3Stream.ReadAheadAsync(Boolean doAsync, CancellationToken cancellationToken)
         at MailKit.Net.Pop3.Pop3Stream.ReadLineAsync(Stream ostream, Boolean doAsync, CancellationToken cancellationToken)
         at MailKit.Net.Pop3.Pop3Engine.ReadLineAsync(Boolean doAsync, CancellationToken cancellationToken)
         at MailKit.Net.Pop3.Pop3Engine.ReadResponseAsync(Pop3Command pc, Boolean doAsync)
         at MailKit.Net.Pop3.Pop3Engine.IterateAsync(Boolean doAsync)
         at MailKit.Net.Pop3.Pop3Client.SendCommandAsync(Boolean doAsync, CancellationToken token, String command)
         at MailKit.Net.Pop3.Pop3Client.DisconnectAsync(Boolean quit, Boolean doAsync, CancellationToken cancellationToken)
```

Below is the code I am using to Disconnect the Client
```
private async Task DisconnectClient(Hashtable markAsRead, EmailServer emailServer)
{
    pollingInProgress = false;
    await emailServer.ClientDisconnect(markAsRead);
    markAsRead.Clear();
}
```

```
internal void MarkAsRead(Hashtable markAsRead)
        {
            emailBinding.emailSource().MarkRead(markAsRead);
        }

        internal async Task ClientDisconnect(Hashtable markAsRead)
        {
            try
            {
                if (!emailBinding.emailSource().IsConnected)
                {
                    await emailBinding.Connect();
                }

                FlushClient(markAsRead);

                await emailBinding.Disconnect();
            }
            catch (Exception e)
            {
                AttachWorkerLogs(string.Format("ClientDisconnect method()==> Exception Message: {0}, Exception String: {1}", e.Message, e.ToString()));
                throw;
            }
        }

        private void FlushClient(Hashtable markAsRead)
        {
            MarkAsRead(markAsRead);
        }
```

Finally calling the disconnect method like this:
```
public async Task Disconnect()
        {
            try
            {
                if (client.IsConnected)
                {
                    await client.DisconnectAsync(true);
                }
            }
            catch (Exception e)
            {
                AttachLogger(string.Format("Disconnect method()==> Exception Message: {0}, Exception String: {1}", e.Message, e.ToString()));
                throw;
            }

        }
```

I am unable to figure out what exactly is the issue.

**Comment by jstedfast** [comment]
Have you tried a debugger?

**Comment by jatinrajbhatia** [comment]
Yes I did, but could not find anything. That's the reason I thought of turning to you, as I am facing this only when I try to disconnect the client.

**Comment by jstedfast** [comment]
Hint: check what your other threads are doing when this occurs.
