### ISSUE TITLE
Connect fails, but only when using DI in Asp.NET Core

### ISSUE THREAD

**Issue by Heldenkrieger01** [jstedfast/MailKit#1303]
**Describe the bug**
The `SmtpClient.Connect` method throws a `MailKit.Security.SslHandshakeException` when I use MailKit dependency-injected. (Asp.NET Core)

**Platform (please complete the following information):**
 - OS: Windows 11
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET 5.0.12
 - MailKit Version: 2.15.0

**Exception**
There is no stacktrace for me to see, I get this exact message in the console: 
Exception thrown: 'MailKit.Security.SslHandshakeException' in System.Private.CoreLib.dll

**Expected behavior**
MailKit should connect to the server as if the `SmtpClient` wasn't injected.

**Code Snippets**
When uncommenting the line marked with UNCOMMENT THIS,  it works. Meaning that only the dependency injected version of my `SmtpClient` fails.

```csharp
public class EmailService : IEmailService
    {
        private readonly ISmtpClient _smtpClient;

        public EmailService(ISmtpClient smtpClient)
        {
            _smtpClient  = smtpClient ?? throw new ArgumentNullException(nameof(smtpClient));
        }

        public async Task Send(string to, string subject, string html, string? from = null)
        {
            // create message
            var email = new MimeMessage();
            // omitted

            // send email
            // using var _smtpClient = new SmtpClient(); //<-------------- UNCOMMENT THIS
            await _smtpClient.ConnectAsync("host", 578, SecureSocketOptions.StartTls); // Line 39
            await _smtpClient.AuthenticateAsync("user", "pass");
            await _smtpClient.SendAsync(email);
            await _smtpClient.DisconnectAsync(true);
        }
    }
```

I register the `SmtpClient` in my `Startup` Class inside `ConfigureServices()`

```csharp
     services.AddScoped<ISmtpClient, SmtpClient>();
```

**Comment by jstedfast** [comment]
What is the inner exception? You'll need to find that out so we know why it is failing.

**Comment by jstedfast** [comment]
Please reopen this when you find out what the inner exception is.

**Comment by Heldenkrieger01** [comment]
I now caught the exception.

Stack trace: (I have marked line 39 in my original description above)
```
   at MailKit.Net.Smtp.SmtpClient.<ConnectAsync>d__93.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MY.NAMESPACE.Services.EmailService.<Send>d__3.MoveNext() in REDACTED\Services\EmailService.cs:line 39
```

Inner exception:
`"Object reference not set to an instance of an object."`

Inner exception stack trace:
```
   at MailKit.Net.Smtp.SmtpClient.ValidateRemoteCertificate(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__173`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.<ConnectAsync>d__93.MoveNext()
```

Inner exception HREsult:
`-2147467261`

Message: (Yes, I read that, and it is none of these, since it works without DI)
```
An error occurred while attempting to establish an SSL or TLS connection.

This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
the following reasons:

1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid.
5. The set of SSL/TLS protocols supported by the client and server do not match.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.
```

HResult:
`-2146233088`

**Comment by Heldenkrieger01** [comment]
@jstedfast I cannot reopen this, since you were the one closing. Please reopen, thank you.

**Comment by jstedfast** [comment]
I suspect the problem is the way you are using it via DI because what you are doing is creating a shared SmtpClient instance which means you could have multiple threads all using the same instance. That's a terrible position to be in and is unsupported.

**Comment by jstedfast** [comment]
Do you have a sample project that illustrates this bug? You could publish such a test project to GitHub and I'll clone it & debug through it just to confirm.
