### ISSUE TITLE
Message Not Found

### ISSUE THREAD

**Issue by ROMYIM** [jstedfast/MailKit#1307]
**Describe the bug**
I used the Search api to query the email uniqueIds. And I  used the uniqueId which the search api returned to get message,  but it throw `MailKit.MessageNotFoundException: The IMAP server did not return the requested message.
`
**Platform (please complete the following information):**
 - OS:Windows 10
 - .NET Runtime:CoreCLR
 - .NET Framework: .Net 6
 - MailKit Version: 3.0.0.0

**Exception**
MailKit.MessageNotFoundException: The IMAP server did not return the requested message.
   at MailKit.Net.Imap.ImapFolder.GetMessageAsync(UniqueId uid, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at iPlatformV2.MailService.TestApi.Controllers.MailController.SendTestEmailAsync(SendMailParameters parameters) in D:\ACIP\Documents\Repositories\iPlatformV2\iPlatformV2.MailService.TestApi\Controllers\MailController.cs:line 79
   at lambda_method5(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**To Reproduce**
1. using var imapClient = new ImapClient();
2. await imapClient.ConnectAsync(imapHost, imapPort);
3. await imapClient.AuthenticateAsync(parameters.MailUserName, parameters.HostPassword);
4. var inbox = imapClient.Inbox;
5. await inbox.OpenAsync(FolderAccess.ReadOnly);
6. var query = SearchQuery.DeliveredAfter(new DateTime(2021, 12, 21));
7. var uniqueIds = await inbox.SearchAsync(query);
8. var uniqueId = uniqueIds[Random.Next(uniqueIds.Count)];
9. var originalMessage = await inbox.GetMessageAsync(uniqueId);

**Expected behavior**
It found the uniqueId, so it should return the message bu not throw NotFoundException

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
        var inbox = imapClient.Inbox;
        await inbox.OpenAsync(FolderAccess.ReadOnly);
        var query = SearchQuery.DeliveredAfter(new DateTime(2021, 12, 21));

       /// it return the 2 uniqueIds
        var uniqueIds = await inbox.SearchAsync(query);
        var uniqueId = uniqueIds[Random.Next(uniqueIds.Count)];

       /// I use one of then to get message but it throw MessageNotFoundException
        var originalMessage = await inbox.GetMessageAsync(uniqueId);
```

**Protocol Logs**
Please include a protocol log (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.

To get a protocol log, follow one of the following code snippets:

```csharp
// query DateQuery
var query = SearchQuery.DeliveredAfter(new DateTime(2021, 12, 21));
```

```csharp
// uniqueIds: 1640164689:1640164690
 var uniqueIds = await inbox.SearchAsync(query);
```

```csharp
// uniqueId: 1640164690
var uniqueId = uniqueIds[Random.Next(uniqueIds.Count)];
```
```csharp
// originalMessage: null  throw MailKit.MessageNotFoundException: The IMAP server did not return the requested message.
var originalMessage = await inbox.GetMessageAsync(uniqueId);
```

Note: if the protocol log contains sensitive information, feel free to email it to me at
jestedfa@microsoft.com instead of including it in the GitHub issue.

**Additional context**

**Comment by jstedfast** [comment]
According to your IMAP server, the message doesn't exist.

**Comment by jstedfast** [comment]
Actually, if you get me a protocol log, I'll take a closer look.

**Comment by jstedfast** [comment]
FWIW, just to explain why I need a protocol log:

What *may* be happening is that MailKIt requests with a command such as:

```
A00000008 UID FETCH 1640164690 (BODY.PEEK[]) 
```

The expected response would look something like this:

```
* 1640164690 FETCH (UID 1640164690 BODY[] {4096}
<the raw message>
)
A00000008 OK UID FETCH completed.
```

What MailKit does is to parse that `Body[]` to extract the part-specifier from between the square brackets (in the above case, it's an empty string).

If your server is doing something broken, like:

```
* 1640164690 FETCH (UID 1640164690 BODY[RFC822] {4096}
<the raw message>
)
A00000008 OK UID FETCH completed.
```

In *this* example, the part-specifier would be `RFC822` and so checking for the empty-string part specifier in the response would find no results, thereby causing the error you are seeing.

That said, *if* this is what is happening, I can add a work-around to MailKit to handle this but first I need to know if that's what is happening.
