### ISSUE TITLE
The IMAP server replied to the 'SELECT' command with a 'NO' response: SELECT Arguments invalid

### ISSUE THREAD

**Issue by michalss** [jstedfast/MailKit#1326]
Hi, Im trying to get Sent folder but im getting this error. Is there anything i can do please ?

```
blazor.server.js:1 [2022-02-02T14:14:41.872Z] Error: System.AggregateException: One or more errors occurred. (The IMAP server replied to the 'SELECT' command with a 'NO' response: SELECT Arguments invalid)
 ---> MailKit.Net.Imap.ImapCommandException: The IMAP server replied to the 'SELECT' command with a 'NO' response: SELECT Arguments invalid
   at MailKit.Net.Imap.ImapFolder.OpenAsync(ImapCommand ic, FolderAccess access, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.Open(FolderAccess access, CancellationToken cancellationToken)
   at lokalizace.net.Services.EMailService.GetSendedFolder()
   at lokalizace.net.Components.SNDEmailComponent.LoadData()
   at lokalizace.net.Components.SNDEmailComponent.OnAfterRenderAsync(Boolean firstRender)
   --- End of inner exception stack trace ---
```

```
Connected to imaps://xxxxxxx/
S: * OK IMAP4 ready
C: R00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 SORT CTHREAD=REFERENCES MULTIAPPEND UNSELECT IDLE CHILDREN NAMESPACE LOGIN-REFERRALS AUTH=PLAIN
S: R00000000 OK completed
C: R00000001 AUTHENTICATE PLAIN
S: + 
C: ********
S: R00000001 OK LOGIN Completed
C: R00000002 CAPABILITY
S: * CAPABILITY IMAP4rev1 AUTH=PLAIN AUTH=LOGIN AUTH=GSSAPI UIDPLUS QUOTA ACL NAMESPACE CHILDREN IDLE ID UNSELECT METADATA X-ICEWARP-SERVER X-MOVE MULTISEARCH ESEARCH XLIST CREATE-SPECIAL-USE X-ICEWARP-PRIVATEBUSY X-ICEWARP-PROVISIONS X-ICEWARP-CHANGEPASSWORD X-ICEWARP-DIAL X-ICEWARP-CONDSTORE X-ICEWARP-SEARCHLIMIT X-COLOR STARTTLS
S: R00000002 OK CAPABILITY Completed
C: R00000003 NAMESPACE
S: * NAMESPACE (("" "/")) (("~" "/")) NIL 
S: R00000003 OK NAMESPACE Completed
C: R00000004 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: R00000004 OK LIST Completed
C: R00000005 XLIST "" "*"
S: * XLIST (\HasNoChildren) "/" "Odstran&ARs-n&AOk- polo&AX4-ky"
S: * XLIST (\HasNoChildren \Sent) "/" "Sent"
S: * XLIST (\HasNoChildren \Noinferiors \Spam) "/" "Spam"
S: * XLIST (\HasNoChildren \Drafts) "/" "Drafts"
S: * XLIST (\HasNoChildren) "/" "INBOX"
S: * XLIST (\HasNoChildren \Trash) "/" "Trash"
S: * XLIST (\HasNoChildren) "/" "Odeslan&AOk- polo&AX4-ky"
S: R00000005 OK XLIST Completed
C: R00000006 EXAMINE ""
S: R00000006 NO EXAMINE Arguments invalid
```

ExampleCode
```csharp
public async Task<MailResponse> GetSendedFolder()
        {
            var messageResponse = new MailResponse();

            try
            {
                string[] CommonSentFolderNames = { "Sent"};

                var messages = new List<EmailMessage>();
                var smtp = new ImapClient();
                smtp.Connect(_settings.SMTP.host_server, _settings.SMTP.IMAPPort, SecureSocketOptions.Auto);
                smtp.Authenticate(_settings.SMTP.host_username, _settings.SMTP.host_password);

                var inbox = smtp.GetFolder(smtp.PersonalNamespaces[0]);
                // This is where it failing
                inbox.Open(FolderAccess.ReadWrite);
                var sentFolder = inbox.GetSubfolders(false).FirstOrDefault(x => CommonSentFolderNames.Contains(x.Name));

                var uids = sentFolder.Search(SearchQuery.All);
                var items = inbox.Fetch(uids, MessageSummaryItems.Full);
                foreach (var item in items)
                {
                  
                    var message = inbox.GetMessage(item.UniqueId);
                    var flag = item.Flags.Value.HasFlag(MessageFlags.Seen);

                    messages.Add(new EmailMessage
                    {
                        body_html = message.HtmlBody,
                        body_plain = message.TextBody,
                        from_email = message.From[0]?.ToString(),
                        subject = message.Subject,
                        importance = message.Importance.ToString(),
                        message_id = message.MessageId,
                        tom_email = message.To[0]?.ToString(),
                        priority = message.Priority.ToString(),
                        rcv_date = message.Date.DateTime,
                        uid = item.UniqueId,
                        readed = flag
                    });
                }

                smtp.Disconnect(true);
                messageResponse.messages = messages;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

            return messageResponse;
        }
```

**Comment by jstedfast** [comment]
The problem is this:

```csharp
var inbox = smtp.GetFolder(smtp.PersonalNamespaces[0]);
```

That's not the Inbox folder, that's the root-level folder (which in most cases is a "fake" folder).

If you want the Inbox (which is a very special folder in IMAP), you can use `client.Inbox`, or you can do something like this:

```csharp
var root = smtp.GetFolder(smtp.PersonalNamespaces[0]);
var folders = root.GetSubfolders ();

// Note: the INBOX folder is case-insensitive. Every other folder is case-sensitive.
var inbox = folders.FirstOrDefault (x => x.FullName.Equals ("INBOX", StringComparison.OrdinalIgnoreCase));
```

-or-

```csharp
var root = smtp.GetFolder(smtp.PersonalNamespaces[0]);
var inbox = root.GetSubfolder ("INBOX");
```

**Comment by jstedfast** [comment]
It's also worth mentioning that you do not need to call `Open(...)` on a folder in order to get a list of subfolders.

You only need to `Open(...)` a folder before you can look at the messages within the folder. So, for example, you would need to open a folder before you can Search(), Fetch(), GetMessage(), etc.

**Comment by michalss** [comment]
But im trying to get Sent folder, i cearly state that in fisrt post..

**Comment by michalss** [comment]
> It's also worth mentioning that you do not need to call `Open(...)` on a folder in order to get a list of subfolders.
> 
> You only need to `Open(...)` a folder before you can look at the messages within the folder. So, for example, you would need to open a folder before you can Search(), Fetch(), GetMessage(), etc.

**Comment by michalss** [comment]
Never mind i solve it on my own. Just as refference here is the code

```csharp
   public async Task<MailResponse> GetSendedFolder()
        {
            var messageResponse = new MailResponse();

            try
            {
                string[] CommonSentFolderNames = { "Sent" };

                var messages = new List<EmailMessage>();
                var smtp = new ImapClient();
                smtp.Connect(_settings.SMTP.host_server, _settings.SMTP.IMAPPort, SecureSocketOptions.Auto);
                smtp.Authenticate(_settings.SMTP.host_username, _settings.SMTP.host_password);

                var root = smtp.GetFolder(smtp.PersonalNamespaces[0]);

                var sentFolder = root.GetSubfolders(false).FirstOrDefault(x => CommonSentFolderNames.Contains(x.Name));
                sentFolder.Open(FolderAccess.ReadWrite);

                var uids = sentFolder.Search(SearchQuery.All);
                var items = sentFolder.Fetch(uids, MessageSummaryItems.Full);
                foreach (var item in items)
                {
                    var message = sentFolder.GetMessage(item.UniqueId);
                    var flag = item.Flags.Value.HasFlag(MessageFlags.Seen);

                    messages.Add(new EmailMessage
                    {
                        body_html = message.HtmlBody,
                        body_plain = message.TextBody,
                        from_email = message.From[0]?.ToString(),
                        subject = message.Subject,
                        importance = message.Importance.ToString(),
                        message_id = message.MessageId,
                        tom_email = message.To[0]?.ToString(),
                        priority = message.Priority.ToString(),
                        rcv_date = message.Date.DateTime,
                        uid = item.UniqueId,
                        readed = flag
                    });
                }

                smtp.Disconnect(true);
                messageResponse.messages = messages;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

            return messageResponse;
        }
```
