### ISSUE TITLE
NetworkStream ReadAsync throws ObjectDisposedException

### ISSUE THREAD

**Issue by faucetcollector** [jstedfast/MailKit#1327]
**Describe the bug**
When a read timeout occurs in the `NetworkStream.ReadAsync` it will Disconnect the Socket. But in the Exception message it will use the `ReadTimeout` property, which reads the `Socket.ReceiveTimeout` property. This will throw an `ObjectDisposedException` because it was just disposed by calling `Disconnect();` in the line before.

```csharp
} catch (OperationCanceledException ex) {
	Disconnect ();
	if (timeout.IsCancellationRequested)
		throw new TimeoutException ($"Operation timed out after {ReadTimeout} milliseconds", ex);
	throw;
}
```
Suggested fix is to store the `ReadTimeout` in a local variable and use that in the exception message.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Framework: net6
 - MailKit Version: 3.1.1

**Exception**

```csharp
Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.ThrowObjectDisposedException()
   at System.Net.Sockets.Socket.GetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName)
   at System.Net.Sockets.Socket.get_ReceiveTimeout()
   at MailKit.Net.NetworkStream.get_ReadTimeout()
   at MailKit.Net.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadAheadAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpStream.ReadResponseAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendCommandAsync(String command, Boolean doAsync, CancellationToken cancellationToken)
```

**Comment by faucetcollector** [comment]
Looks like the same issue applies in the `WriteAsync` method with the `WriteTimeout` property in the Exception message.
