### ISSUE TITLE
MimeKit.ParseException: Invalid local-part at offset 0

### ISSUE THREAD

**Issue by thoshiteng** [jstedfast/MailKit#1344]
**Describe the bug**
When preparing a MimeMessage and adding recipient into the "To" object, and providing email address "testing123.tesing.1234.@free.fr" to object MailboxAddress, the MimeKit throw exception "Invalid local-part at offset 0"

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: Core
 - .NET Framework: .Net 3.1
 - MailKit Version: Tested with 2.10.1 and 3.1.1 

**Exception**
Invalid local-part at offset 0

   at MimeKit.InternetAddress.TryParseLocalPart(Byte[] text, Int32& index, Int32 endIndex, RfcComplianceMode compliance, Boolean skipTrailingCfws, Boolean throwOnError, String& localpart)
   at MimeKit.InternetAddress.TryParseAddrspec(Byte[] text, Int32& index, Int32 endIndex, Byte[] sentinels, RfcComplianceMode compliance, Boolean throwOnError, String& addrspec, Int32& at)
   at MimeKit.MailboxAddress.set_Address(String value)
   at MimeKit.MailboxAddress..ctor(Encoding encoding, String name, String address)
   at MimeKit.MailboxAddress..ctor(String name, String address)
   at Dell.Cloud.Identity.Messaging.Services.Business.SmtpService.<>c__DisplayClass8_0.<BuildMimeMessage>b__0(String to) in C:\Local\Source\dell.cloud.identity.messaging.api\Dell.Cloud.Identity.Messaging.Services\Business\SmtpService.cs:line 141

**To Reproduce**
1. Create a new object MimeMessage 
2. Add a new MailboxAddress object with email address testing123.tesing.1234.@free.fr

**Expected behavior**
Should not have thrown error.

**Code Snippets**
```csharp
var message = new MimeMessage() {
                Subject = subject,
                Sender = new MailboxAddress("test", string.IsNullOrWhiteSpace(sender) ? _smtpSettings.Sender : sender),
                Body = new TextPart(isHtml ? TextFormat.Html : TextFormat.Text) {
                    Text = emailBody
                }
            };
            message.From.Add(new MailboxAddress("test", string.IsNullOrWhiteSpace(from) ? _smtpSettings.From : from));
            mailTo.Split(new char[] { ',', ';', ' ' }).ToList().ForEach(
                to => {
                    if (!string.IsNullOrWhiteSpace(to)) {
                        message.To.Add(new MailboxAddress("test", to));
                    }
                });
```

**Comment by jstedfast** [comment]
`testing123.tesing.1234.@free.fr` is an illegal address.

If you want to parse it anyway, you need to set: 

```csharp
ParserOptions.Default.AddressParserCompliance = RfcComplianceMode.Loosest;
```
