### ISSUE TITLE
Getting Access Token for an Outlook Email Account, but it is failing when trying to Authenticate it

### ISSUE THREAD

**Issue by LaurelQuadras** [jstedfast/MailKit#1365]
Using Mailkit code for fetching Outlook Emails using Pop3 and OAuth2.0 Flow, I am able to get the Access Token for my account. But when I am trying to Authenticate with it, it is failing with the below exception

`MailKit.Security.AuthenticationException
  HResult=0x80131500
  Message=Authentication failed.
  Source=MailKit
  StackTrace:
   at MailKit.Net.Pop3.Pop3Client.<AuthenticateAsync>d__100.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EmailOAuth.OutlookOAuthMailbee.<OutlookOAuth3>d__2.MoveNext() in C:\git\emailoauth\EmailOAuth\EmailOAuth\OutlookOAuthMailbee.cs:line 193
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EmailOAuth.Program.<Main>d__0.MoveNext() in C:\git\emailoauth\EmailOAuth\EmailOAuth\Program.cs:line 11

  This exception was originally thrown at this call stack:
    [External Code]
    EmailOAuth.OutlookOAuthMailbee.OutlookOAuth3() in OutlookOAuthMailbee.cs
    [External Code]
    EmailOAuth.Program.Main(string[]) in Program.cs
`

The access token seem to be proper. But I'm not able to authenticate it. I need help in figuring out why it is not authenticating the Outlook Email Account and fetching my emails. I am getting error in the line: await client.AuthenticateAsync(oauth2);

The following is the code sample I am using

`           string clientId = "clientId";
            string clientSecret = "clientSecret";
            string tenantId = "tenantId";

            var options = new PublicClientApplicationOptions
            {
                ClientId = clientId,
                TenantId = tenantId,
                RedirectUri = "http://localhost"
            };

            var publicClientApplication = PublicClientApplicationBuilder
                .CreateWithApplicationOptions(options)
                .Build();

            var scopes = new string[] {
                "https://outlook.office.com/POP.AccessAsUser.All",  
            };

            var authToken = await publicClientApplication.AcquireTokenInteractive(scopes).ExecuteAsync();

            var oauth2 = new SaslMechanismOAuth2(authToken.Account.Username, authToken.AccessToken);

            using (var client = new Pop3Client())
            {
                await client.ConnectAsync("outlook.office365.com", 995, SecureSocketOptions.SslOnConnect);
                await client.AuthenticateAsync(oauth2);
                await client.DisconnectAsync(true);
            }`

**Comment by jstedfast** [comment]
I would recommend asking here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

I don't know how to debug this issue because the issue isn't with MailKit, it's clearly something to do with the token.
