### ISSUE TITLE
Cannot connect to a specific MDaemon Server under linux OS

### ISSUE THREAD

**Issue by Sbaia** [jstedfast/MailKit#1377]
**Describe the bug**

Only in Linux environment, only for some MDaemon IMAP server, after CAPABILITY command the ImapClient throw exception
"MailKit.Net.Imap.ImapProtocolException: The IMAP server has unexpectedly disconnected."

**Platform (please complete the following information):**
 - OS: Linux, only in Linux OS
 - .NET Runtime: CoreCLR
 - .NET Framework: NET5.0
 - MailKit Version: latest

**Exception**

The IMAP server has unexpectedly disconnected.
at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken)
at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken)
at MailKit.Net.Imap.ImapEngine.ReadTokenAsync(Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.Imap.ImapCommand.StepAsync(Boolean doAsync)
at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
at MailKit.Net.Imap.ImapEngine.QueryCapabilitiesAsync(Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)

**To Reproduce**
Try to connect to mail server iomedia.it in SSL protocol to 993 protocol.
If you connect to iomedia.it:143 the CAPABILITY command crash after STARTTLS command

**Expected behavior**
I suppose that the connection between Linux or Windows shoud have the same behaviour. 

**Code Snippets**

```csharp
using (var client = new ImapClient(new ConsoleLogger())
                       {
                           SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13
                       })
                {
                    client.ServerCertificateValidationCallback = (sender, certificate, chain, errors) => true;
                    client.Connect("mail.iomedia.it", 993, true);
                    client.Disconnect(true);
                }
                Console.WriteLine("DONE");

```

**Protocol Logs**
Please include a protocol log (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.

To get a protocol log, follow one of the following code snippets:

```csharp
CONNECT
S:* OK iomedia.it IMAP4rev1 MDaemon 9.6.6 ready
C:A00000000 CAPABILITY
```

**Comment by Sbaia** [comment]
Exacly, when MailKey read from the Stream in ReadAhead, reads 0 bytes but really connection was up, ma è stata trattata come chiusa.
It is as if the server did not receive the end-of-command characters, even if \r\n has been sent

**Comment by jstedfast** [comment]
I haven't been able to connect to mail.iomedia.it at all, so I can't debug this at all.

FWIW, the code is definitely sending the \r\n:

```csharp
var ic = QueueCommand (cancellationToken, null, "CAPABILITY\r\n");
```

Plus I have a unit test for this scenario.

The bug definitely seems to be server-side.

**Comment by Sbaia** [comment]
Hi J,
the server has removed SSL certificate, perhaps they realized that had a problem.

Thanks
