### ISSUE TITLE
System.Net.NameResolution is not supported on this platform. when connect to smtp server

### ISSUE THREAD

**Issue by zonggang** [jstedfast/MailKit#1394]
**Describe the bug**
System.Net.NameResolution is not supported on this platform. when connect to smtp server

**Platform:**
 - OS: Windows
 - .NET Framework: .Net 6
 - MailKit Version: 3.3.0

**Exception**
 Unhandled exception rendering component: System.Net.NameResolution is not supported on this platform.
System.PlatformNotSupportedException: System.Net.NameResolution is not supported on this platform.
   at System.Net.Dns.GetHostAddressesAsync(String hostNameOrAddress)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.SocketUtils.ConnectAsync(String host, Int32 port, IPEndPoint localEndPoint, Int32 timeout, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailService.ConnectNetwork(String host, Int32 port, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)

**Code Snippets**
var client = new SmtpClient();
client.Connect(host, port, false);

**Comment by jstedfast** [comment]
You're not running your app on Windows, you are running it in a browser using webAssembly which doesn't allow networking.

Sorry but you aren't going to be able to get any networking library to work.
