### ISSUE TITLE
An error occurred while attempting to establish an SSL or TLS connection

### ISSUE THREAD

**Issue by johnmartin226** [jstedfast/MailKit#1413]
**SSL certificate error**
'm trying to make a simple email viewer , but this SSL error is distracting me to continue , some emails works fine and some i get this error , like i have two yahoo emails , one account works , the other doesn't work ! it's the same imap what's the issue ?

NOTE : after testing and checking , i get SSL error but in logs the imap is connected and even got emails !

**Platform (please complete the following information):**
 - OS: windows 
 - .NET Runtime: `<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />`
 - .NET Framework: `<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />`
 - MailKit Version: latest

**Exception**
```
An error occurred while attempting to establish an SSL or TLS connection.

This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
the following reasons:

1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid.
5. The set of SSL/TLS protocols supported by the client and server do not match.
6. You are trying to connect to a port which does not support SSL/TLS.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.

   at MailKit.Net.Imap.ImapClient.<ConnectAsync>d__108.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at emailviewer.Form1.LoginChecker(String login, String pass, String imp, String PrxIP, Int32 PrxPrt, String PrxLogin, String PrxPass)
```
----------

**To Reproduce**
searching emails and sort them then showing it

**Expected behavior**
to login without any errors since this email account doesn't require enabling IMAP like google

**Code Snippets**
If applicable, add code snippets to help explain your problem.

```csharp
//  Using client = New ImapClient()


                client.CheckCertificateRevocation = False

                client.Connect(imp, 993, SecureSocketOptions.Auto)

                client.Authenticate(login, pass)
                Dim inbox = client.Inbox
                inbox.Open(FolderAccess.[ReadOnly])

                Dim query = SearchQuery.DeliveredAfter(DateTime.Parse("2018-01-01"))


Dim uids = inbox.Search(query)
If uids.Count > 0 Then
'some code here
End If

client.Disconnect(True)


Catch ex As Exception
If (ex.Message.Contains("authentication failed") OrElse ex.Message.Contains("Invalid") OrElse ex.Message.Contains("Authentication") OrElse ex.Message.Contains("login failed")) Then
            
             MsgBox("wrong pass")


        ElseIf (ex.Message.Contains("Failed to connect") OrElse ex.Message.Contains("host") OrElse ex.Message.Contains(" Bad Request") OrElse ex.Message.Contains("connnection") OrElse ex.Message.Contains("ssl")) Then
             MsgBox("attempting a retry. " &  ex.Message)
           'my thread retry code
        Else
            MsgBox("unexpected error : " &  ex.Message)

        End If


End Try
```

**Protocol Logs**
Please include a protocol log (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.

To get a protocol log, follow one of the following code snippets:

```csharp
// log to a file called 'imap.log'
Connected to imaps://imap.gotadsl.co.uk:993/
S: * OK APM IMAP Redirector ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT IDLE
S: A00000000 OK CAPABILITY completed
C: A00000001 LOGIN ******** ********
S: A00000001 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE] Logged in
C: A00000002 NAMESPACE
S: * NAMESPACE (("INBOX." ".")) NIL NIL
S: A00000002 OK Namespace completed (0.001 + 0.000 secs).
C: A00000003 LIST "" "INBOX" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\HasChildren) "." INBOX
S: A00000003 OK List completed (0.002 + 0.000 + 0.001 secs).
C: A00000004 LIST (SPECIAL-USE) "" "*" RETURN (SUBSCRIBED CHILDREN)
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Trash) "." INBOX.Trash
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Drafts) "." INBOX.Drafts
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Archive) "." INBOX.Archive
S: * LIST (\Subscribed \HasNoChildren \Junk) "." INBOX.Spam
S: * LIST (\Subscribed \HasNoChildren \UnMarked \Sent) "." INBOX.Sent
S: A00000004 OK List completed (0.001 + 0.000 secs).
C: A00000005 EXAMINE INBOX (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft Flagged)
S: * OK [PERMANENTFLAGS ()] Read-only mailbox.
S: * 1942 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 1197] First unseen.
S: * OK [UIDVALIDITY 1288822399] UIDs valid
S: * OK [UIDNEXT 12092] Predicted next UID
S: * OK [HIGHESTMODSEQ 29584] Highest
S: A00000005 OK [READ-ONLY] Examine completed (0.003 + 0.000 + 0.002 secs).
C: A00000006 UID SEARCH RETURN (ALL) SINCE 31-Jul-2018
S: * ESEARCH (TAG "A00000006") UID ALL 8913:8922,8936:8937,8939,8942,8948,8951:8952,8954,9020:9024,9088:9092,10384,10627,11176:11178,11818:11819
S: A00000006 OK Search completed (0.018 + 0.000 + 0.017 secs).
C: A00000007 UID SEARCH RETURN (ALL) SINCE 1-Jul-2022 
S: * ESEARCH (TAG "A00000007") UID
S: A00000007 OK Search completed (0.007 + 0.000 + 0.006 secs).
C: A00000008 UID FETCH 8913 (BODY.PEEK[])
S: * 69 FETCH (UID 8913 BODY[] {9733}
''EMAILS''
S: A00000042 OK Fetch completed (0.001 + 0.000 secs).
C: A00000043 LOGOUT
S: * BYE Logging out
S: A00000043 OK Logout completed (0.001 + 0.000 secs).
```

**Additional context**
So my software get me SSL error for this connection , and it doesn't make anysense that it's signed in and fetched emails , what possibly could be the issue here ? 
if you can help with C# would be okay since there's translators

**Comment by jstedfast** [comment]
Ignore the protocol log because nothing was written to the log file if it threw that exception which can *only* happen at Connect time.

There's nothing I can tell you that isn't already in the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException).
