### ISSUE TITLE
Syntax error through client.send() after successful authentication

### ISSUE THREAD

**Issue by Daenges** [jstedfast/MailKit#1452]
I get a `MailKit.Net.Smtp.SmtpCommandException: 'Syntax error, command unrecognized'` crash on sending a message after a successful SMTP authentication.

```
Connected to ...
S: 220 ... ESMTP outbound-server; Fri, 21 Oct 2022 23:23:16 +0200
C: EHLO Der-Geraet
S: 250-... Hello Der-Geraet [/...] , Pleased to meet you
S: 250-DSN
S: 250-HELP
S: 250 AUTH LOGIN DIGEST-MD5 PLAIN CRAM-MD5
C: AUTH DIGEST-MD5
S: 334 ...
C: ********
S: 334 ...
C:
S: 235 Authentication successful
C: MAIL FROM:<joey@friends.com>
S: 500 Syntax error, command unrecognized
C: RSET
S: 250 Requested mail action okay, completed
Unhandled exception. MailKit.Net.Smtp.SmtpCommandException: Syntax error, command unrecognized
   at MailKit.Net.Smtp.SmtpClient.OnSenderNotAccepted(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
   at MailKit.Net.Smtp.SmtpClient.ProcessMailFromResponse(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
   at MailKit.Net.Smtp.SmtpClient.MailFromAsync(FormatOptions options, MimeMessage message, MailboxAddress mailbox, SmtpExtension extensions, Int64 size, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.MailTransport.Send(MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at TestClient.Program.Main(String[] args) in ... .cs:line 36
```

I use the [Sample Code](https://github.com/jstedfast/MailKit#sending-messages) for sending a message.

**Comment by jstedfast** [comment]
Looks like a server bug. The `MAIL FROM:<joey@friends.com>` is 100% correct syntax.

**Comment by Daenges** [comment]
@jstedfast It can not be a server bug. I tried the exact same thing in Python and it works.

**Comment by Daenges** [comment]
![pythonExample](https://user-images.githubusercontent.com/57369924/197419846-0163b30c-c014-4ede-b046-7b3664725d6b.jpg)

Example taken from [here](https://realpython.com/python-send-email/#sending-your-plain-text-email).

**Comment by jstedfast** [comment]
Okay, I see the problem. It's the second 334 response. That is causing MailKit's digest-md5 mechanism to send a reset request at which point the server responds success. But by this point, mailkit and the server are out of sync.

This is definitely a server bug, but you might be able to work around it by using a different AUTH mechanism.

client.AuthenticationMechanisms.Remove("DIGEST-MD5")
client.Authenticate(...)

**Comment by jstedfast** [comment]
Yea your python code is not using DIGEST-MD5.

**Comment by jstedfast** [comment]
Was at dinner before using my phone, so had to wait until now to respond with some sample code that should work just like the python code:

```csharp
using (var client = new SmtpClient ()) {
    client.Connect (hostName, 465, SecureSocketOptions.SslOnConnect);

    // Enforce LOGIN authentication:
    var login = new SaslMechanismLogin (username, password);
    client.Authenticate (login);

    client.Send (message);
    client.Disconnect (true);
}
```
