### ISSUE TITLE
Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1

### ISSUE THREAD

**Issue by JamalAPI** [jstedfast/MailKit#1462]
**Describe the bug**
I have System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0 installed on my system, yet MailKit is referencing System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1 which is not installed. 

In App.Config, I have:
`
<dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
</dependentAssembly>
`
**Platform (please complete the following information):**
 - OS: Window 11 Pro
 - .NET Runtime: 4.8
 - .NET Framework: 4.8
 - MailKit Version: 3.4.2

**Exception**

System.IO.FileLoadException: 'Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

**Code Snippets**
var message = new MimeMessage();    // **exception on this line**

**Additional context**
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=System.Memory
  StackTrace:
   at System.Span`1..ctor(T[] array)
   at MimeKit.Utils.ValueStringBuilder..ctor(Int32 initialCapacity)
   at MimeKit.Utils.Rfc2047.Encode(FormatOptions options, Encoding charset, String text, Boolean phrase)
   at MimeKit.Header.EncodeUnstructuredHeader(ParserOptions options, FormatOptions format, Encoding encoding, String field, String value)
   at MimeKit.Header.EncodeAddressHeader(ParserOptions options, FormatOptions format, Encoding encoding, String field, String value)
   at MimeKit.Header.FormatRawValue(FormatOptions format, Encoding encoding, String value)
   at MimeKit.Header.SetValue(FormatOptions format, Encoding encoding, String value)
   at MimeKit.Header..ctor(Encoding encoding, HeaderId id, String value)
   at MimeKit.HeaderList.set_Item(HeaderId id, String value)
   at MimeKit.MimeMessage..ctor()
   at SharpLibTestApp.MailKitForm.button1_Click(Object sender, EventArgs e) in C:\Users\Jamal\Documents\Visual Studio 2022\Projects\SharpLib\SharpLibTestApp\MailKitForm.cs:line 75
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at LimoWizCSharpLibTestApp.Program.Main() in C:\Users\Jamal\Documents\Visual Studio 2022\Projects\SharpLib\CSharpLibTestApp\Program.cs:line 25

**Comment by jstedfast** [comment]
🤷‍♂️

I don't seem to have this issue so it seems to be a problem on your end.

**Comment by WaltteriVa** [comment]
@JamalAPI 
What worked for me: 
1. Run visual studio as admin and launch developer command prompt
2. gacutil /i path/to/the/dll (should be something along the lines of \packages\System.Runtime.CompilerServices.Unsafe.4.5.3\lib\net461\System.Runtime.CompilerServices.Unsafe.dll)

**Comment by jstedfast** [comment]
This seems to have some useful info: https://stackoverflow.com/questions/62764744/could-not-load-file-or-assembly-system-runtime-compilerservices-unsafe

Especially regarding the NuGet vs Assembly versioning scheme.

**Comment by jstedfast** [comment]
StackExchange.Redis seemed to have the same issue: https://github.com/StackExchange/StackExchange.Redis/issues/1128

They seem to have talked to the Microsoft Build tools team and concluded that the bug is in MSBuild targets.

Which version of Visual Studio do you have installed?

**Comment by jstedfast** [comment]
FWIW, the dependencies work as follows:

* MailKit v3.4.2 depends on:
    * MimeKit v3.4.2, which depends on:
        * System.Memory v4.5.5, which depends on:
            * System.Runtime.CompilerServices.Unsafe v4.5.3

Apparently, if your project depends on some other NuGet which ends up depending on a *newer* version of System.Runtime.CompilerServices.Unsafe, then you will hit this issue.

In other words, unless *every single NuGet dependency that your project references depends on the exact same version of System.Runtime.CompilerServices.Unsafe.dll*, you will hit this issue.

**Comment by JamalAPI** [comment]
@jstedfast, thanks for the response. I tried all suggested fixes from the various sources on to no avail. The good news that If I create a clean Winforms App using .NET Framework 4.0 (in VS 2022 Pro), then MailKit works fine.  I also updated CompilerServices.Unsafe assembly to version 6.0 via NuGet Package Manager and MailKit continued to work fine.  I am adding other 3rd party libs to see what would trigger the issue.
So, definitely, it's a conflict somewhere. I find out the real reason, I'll give feedback.

**Comment by RPORTNOFF** [comment]
I was previously using MailKit 2.15 with .NET Framework 4.5.2 and it worked fine.

I upgraded to MailKit 4.7.0 and .NET Framework 4.8 and I am now getting this "Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1" error.

Note that I am building DLL as x86

I tried all of the suggestions in this post but none fixed the problem.

I also tried deleting and re-creating the entire project but that did not fix the problem.

**Comment by jstedfast** [comment]
Adding an app.config has fixed it for everyone else:

```xml
<dependentAssembly>
    <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="4.0.4.1" />
</dependentAssembly>
```

**Comment by jstedfast** [comment]
I have no idea. I am not knowledgeable in this area. Everything has always just worked fine for me.
