### ISSUE TITLE
ParseException: Invalid local-part at offset 2

### ISSUE THREAD

**Issue by ajtruckle** [jstedfast/MailKit#1483]
Hi !

A user of my software has just encountered this exception message with my tool that sends emails via GMail:
```
<LogEntry Date="2022-12-09 00:10:58" Severity="Exception" Source="MSAToolsGMailLibrary.MSAToolsGMailLibraryClass.SendEmail" ThreadId="1">
	<Exception Type="MimeKit.ParseException" Source="MimeKit.InternetAddress.TryParseLocalPart">
		<Message>Invalid local-part at offset 2</Message>
		<StackTrace>at MimeKit.InternetAddress.TryParseLocalPart(Byte[] text, Int32&amp; index, Int32 endIndex, RfcComplianceMode compliance, Boolean skipTrailingCfws, Boolean throwOnError, String&amp; localpart)
					at MimeKit.InternetAddress.TryParseAddrspec(Byte[] text, Int32&amp; index, Int32 endIndex, Byte[] sentinels, RfcComplianceMode compliance, Boolean throwOnError, String&amp; addrspec, Int32&amp; at)
					at MimeKit.InternetAddress.TryParseMailbox(ParserOptions options, Byte[] text, Int32 startIndex, Int32&amp; index, Int32 endIndex, String name, Int32 codepage, Boolean throwOnError, InternetAddress&amp; address)
					at MimeKit.InternetAddress.TryParse(AddressParserFlags flags, ParserOptions options, Byte[] text, Int32&amp; index, Int32 endIndex, Int32 groupDepth, InternetAddress&amp; address)
					at MimeKit.MailboxAddress.Parse(ParserOptions options, String text)
					at MSAToolsGMailLibrary.MSAToolsGMailLibraryClass.SendEmail(String From, String Subject, String Attachment)</StackTrace>
	</Exception>
</LogEntry>
```

My application is C# and I have MimeKit 3.4.2 installed.

Please let me know if you need more information.

**Comment by jstedfast** [comment]
I would need to know the email address that it was trying to parse.

**Comment by ajtruckle** [comment]
I have split his email up to avoid spamming:


***@***.***>

at

***@***.***>

com


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jstedfast** [comment]
I guarantee that MimeKit didn't have a problem parsing that. It must have been a different address.

**Comment by jstedfast** [comment]
If you find the email address that was causing the issue, let me know and I will investigate.
