### ISSUE TITLE
Can anyone shed light on this exception that a user has when sending email and using MikeKit?

### ISSUE THREAD

**Issue by ajtruckle** [jstedfast/MailKit#1492]
Can anyone sched any light on this exception that was triggered on a users computer when my DLL was used to try and send an email?

Exception:

```
<LogEntry Date="2022-12-23 05:57:59" Severity="Exception" Source="MSAToolsGMailLibrary.MSAToolsGMailLibraryClass.SendEmail" ThreadId="1">
    <Exception Type="System.IO.FileNotFoundException" Source="System.Span`1..ctor">
    <Message>Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</Message>
         <StackTrace>   at System.Span`1..ctor(T[] array)
                        at MimeKit.Utils.ValueStringBuilder..ctor(Int32 initialCapacity)
                        at MimeKit.Utils.Rfc2047.Encode(FormatOptions options, Encoding charset, String text, Boolean phrase)
                        at MimeKit.Utils.Rfc2047.EncodeText(FormatOptions options, Encoding charset, String text)
                        at MimeKit.Header.EncodeUnstructuredHeader(ParserOptions options, FormatOptions format, Encoding encoding, String field, String value)
                        at MimeKit.Header.EncodeAddressHeader(ParserOptions options, FormatOptions format, Encoding encoding, String field, String value)
                        at MimeKit.Header.FormatRawValue(FormatOptions format, Encoding encoding, String value)
                        at MimeKit.Header.SetValue(FormatOptions format, Encoding encoding, String value)
                        at MimeKit.Header.SetValue(Encoding encoding, String value)
                        at MimeKit.Header..ctor(Encoding encoding, HeaderId id, String value)
                        at MimeKit.HeaderList.set_Item(HeaderId id, String value)
                        at MimeKit.MimeMessage..ctor()
                        at MSAToolsGMailLibrary.MSAToolsGMailLibraryClass.SendEmail(String From, String Subject, String Attachment) 
        </StackTrace>
    </Exception>
</LogEntry>
```

**Comment by ajtruckle** [comment]
I just noticed that this issue is also affecting me too now:

![Exception](https://user-images.githubusercontent.com/7985331/209395881-1aea9b38-0f73-47b5-9c7e-b7a1f2394a29.jpg)

Not sure how to address this.

**Comment by ajtruckle** [comment]
I see this realest discussion on the exception:

https://stackoverflow.com/questions/62764744/could-not-load-file-or-assembly-system-runtime-compilerservices-unsafe

I have Unsafe version 6.0.0 installed. But it was all handled by the NuGet Package Manager.

Please advise. Thank you.

**Comment by ajtruckle** [comment]
I tried adding this to the config file and it seems to make no difference:

```
			<dependentAssembly>
				<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0"/>
			</dependentAssembly>
```

**Comment by ajtruckle** [comment]
Update:

If I downgrade MimeKit from 3.4.3 back to 3.4.2 then my DLL functions fine.

Await update.

**Comment by jstedfast** [comment]
MimeKit v3.4.3 was my best attempt at fixing this and it solved it for the people that hit this problem using 3.4.2 and older versions.

But you are saying the opposite?

I'm stumped. I don't have this problem and have never been able to reproduce it.

It has to be a conflict with another library you are depending on.

**Comment by ajtruckle** [comment]
Possibly ... I have a few projects that all use NuGet packages. To my knowledge, only two of the projects specifically mention this "Unsafe" NuGet package, and both are on 6.0.0. So I am slightly confused myself. The others that have NuGet packages do not use "Unsafe" from what I can tell.

I am not well knowledges with the mechanics of NuGet packages. If you want me to look for certain data about my projects setups and / or try anything specific then let me know.
