### ISSUE TITLE
Syntactically invalid HELO argument(s)

### ISSUE THREAD

**Issue by dimkadv2** [jstedfast/MailKit#1501]
Hi!

**Platform (please complete the following information):**
 - OS: Windows 7
 - .NET Runtime: .NET Desktop Runtime 6.0.12
 - MailKit Version: 3.3.0

**Exception**
2023-01-09 12:04:46.3702|ERROR|1|MailKit.Net.Smtp.SmtpCommandException: Syntactically invalid HELO argument(s)|MailKit.Net.Smtp.SmtpCommandException: Syntactically invalid HELO argument(s)
   at MailKit.Net.Smtp.SmtpClient.EhloAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at Reports.Services.ReportExportEmailService.SendMessages(IEnumerable`1 messages, ReportSendType reportSendType)
   at Reports.Services.ReportExportEmailService.Export(XtraReport report, RibbonBarManager ribbonBarManager)
   at Reports.Services.Commands.ExportEmailCommand.ExportToEmail(Object sender, ItemClickEventArgs e)
**To Reproduce**
Change PC name with '_' or russian name

**Expected behavior**
before updating the application to net6-windows there were no problems, messages were sent to the mail (unfortunately I can't tell you what version it was before switching to the new platform)

How can i fix my problem? thanks

**Comment by jstedfast** [comment]
I seem to recall a similar bug report like this where it was determined that the problem was in Microsoft's IDN implementation on some versions of .NET (can't recall if it was .NET Framework or .NET Core that was broken).

I think this was the reason that I added the [IPunycode](https://github.com/jstedfast/MimeKit/blob/master/MimeKit/Encodings/IPunycode.cs) interface to MimeKit.

**Comment by jstedfast** [comment]
What *exactly* is the host name being sent in the EHLO/HELO command to the server?

**Comment by jstedfast** [comment]
You can override whatever string gets used by setting the `client.LocalDomain` property.

**Comment by dimkadv2** [comment]
> What exactly is the host name being sent in the EHLO/HELO command to the server?

for example 'ГЛАВ_БУХ'

> You can override whatever string gets used by setting the `client.LocalDomain` property.

I will try this option

**Comment by dimkadv2** [comment]
> You can override whatever string gets used by setting the client.LocalDomain property.

yes it helped thanks!

**Comment by jstedfast** [comment]
> > What exactly is the host name being sent in the EHLO/HELO command to the server?

> for example 'ГЛАВ_БУХ'

There's no way it sends that as the host name in the EHLO/HELO command.

Did you get this from the logs or is this just your PC name?

**Comment by dimkadv2** [comment]
> > > What exactly is the host name being sent in the EHLO/HELO command to the server?
> 
> > for example 'ГЛАВ_БУХ'
> 
> There's no way it sends that as the host name in the EHLO/HELO command.
> 
> Did you get this from the logs or is this just your PC name?

This is PC name from which the mailing was attempted.

**Comment by jstedfast** [comment]
If you remove the _ from your PC name, does it work?

**Comment by jstedfast** [comment]
ping.
