### ISSUE TITLE
The IMAP server has unexpectedly disconnected

### ISSUE THREAD

**Issue by johnmartin226** [jstedfast/MailKit#1528]
**Describe the bug**
i'm trying to make a little mail client project with vb.net ( I know vb.net is a low language but I'm learning )
I'm having an issue with my btinternet.com email , my connection works well with most of the providers but this site no..
the confusing part is it works after like 10-20 tries i keep pressing login in my software and eventually it logins

i get "The IMAP server has unexpectedly disconnected"
and this is the stack track for the error

**The IMAP server has unexpectedly disconnected.
   at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapEngine.ReadTokenAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.<StepAsync>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<RunAsync>d__191.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Imap.ImapClient.<AuthenticateAsync>d__103.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at mailfire.Form1.VB$StateMachine_21_Checker.MoveNext()
----------**
If applicable, add code snippets to help explain your problem.

```vb.net
//   Using client = New ImapClient()     
                    client.CheckCertificateRevocation = False
                    client.Connect(imp, 993, SecureSocketOptions.Auto)
                    client.Authenticate(login, pass)
```

my code is pretty simple

**Comment by jstedfast** [comment]
This just means that your server disconnected you. Since it works for every other server, it probably indicates a server bug that you should contact them about.
