### ISSUE TITLE
AuthenticateAsync throws Pop3ProtocolException in Windows 11

### ISSUE THREAD

**Issue by kobruleht** [jstedfast/MailKit#1544]
**Describe the bug**

Calling AuthenticateAsync  for pop3.zone.eu  POP3 server in Windows 11 throws  Pop3ProtocolException  The POP3 server has unexpectedly disconnected.

**Platform (please complete the following information):**
 - OS: Windows 11
 - .NET Runtime: CoreCLR
 - .NET Framework:  .NET 7.0.4
 - MailKit Version:  3.6.0

**Exception**

```
MailKit.Net.Pop3.Pop3ProtocolException: The POP3 server has unexpectedly disconnected.
   at MailKit.Net.Pop3.Pop3Stream.OnReadAhead(Int32 start, Int32 nread)
   at MailKit.Net.Pop3.Pop3Stream.ReadAheadAsync(CancellationToken cancellationToken)
   at MailKit.Net.Pop3.Pop3Stream.ReadLineAsync(ByteArrayBuilder builder, CancellationToken cancellationToken)
   at MailKit.Net.Pop3.Pop3Engine.ReadLineAsync(CancellationToken cancellationToken)
   at MailKit.Net.Pop3.Pop3Engine.ReadResponseAsync(Pop3Command pc, CancellationToken cancellationToken)
   at MailKit.Net.Pop3.Pop3Engine.RunAsync(Boolean throwOnError, CancellationToken cancellationToken)
   at MailKit.Net.Pop3.Pop3Client.SendCommandAsync(CancellationToken token, Encoding encoding, String format, Object[] args)
   at MailKit.Net.Pop3.Pop3Client.AuthenticateAsync(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
```

**To Reproduce**

Run code from Visual Studio IDE in Windows:

```csharp
    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
     using var client = new Pop3Client();
    await client.ConnectAsync("pop3.zone.eu", 995, true);
    // Can provide user name and password
    await client.AuthenticateAsync("Pop3user", "Pop3pass");
```
**Expected behavior**

No exception.

**Protocol Logs**
```
2023-04-10T09:19:35Z Connected to pops://pop3.zone.eu:995/
2023-04-10T09:20:35Z S: +OK ZoneMail | POP3 Server ready for requests from x.x.x.x 2ez6sk6hny5ecdfd
2023-04-10T09:20:35Z S: -ERR Disconnected for inactivity
2023-04-10T09:20:35Z C: CAPA
2023-04-10T09:20:35Z C: USER ********
```

**Comment by jstedfast** [comment]
See the -ERR response in your log. This is a server bug.

**Comment by kobruleht** [comment]
This occurs only when code is running in Windows. In Debian it works properly.

**Comment by jstedfast** [comment]
Does your POP3 server respond with `-ERR Disconnected for inactivity` when connecting from Debian? If not, then that's the problem.

**Comment by kobruleht** [comment]
AuthenticateAsync runs long time before it reports error. 
So server does not receive any commands and disconnects after timeout.  

I added Thread.Sleep(1000) before AuthenticateAsync but problem persists.

**Comment by jstedfast** [comment]
In about 30 minutes, try the latest build from https://www.myget.org/feed/mimekit/package/nuget/MailKit

Make sure it has today's date.

**Comment by kobruleht** [comment]
Tried version 3.6.0.639 but got same exception.

2023-04-10T20:10:41Z Connected to pops://pop3.zone.eu:995/
2023-04-10T20:11:41Z S: +OK ZoneMail | POP3 Server ready for requests from 85.253.49.142 b6jxwygm3ghf4fbc
2023-04-10T20:11:41Z S: -ERR Disconnected for inactivity
2023-04-10T20:11:41Z C: CAPA
2023-04-10T20:11:41Z C: USER ********
