### ISSUE TITLE
[iCloud] .AppendAsync not working?!?

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1551]
@jstedfast I just ran into an issue where after sending a mail I wanted to append it to the SENT folder and got exception below
```
MailKit.Net.Imap.ImapCommandException: The IMAP server replied to the 'APPEND' command with a 'NO' response: Unexpected exception (took 3548 ms)
   at MailKit.Net.Imap.ImapFolder.AppendAsync(FormatOptions options, IAppendRequest request, Boolean doAsync, CancellationToken cancellationToken)
   at Unusual.Mail.MailClient.AppendToSentFolder(Mail mail)
```
Also: as a result my iPhone/iPad now are spammed with non-stop 'new message' notifications. Looks like the iOS email client is reading the same mail over and over again...
This is **MailKitLite 3.6.0**

Would you have any idea what might be going on?

Here are the details when connecting
```
2023-04-17 08:41:07:332 Imap.Connected: 'imaps://imap.mail.me.com:993/'
2023-04-17 08:41:07:489 Imap.S: * OK [CAPABILITY XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 SASL-IR AUTH=ATOKEN AUTH=PLAIN] (2313B20-3ff771b405ab) pv50p00im-tygg10010601.me.com
2023-04-17 08:41:07:503 Imap.C: A00000000 AUTHENTICATE PLAIN AGRpZXJrLmRyb3RoQGljbG91ZC5jb20AZGRwYy1pYmhwLWNrcXktenVsdA==
2023-04-17 08:41:08:015 Imap.S: A00000000 OK user dierk.droth authenticated
2023-04-17 08:41:08:017 Imap.C: A00000001 CAPABILITY
2023-04-17 08:41:08:182 Imap.S: * CAPABILITY XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 CONDSTORE ENABLE QRESYNC QUOTA XAPPLELITERAL NAMESPACE UIDPLUS CHILDREN BINARY UNSELECT SORT CATENATE URLAUTH LANGUAGE ESEARCH ESORT THREAD=ORDEREDSUBJECT THREAD=REFERENCES CONTEXT=SEARCH CONTEXT=SORT WITHIN SASL-IR SEARCHRES METADATA ID XMSEARCH X-SUN-SORT ANNOTATE-EXPERIMENT-1 X-UNAUTHENTICATE X-SUN-IMAP XUM1 MULTISEARCH IDLE X-APPLE-REMOTE-LINKS LIST-STATUS
2023-04-17 08:41:08:183 Imap.S: A00000001 OK Completed
2023-04-17 08:41:08:187 Imap.C: A00000002 NAMESPACE
2023-04-17 08:41:08:392 Imap.S: * NAMESPACE (("" "/")) NIL NIL
2023-04-17 08:41:08:392 Imap.S: A00000002 OK NAMESPACE completed (took 0 ms)
2023-04-17 08:41:08:396 Imap.C: A00000003 LIST "" "INBOX"
2023-04-17 08:41:08:741 Imap.S: * LIST (\Noinferiors) "/" "INBOX"
2023-04-17 08:41:08:741 Imap.S: A00000003 OK LIST completed (took 1 ms)
2023-04-17 08:41:08:745 Imap.C: A00000004 SELECT INBOX (CONDSTORE)
2023-04-17 08:41:08:970 Imap.S: * 0 EXISTS
2023-04-17 08:41:08:970 Imap.S: * 0 RECENT
2023-04-17 08:41:08:970 Imap.S: * OK [UIDVALIDITY 1475088412]
2023-04-17 08:41:08:970 Imap.S: * OK [UIDNEXT 968]
2023-04-17 08:41:08:970 Imap.S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen \Recent $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 $Forwarded Redirected $NotJunk NotJunk)
2023-04-17 08:41:08:970 Imap.S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \Recent $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 $Forwarded Redirected $NotJunk NotJunk \*)]
2023-04-17 08:41:08:970 Imap.S: * OK [HIGHESTMODSEQ 393317264013185]
2023-04-17 08:41:08:970 Imap.S: A00000004 OK [READ-WRITE] SELECT completed (took 20 ms)
2023-04-17 08:41:08:974 Imap.C: A00000005 LIST "" "%"
2023-04-17 08:41:09:182 Imap.S: * LIST () "/" "Sent Items"
2023-04-17 08:41:09:182 Imap.S: * LIST () "/" "Done"
2023-04-17 08:41:09:182 Imap.S: * LIST () "/" "Archive"
2023-04-17 08:41:09:182 Imap.S: * LIST (\Trash) "/" "Deleted Messages"
2023-04-17 08:41:09:182 Imap.S: * LIST () "/" "Junk"
2023-04-17 08:41:09:182 Imap.S: * LIST () "/" "Notes"
2023-04-17 08:41:09:182 Imap.S: * LIST (\Sent) "/" "Sent Messages"
2023-04-17 08:41:09:182 Imap.S: * LIST () "/" "Deleted Items"
2023-04-17 08:41:09:182 Imap.S: * LIST (\Noinferiors) "/" "INBOX"
2023-04-17 08:41:09:182 Imap.S: * LIST () "/" "Drafts"
2023-04-17 08:41:09:182 Imap.S: A00000005 OK LIST completed (took 2 ms)
2023-04-17 08:41:09:187 Imap.C: A00000006 SUBSCRIBE Done
2023-04-17 08:41:09:433 Imap.S: A00000006 OK SUBSCRIBE completed (took 34 ms)
2023-04-17 08:41:09:434 Imap.C: A00000007 LIST "" "%"
2023-04-17 08:41:09:663 Imap.S: * LIST (\Noinferiors) "/" "INBOX"
2023-04-17 08:41:09:663 Imap.S: * LIST (\Trash) "/" "Deleted Messages"
2023-04-17 08:41:09:663 Imap.S: * LIST () "/" "Drafts"
2023-04-17 08:41:09:663 Imap.S: * LIST () "/" "Notes"
2023-04-17 08:41:09:663 Imap.S: * LIST (\Sent) "/" "Sent Messages"
2023-04-17 08:41:09:663 Imap.S: * LIST () "/" "Junk"
2023-04-17 08:41:09:663 Imap.S: * LIST () "/" "Done"
2023-04-17 08:41:09:663 Imap.S: * LIST () "/" "Archive"
2023-04-17 08:41:09:663 Imap.S: * LIST () "/" "Sent Items"
2023-04-17 08:41:09:663 Imap.S: * LIST () "/" "Deleted Items"
2023-04-17 08:41:09:663 Imap.S: A00000007 OK LIST completed (took 18 ms)
2023-04-17 08:41:09:663 Imap.C: A00000008 LIST "" "%"
2023-04-17 08:41:09:875 Imap.S: * LIST () "/" "Sent Items"
2023-04-17 08:41:09:875 Imap.S: * LIST () "/" "Done"
2023-04-17 08:41:09:875 Imap.S: * LIST () "/" "Archive"
2023-04-17 08:41:09:875 Imap.S: * LIST (\Trash) "/" "Deleted Messages"
2023-04-17 08:41:09:875 Imap.S: * LIST () "/" "Junk"
2023-04-17 08:41:09:875 Imap.S: * LIST () "/" "Notes"
2023-04-17 08:41:09:875 Imap.S: * LIST (\Sent) "/" "Sent Messages"
2023-04-17 08:41:09:875 Imap.S: * LIST () "/" "Deleted Items"
2023-04-17 08:41:09:875 Imap.S: * LIST (\Noinferiors) "/" "INBOX"
2023-04-17 08:41:09:875 Imap.S: * LIST () "/" "Drafts"
2023-04-17 08:41:09:875 Imap.S: A00000008 OK LIST completed (took 2 ms)
2023-04-17 08:41:09:875 (local) Mail.MailClient.Connected: mailAccount='dierk.droth@icloud.com' hasCondStore=True hasSpecialUse=False hasXlist=False sentFolder='Sent 
```

Here are the full traces of the case
```
!!!
2023-04-17 08:33:27:003 (local) Mail.MailClient.AppendToSentFolder.ImapSemaphoreWaitSync: mailAccount='dierk.droth@icloud.com' currentCount=1 managedThreadId=23
2023-04-17 08:33:27:003 Imap.C: E00000132 UNSELECT
2023-04-17 08:33:27:247 Imap.S: E00000132 OK UNSELECT completed (took 1 ms)
2023-04-17 08:33:27:247 Imap.C: E00000133 SELECT "Sent Messages" (CONDSTORE)
2023-04-17 08:33:27:485 Imap.S: * 2937 EXISTS
2023-04-17 08:33:27:485 Imap.S: * 0 RECENT
2023-04-17 08:33:27:485 Imap.S: * OK [UNSEEN 17]
2023-04-17 08:33:27:485 Imap.S: * OK [UIDVALIDITY 1475179112]
2023-04-17 08:33:27:485 Imap.S: * OK [UIDNEXT 8870]
2023-04-17 08:33:27:485 Imap.S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen \Recent $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 $Forwarded Redirected $NotJunk NotJunk)
2023-04-17 08:33:27:485 Imap.S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \Recent $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 $Forwarded Redirected $NotJunk NotJunk \*)]
2023-04-17 08:33:27:485 Imap.S: * OK [HIGHESTMODSEQ 393317264036880]
2023-04-17 08:33:27:485 Imap.S: E00000133 OK [READ-WRITE] SELECT completed (took 30 ms)
2023-04-17 08:33:27:486 Imap.C: E00000134 UID SEARCH RETURN (ALL) HEADER Message-Id 6H8OXNBIPJU4.07HHPV2MLX7N1@unusual
2023-04-17 08:33:27:737 Imap.S: * ESEARCH (TAG "E00000134")
2023-04-17 08:33:27:737 Imap.S: E00000134 OK SEARCH completed (took 45 ms)
2023-04-17 08:33:27:737 Imap.C: E00000135 APPEND "Sent Messages" {3542}
2023-04-17 08:33:27:903 Imap.S: + go ahead
2023-04-17 08:33:27:903 Imap.C: From: dierk.droth@icloud.com
2023-04-17 08:33:27:903 Imap.C: Date: Mon, 17 Apr 2023 10:32:12 +0200
2023-04-17 08:33:27:903 Imap.C: Subject: 5555
2023-04-17 08:33:27:903 Imap.C: Message-Id: <6H8OXNBIPJU4.07HHPV2MLX7N1@unusual>
2023-04-17 08:33:27:903 Imap.C: MIME-Version: 1.0
2023-04-17 08:33:27:903 Imap.C: To: superuser <dierk.droth1@gmail.com>
2023-04-17 08:33:27:903 Imap.C: Content-Type: multipart/mixed; boundary="=-0yQJ0Uv3tEbwruG4xA+voA=="
2023-04-17 08:33:27:903 Imap.C: --=-0yQJ0Uv3tEbwruG4xA+voA==
2023-04-17 08:33:27:903 Imap.C: Content-Type: text/html; charset=utf-8
2023-04-17 08:33:27:903 Imap.C: Content-Transfer-Encoding: quoted-printable
2023-04-17 08:33:27:903 Imap.C: <html><head>
2023-04-17 08:33:27:903 Imap.C: 	<link rel=3D"preconnect" href=3D"https://fonts.googleapis.com"><link rel=3D=
2023-04-17 08:33:27:903 Imap.C: "preconnect" href=3D"https://fonts.gstatic.com" crossorigin=3D""><link href=
2023-04-17 08:33:27:903 Imap.C: =3D"https://fonts.googleapis.com/css2?family=3DRoboto:ital,wght@0,100;0,300=
2023-04-17 08:33:27:903 Imap.C: ;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=3D=
2023-04-17 08:33:27:903 Imap.C: swap" rel=3D"stylesheet">
2023-04-17 08:33:27:903 Imap.C: 	<style>
2023-04-17 08:33:27:903 Imap.C: 	body { font-family: Roboto; font-size: 14px; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-code { font-family: monospace; font-size: 14px; line-height: 20px=
2023-04-17 08:33:27:903 Imap.C: ; padding: 2px; margin: 0; background-color: #E4E5E9; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-div { font-family: Roboto; font-size: 14px; line-height: 20px; pa=
2023-04-17 08:33:27:903 Imap.C: dding: 2px 0 2px 0; margin: 0; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-dark-mode { background-color: black; color: white; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-h1 { font-family: Roboto; font-size: 32px; line-height: 36px; pad=
2023-04-17 08:33:27:903 Imap.C: ding: 2px 0 2px 0; margin: 0; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-h2 { font-family: Roboto; font-size: 24px; line-height: 28px; pad=
2023-04-17 08:33:27:903 Imap.C: ding: 2px 0 2px 0; margin: 0; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-h3 { font-family: Roboto; font-size: 18px; line-height: 22px; pad=
2023-04-17 08:33:27:903 Imap.C: ding: 2px 0 2px 0; margin: 0; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-h4 { font-family: Roboto; font-size: 14px; line-height: 20px; pad=
2023-04-17 08:33:27:903 Imap.C: ding: 2px 0 2px 0; margin: 0; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-h5 { font-family: Roboto; font-size: 12px; line-height: 16px; pad=
2023-04-17 08:33:27:903 Imap.C: ding: 2px 0 2px 0; margin: 0; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-h6 { font-family: Roboto; font-size: 10px; line-height: 13px; pad=
2023-04-17 08:33:27:903 Imap.C: ding: 2px 0 2px 0; margin: 0; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-li { font-family: Roboto; font-size: 14px; line-height: 20px; pad=
2023-04-17 08:33:27:903 Imap.C: ding: 2px 0 2px 0; margin: 0; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-light-mode { background-color: white; color: black; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-ol { line-height: 20px; padding: 0px 0 0px 48px; margin: 0; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-p { font-family: Roboto; font-size: 14px; line-height: 20px; padd=
2023-04-17 08:33:27:903 Imap.C: ing: 2px 0 2px 0; margin: 0; }
2023-04-17 08:33:27:903 Imap.C: 	.unusual-ul { line-height: 20px; padding: 0px 0 0px 48px; margin: 0; }
2023-04-17 08:33:27:903 Imap.C:     </style>
2023-04-17 08:33:27:903 Imap.C: </head>
2023-04-17 08:33:27:903 Imap.C: <body class=3D"unusual-light-mode" style=3D"">
2023-04-17 08:33:27:903 Imap.C: 	<div class=3D"unusual-div"><br></div><p id=3D"SignatureStart_DDC053ED789E4=
2023-04-17 08:33:27:903 Imap.C: 890B6303C84D0919173" style=3D"display:none"></p><div style=3D"font-family: =
2023-04-17 08:33:27:903 Imap.C: Roboto; font-size: 14px; line-height: 20px; padding: 2px 0 2px 0; margin: 0=
2023-04-17 08:33:27:903 Imap.C: ;">
2023-04-17 08:33:27:903 Imap.C:       <br>
2023-04-17 08:33:27:903 Imap.C:       <p style=3D"font-family: Roboto; font-size: 14px; line-height: 20px; =
2023-04-17 08:33:27:903 Imap.C: padding: 2px 0 2px 0; margin: 0;">Mit freundlichen Gr=C3=BC=C3=9Fen | Since=
2023-04-17 08:33:27:903 Imap.C: rely yours</p>
2023-04-17 08:33:27:903 Imap.C:       <p style=3D"font-family: Roboto; font-size: 14px; line-height: 20px; =
2023-04-17 08:33:27:903 Imap.C: padding: 2px 0 2px 0; margin: 0;"></p>
2023-04-17 08:33:27:903 Imap.C:       <p style=3D"font-family: Roboto; font-size: 14px; font-weight: bold; =
2023-04-17 08:33:27:903 Imap.C: line-height: 20px; padding: 2px 0 2px 0; margin: 0;">Dierk Droth</p>
2023-04-17 08:33:27:903 Imap.C:       <p style=3D"font-family: Roboto; font-size: 14px; font-weight: bold; =
2023-04-17 08:33:27:903 Imap.C: line-height: 20px; padding: 2px 0 2px 0; margin: 0;">Gesch=C3=A4ftsf=C3=BCh=
2023-04-17 08:33:27:903 Imap.C: rer | CEO</p>
2023-04-17 08:33:27:903 Imap.C:       <p style=3D"font-family: Roboto; font-size: 14px; line-height: 20px; =
2023-04-17 08:33:27:903 Imap.C: padding: 2px 0 2px 0; margin: 0;">Unusual Software GmbH | Heiliggrabstrasse=
2023-04-17 08:33:27:903 Imap.C:  11c, 96052 Bamberg | Amtsgericht Bamberg, HRB 10796 | Gesch=C3=A4ftsf=C3=BC=
2023-04-17 08:33:27:903 Imap.C: hrer: Dierk Droth</p>
2023-04-17 08:33:27:903 Imap.C:     </div><p id=3D"SignatureEnd_DDC053ED789E4890B6303C84D0919173" style=3D"=
2023-04-17 08:33:27:903 Imap.C: display:none"></p>
2023-04-17 08:33:27:903 Imap.C: </body></html>=
2023-04-17 08:33:27:903 Imap.C: --=-0yQJ0Uv3tEbwruG4xA+voA==--
2023-04-17 08:33:31:836 Imap.S: E00000135 NO [UNAVAILABLE] Unexpected exception (took 3548 ms)
2023-04-17 08:33:31:839 (local) Mail.MailClient.AppendToSentFolder.ImapSemaphoreRelease: mailAccount='dierk.droth@icloud.com' currentCount=1 managedThreadId=22
2023-04-17 08:33:31:847 (local) Mail.MailClient.AppendToSentFolder.Exception.GivingUp: mailAccount='dierk.droth@icloud.com' MailKit.Net.Imap.ImapCommandException: The IMAP server replied to the 'APPEND' command with a 'NO' response: Unexpected exception (took 3548 ms)
   at MailKit.Net.Imap.ImapFolder.AppendAsync(FormatOptions options, IAppendRequest request, Boolean doAsync, CancellationToken cancellationToken)
   at Unusual.Mail.MailClient.AppendToSentFolder(Mail mail)
!!!

```

**Comment by jstedfast** [comment]
Looks like the iCloud IMAP server got an unexpected exception and so rejected the APPEND.

Beyond that, I'm not sure why the iOS email app would be reading the same message over and over (other than that whatever bug you hit in the iCloud IMAP server is likely to blame for that as well?)

**Comment by jstedfast** [comment]
This is totally non-obvious (and in fact, counter intuitive), but it turns out you don't have to select the "Sent Messages" folder before appending a message to it.

It shouldn't cause any problems, but I just thought I'd mention it now that I noticed it in case that helps you optimize your program a bit more.

**Comment by DierkDroth** [comment]
Thanks @jstedfast. I'll actually running some tests right now and wanted to get back to in the next couple of days...

Here is my pseudo code on 'append to SENT folder':
```
if (!sentFolder.IsOpen)
    await sentFolder.OpenAsync(FolderAccess.ReadWrite, cts.Token);

IList<UniqueId> existing = await sentFolder.SearchAsync(MailKit.Search.SearchQuery.HeaderContains("Message-Id", mimeMessage.MessageId));
if (existing.Count > 0)
    return existing[0].Id.ToString();

UniqueId? tmp = await sentFolder.AppendAsync(mimeMessage, MessageFlags.None, cts.Token);
```
Should I close the `sendFolder `again before calling `.AppendAsync`?

**Comment by jstedfast** [comment]
No, I would just get rid of this:

```csharp
if (!sentFolder.IsOpen)
    await sentFolder.OpenAsync(FolderAccess.ReadWrite, cts.Token);
```

**Comment by jstedfast** [comment]
No, I didn't notice that you were searching the sentFolder - that requires that the folder be opened, so what you have is fine.

**Comment by DierkDroth** [comment]
Thanks @jstedfast. So I'll leave my code as is for now...
