### ISSUE TITLE
Issue while connecting to zimbra mail server POP3/IMAP

### ISSUE THREAD

**Issue by HemantMann** [jstedfast/MailKit#1580]
**Describe the bug**

IMAP or POP3Cient are not working when we connecting with https://www.zimbra.com/ mail server.
I had installed zimbra mail server on my machine and trying to read mail using mailkit.

But it's not connecting, tried with both IMAP and Pop3 protool.
But getting error as below 

**Platform (please complete the following information):**
 - OS: windows
 - .NET Runtime: 4.7.2.
 - .NET Framework: .NET 4.7.2
 - MailKit Version: 4.0.0

**Exception**
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The host name did not match the name given in the server's SSL certificate.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at MailKit.Net.Pop3.Pop3Client.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Pop3\Pop3Client.cs:line 1193
   --- End of inner exception stack trace ---
   at MailKit.Net.Pop3.Pop3Client.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Pop3\Pop3Client.cs:line 1212
   at SendMail.Program.ReadMailsPOP3() in C:\SendMailConsole\SendMail\SendMail\Program.cs:line 497

**To Reproduce**
1. install zimbra server 
2. try to read mail via mailkit

**Expected behavior**

**Code Snippets**
mailServer = "192.168.0.185";
                pop3Port = 110;
                useSSL = false;

                if (!useSSL)
                {
                    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                }

                using (var client = new Pop3Client(new ProtocolLogger("pop3.log")))
                {
                    if (useSSL)
                    {
                        client.Connect(mailServer, pop3Port, useSSL);
                        client.Authenticate(userID, pwd);
                    }
                    else
                    {
                        client.Connect(mailServer, pop3Port);
                    }

                    Console.WriteLine("Total messages: {0}", client.Count);

                    client.Disconnect(true);
                }
```csharp
// Add your code snippet here.
```

**Protocol Logs**
Connected to pop://192.168.0.185:110/?starttls=when-available
S: +OK POP3 ready
C: CAPA
S: +OK Capability list follows
S: EXPIRE 31 USER
S: TOP
S: UIDL
S: XOIP
S: SASL PLAIN
S: STLS
S: .
C: STLS
S: +OK

```

Note: if the protocol log contains sensitive information, feel free to email it to me at
jestedfa@microsoft.com instead of including it in the GitHub issue.

**Additional context**
Add any other context about the problem here.

**Comment by jstedfast** [comment]
The Connect() method that takes a true/false useSsl argument only disables 1 of the 2 SSL types. It will still use STARTTLS if the server supports it and that's where you are having a problem because your SSL certificate's host name does not match your server host name.

You have 2 options:

1. Use Connect(hostName, port, SecureSocketOptions.None);
2. Write a custom ServerCertificateValidationCallback (See the FAQ.md file in the repo to see how to do this).

**Comment by HemantMann** [comment]
tried with 1 option, but not got stuck at Authenticate.

client.Connect(mailServer, pop3Port, MailKit.Security.SecureSocketOptions.None);
                        NetworkCredential myCred = new NetworkCredential(userID, pwd);
                        //client.Authenticate(myCred);
                        var sasl = SaslMechanism.Create("PLAIN", myCred);
                        client.Authenticate(sasl);
                        //client.Authenticate(userID, pwd);
                        
 its failing at client.Authenticate, below is POP3 log
 
 Connected to pop://192.168.0.185:110/
S: +OK POP3 ready
C: CAPA
S: +OK Capability list follows
S: EXPIRE 31 USER
S: TOP
S: UIDL
S: XOIP
S: SASL PLAIN
S: STLS
S: .
C: AUTH PLAIN
S: -ERR invalid command

**Comment by jstedfast** [comment]
Try disabling PLAIN authentication. Clearly your server is broken because it says it is supported but then gives an error.

client.AuthenticationMechanisms.Remove("PLAIN");

**Comment by HemantMann** [comment]
Hi Jeff,
client.AuthenticationMechanisms.Remove("PLAIN");
this not worked, instead tried as with option 2 

client.ServerCertificateValidationCallback = (s, c, h, e) => true;
client.Connect(mailServer, pop3Port, SecureSocketOptions.Auto);
client.Authenticate(userID, pwd);

and it worked on same mail server.
But same setting failing when trying to another server

Tried with different option, but no success.
Is their any command through which we can identify mail server POP3, SMTP settings like port, SSL etc?
Do we have any fallback process in mailkit i.e. it try to connect with all possible option itself ?

below is POP3 log, its reaching till userID and failing on pwd, please advise what can be reason?
Is pwd sent with correct base64 encoding, how to check, what other way to try ?

Connected to pop://192.168.0.30:110/
S: +OK mail.ispw.polnet Zimbra POP3 server ready
C: CAPA
S: +OK Capability list follows
S: TOP
S: USER
S: UIDL
S: STLS
S: SASL PLAIN X-ZIMBRA
S: EXPIRE 31 USER
S: XOIP
S: IMPLEMENTATION ZimbraInc
S: .
C: AUTH PLAIN
S: + 
C: ********
S: -ERR authentication failed: LOGIN failed
C: USER ********
S: +OK hello centraldistt@dl.polnet, please enter your password
C: PASS ********
S: -ERR LOGIN failed

**Comment by jstedfast** [comment]
You apparentlyt need to disable PLAIN authentication with this server as well:

```csharp
client.ServerCertificateValidationCallback = (s, c, h, e) => true;
client.Connect(mailServer, pop3Port, SecureSocketOptions.Auto);
client.AuthenticationMechanisms.Remove("PLAIN");
client.Authenticate(userID, pwd);
```

> Is their any command through which we can identify mail server POP3, SMTP settings like port, SSL etc?

No. You have to get that info from the ISP / mail server administrators/website/etc.

> Is pwd sent with correct base64 encoding, how to check, what other way to try ?

Yes, I guarantee that it is correctly base64 encoded but perhaps the failure is because the server expects ISO-8859-1 character encoding instead of UTF-8 (the default).

To specify a charset encoding, you can try using:

```csharp
client.Authenticate(Encoding.GetEncoding("iso-8859-1"), userID, pwd);
```

But this is only a guess and it could be iso-8859-15 or any other charset name (which is why it is up to you to figure out because MailKit cannot possibly figure this out on its own).
