### ISSUE TITLE
ImapProtocolException: Syntax error in response code. Unexpected atom token: Flags

### ISSUE THREAD

**Issue by sunfiery** [jstedfast/MailKit#1589]
**Describe the bug**
I'm trying to sync messages from server to my local application. The server is unusual: http://bea-to-email.de/
client.Connect & client.Authenticate passing without any problems.

Then I can successfully get a root folder:
 ` var personal = _client.ImapClient.GetFolder(_client.ImapClient.PersonalNamespaces[0]);`
and it subfolders:
`IList<IMailFolder> subFolders = personal.GetSubfolders(StatusItems.UidValidity | StatusItems.Count | StatusItems.Unread);`

the problem happens when I try to open INBOX folder:
` var access = await folder.OpenAsync(FolderAccess.ReadOnly, cancellationToken);`

I am getting below exception
 
**Exception**
Message: `Syntax error in response code. Unexpected atom token: Flags`
Stack:
```
  at MailKit.Net.Imap.ImapEngine.AssertToken(ImapToken token, ImapTokenType type, String format, Object[] args)
   at MailKit.Net.Imap.ImapEngine.<ParseResponseCodeAsync>d__186.MoveNext()
   at MailKit.Net.Imap.ImapEngine.<ProcessUntaggedResponseAsync>d__189.MoveNext()
   at MailKit.Net.Imap.ImapCommand.<StepAsync>d__84.MoveNext()
   at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__190.MoveNext()
   at MailKit.Net.Imap.ImapEngine.<RunAsync>d__191.MoveNext()
   at MailKit.Net.Imap.ImapFolder.<OpenAsync>d__26.MoveNext()
   at Domain.Services.ImapSyncService.<SyncFolder>d__14.MoveNext() in D:\Projects\source\Domain.Core\Services\ImapSyncService.cs:line 192
   at Domain.Services.ImapSyncService.<SyncFolder>d__13.MoveNext() in D:\Projects\source\Domain.Core\Services\ImapSyncService.cs:line 133
```

**Protocol Logs**
```
S: * OK IMAP4rev1 Server beAte v1.8.6-026 ready
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 LITERAL+ UIDPLUS SORT ID QUOTA
S: A00000000 OK CAPABILITY completed.
C: A00000001 LOGIN ******** ********
S: A00000001 OK LOGIN completed.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4rev1 LITERAL+ UIDPLUS SORT ID QUOTA
S: A00000002 OK CAPABILITY completed.
C: A00000003 LIST "" ""
S: * LIST (\Noselect) "." ""
S: A00000003 OK LIST completed.
C: A00000004 LIST "" "INBOX"
S: * LIST () "." INBOX
S: A00000004 OK LIST completed.
C: A00000005 LIST "" "%"
S: * LIST () "." INBOX
S: * LIST () "." Draft
S: * LIST () "." Postausgang
S: * LIST () "." Sent
S: * LIST () "." Trash
S: * LIST () "." beAte_Archiv
S: A00000005 OK LIST completed.
C: A00000006 STATUS INBOX (MESSAGES UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 814 UIDVALIDITY 23 UNSEEN 812)
S: A00000006 OK STATUS completed.
C: A00000007 STATUS Draft (MESSAGES UIDVALIDITY UNSEEN)
S: * STATUS "Draft" (MESSAGES 0 UIDVALIDITY 23 UNSEEN 0)
S: A00000007 OK STATUS completed.
C: A00000008 STATUS Postausgang (MESSAGES UIDVALIDITY UNSEEN)
S: * STATUS "Postausgang" (MESSAGES 0 UIDVALIDITY 23 UNSEEN 0)
S: A00000008 OK STATUS completed.
C: A00000009 STATUS Sent (MESSAGES UIDVALIDITY UNSEEN)
S: * STATUS "Sent" (MESSAGES 877 UIDVALIDITY 23 UNSEEN 868)
S: A00000009 OK STATUS completed.
C: A00000010 STATUS Trash (MESSAGES UIDVALIDITY UNSEEN)
S: * STATUS "Trash" (MESSAGES 912 UIDVALIDITY 23 UNSEEN 912)
S: A00000010 OK STATUS completed.
C: A00000011 STATUS beAte_Archiv (MESSAGES UIDVALIDITY UNSEEN)
S: * STATUS "beAte_Archiv" (MESSAGES 601 UIDVALIDITY 23 UNSEEN 595)
S: A00000011 OK STATUS completed.
C: A00000012 EXAMINE INBOX
S: * FLAGS (\Seen 4_eeb-ab 3_beate 1_eeb-abgeben)
S: * OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen \*)  Flags permitted.]
S: * 814 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 23]
S: * OK [UIDNEXT 3790]
S: A00000012 OK [READ-ONLY] EXAMINE completed.
```

**Platform (please complete the following information):**
 - OS: Windows 10
 - .NET Runtime: CoreCLR
 - .NET Framework: .Net 6.0
 - MailKit version: 4.0.0 (checked 3.6.0, the problem is also present)

Is there any way to fix this?

**Comment by jstedfast** [comment]
Um, yea, the server is broken.

```
S: * OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen \*)  Flags permitted.]
```

The `Flags permitted.` string is supposed to go *after* the `]`, not before it.

Everything within the `[]` is supposed to follow a strict syntax that is machine parseable.

**Comment by TMBBerlin** [comment]
Right. RFC3501 says it does belong after the bracket. Fixed in Server.
