### ISSUE TITLE
Duplicate message when server disconnects "An existing connection was forcibly closed by the remote host."

### ISSUE THREAD

**Issue by xavier-rigau** [jstedfast/MailKit#159]
Error:DownloadViaImap: An existing connection was forcibly closed by the remote host.

An existing connection was forcibly closed by the remote host.

A first chance exception of type 'System.IO.IOException' occurred in System.Runtime.WindowsRuntime.NI.DLL
A first chance exception of type 'System.IO.IOException' occurred in MailKit.DLL
A first chance exception of type 'System.IO.IOException' occurred in MailKit.DLL
A first chance exception of type 'System.IO.IOException' occurred in mscorlib.ni.dll
A first chance exception of type 'System.IO.IOException' occurred in mscorlib.ni.dll
Error:DownloadViaImap: <b>An existing connection was forcibly closed by the remote host.</b>

<b>An existing connection was forcibly closed by the remote host.</b>

**Comment by jstedfast** [comment]
Do you have a test case?

**Comment by xavier-rigau** [comment]
Hi Jeff,

Here are the logs with the MailKit calls in between and a screen shot of what we show to the user. Does that help?

_imapClient.ConnectAsync()

2015-03-10 07:52:08 Information:EmailLogger created:EmailLogger-Line:12:.ctor
2015-03-10 07:52:12 Information:imaps://imap.mail.yahoo.com:993:EmailLogger-Line:23:LogConnect
2015-03-10 07:52:12 Information:S: * OK [CAPABILITY IMAP4rev1 ID NAMESPACE X-ID-ACLID UIDPLUS LITERAL+ CHILDREN XAPPLEPUSHSERVICE XYMHIGHESTMODSEQ AUTH=PLAIN AUTH=:EmailLogger-Line:58:LogLine
2015-03-10 07:52:12 Information:C: A00000000 AUTHENTICATE PLAIN:EmailLogger-Line:63:LogLine
2015-03-10 07:52:12 Information:S: + :EmailLogger-Line:63:LogLine
2015-03-10 07:52:12 Information:C: AGNoZW5qaW5nZ3NsQHlhaG9vLmNvbQBRYXp3c3gxMjM0:EmailLogger-Line:63:LogLine
2015-03-10 07:52:13 Information:S: A00000000 OK AUTHENTICATE completed - Mailbox size in bytes is 57829017:EmailLogger-Line:63:LogLine
2015-03-10 07:52:13 Information:C: A00000001 CAPABILITY:EmailLogger-Line:63:LogLine
2015-03-10 07:52:13 Information:S: * CAPABILITY IMAP4rev1 ID NAMESPACE X-ID-ACLID UIDPLUS LITERAL+ XAPPLEPUSHSERVICE XYMHIGHESTMODSEQA00000001 OK CAPABILITY comple:EmailLogger-Line:58:LogLine
2015-03-10 07:52:13 Information:C: A00000002 NAMESPACE:EmailLogger-Line:63:LogLine
2015-03-10 07:52:14 Information:S: * NAMESPACE (("" "/")) NIL NILA00000002 OK NAMESPACE completed:EmailLogger-Line:63:LogLine
2015-03-10 07:52:14 Information:C: A00000003 LIST "" "INBOX":EmailLogger-Line:63:LogLine
2015-03-10 07:52:14 Information:S: * LIST (\HasNoChildren) "/" "Inbox"A00000003 OK LIST completed:EmailLogger-Line:63:LogLine
2015-03-10 07:52:14 Information:C: A00000004 EXAMINE Inbox:EmailLogger-Line:63:LogLine
2015-03-10 07:52:14 Information:S: * 27 EXISTS* 0 RECENT* OK [UIDVALIDITY 1408429550] UIDs valid* OK [UIDNEXT 421] Predicted next UID* FLAGS (\Answered \Deleted \D:EmailLogger-Line:58:LogLine
2015-03-10 07:52:15 Information:Downloaded 0 so far.:EmailViewModel-Line:641:FetchMessagesAsync

inbox.FetchAsync()

2015-03-10 07:52:15 Information:27 msgs in Inbox, 10 num Messages to download:EmailViewModel-Line:642:FetchMessagesAsync
2015-03-10 07:52:15 Information:C: A00000005 FETCH 18:27 ALL:EmailLogger-Line:63:LogLine
2015-03-10 07:52:15 Information:S: * 18 FETCH (:EmailLogger-Line:63:LogLine
2015-03-10 07:52:16 Information:S: FLAGS (\Seen $NotJunk) INTERNALDATE "13-Jan-2015 02:22:00 +0000" RFC822.SIZE 332018 ENVELOPE ("Tue, 13 Jan 2015 10:17:20 +0800" :EmailLogger-Line:58:LogLine
2015-03-10 07:52:16 Information:S: il.microsoft.com")) ((NIL NIL "chenjinggsl" "yahoo.com")) NIL NIL NIL "<f1f9b67e-c420-43db-b8a3-22284593360b@xtinmta4192.xt.loca:EmailLogger-Line:58:LogLine
2015-03-10 07:52:16 Information:S:  Devices News" NIL "reply-fe9417737665037c7c-889095_HTML-882447769-10822948-214" "e-mail.microsoft.com")) ((NIL NIL "chenjinggsl:EmailLogger-Line:58:LogLine
2015-03-10 07:52:16 Information:26 Summary : Go for a ride with the Lumia 830 From :Microsoft Devices News Date: 3/7/2015 12:54:32 PM:EmailViewModel-Line:661:FetchMessagesAsync
2015-03-10 07:52:16 Information:25 Summary : Emailing: 迪恩-史密斯去世科比悼念：篮球史上最伟大导师_网易荐新闻.htm From :wujian Date: 3/5/2015 9:37:13 PM:EmailViewModel-Line:661:FetchMessagesAsync
2015-03-10 07:52:16 Information:24 Summary : epe testing From :Jing Chen Date: 2/24/2015 7:04:08 PM:EmailViewModel-Line:661:FetchMessagesAsync
2015-03-10 07:52:16 Information:23 Summary : Need a sidekick? Look to your Lumia. From :Microsoft Devices News Date: 2/24/2015 9:04:20 AM:EmailViewModel-Line:661:FetchMessagesAsync
2015-03-10 07:52:16 Information:22 Summary : Failure Notice From :MAILER-DAEMON@yahoo.com Date: 1/26/2015 6:03:47 PM:EmailViewModel-Line:661:FetchMessagesAsync
2015-03-10 07:52:16 Information:21 Summary : Make your Lumia fit your style From :Microsoft Devices News Date: 1/26/2015 6:05:20 AM:EmailViewModel-Line:661:FetchMessagesAsync
2015-03-10 07:52:16 Information:20 Summary : Failure Notice From :MAILER-DAEMON@yahoo.com Date: 1/20/2015 9:12:54 PM:EmailViewModel-Line:661:FetchMessagesAsync
2015-03-10 07:52:16 Information:19 Summary : XML ATTACHEMNT From :Jing Chen Date: 1/19/2015 9:34:40 PM:EmailViewModel-Line:661:FetchMessagesAsync
2015-03-10 07:52:16 Information:18 Summary : 习大 From :Jing Chen Date: 1/13/2015 10:39:37 PM:EmailViewModel-Line:661:FetchMessagesAsync
2015-03-10 07:52:16 Information:17 Summary : same name picture From :suwei Date: 1/12/2015 6:22:00 PM:EmailViewModel-Line:661:FetchMessagesAsync


// Put a break point here and wait more than 5 minutes.

_imapClient.Inbox.GetMessageAsync(selectedMsgIndex);

2015-03-10 08:02:30 Error:Unexpected Exception:The IMAP server has unexpectedly disconnected., 0x80131500
   at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapEngine.ReadToken(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.Step()
   at MailKit.Net.Imap.ImapEngine.Iterate()
   at MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)
   at MailKit.Net.Imap.ImapFolder.GetMessage(Int32 index, CancellationToken cancellationToken)
   at MailKit.MailFolder.<>c__DisplayClassf8.<GetMessageAsync>b__f7()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ePEMobile.ViewModel.EmailViewModel.<ExecuteProcessEmailMessageAsync>d__35.MoveNext():App.xaml-Line:107:UnexpectedExceptionAsync
2015-03-10 08:02:30 Error:ExecuteProcessEmailMessage: The IMAP server has unexpectedly disconnected., 80131500:EmailViewModel-Line:833:ExecuteProcessEmailMessageAsync

**Comment by jstedfast** [comment]
I guess I'm confused what the problem is?

Seems like the log shows only 1 exception being thrown but I thought the problem was that the same exception was being thrown twice?

Or maybe you are saying that the Exception.Message string has the same text duplicated?

If so, are you sure? Because that can't happen either unless there's a bug in Microsoft's System.Exception implementation.

**Comment by xavier-rigau** [comment]
Exception.Message string has the same text duplicated? Yes. That is exactly what I am saying. I debugged this myself and the string was duplicated.

**Comment by jstedfast** [comment]
so if you look at ex.Message in a debugger, it shows `"The IMAP server has unexpectedly disconnected. The IMAP server has unexpectedly disconnected."`?

**Comment by xavier-rigau** [comment]
Yep. With new lines in between.

**Comment by jstedfast** [comment]
If I look at ex.Message in a debugger, I see `"The IMAP server has unexpectedly disconnected."`. There is no duplication.

I also do not get any duplication if I do `Console.WriteLine ("Message = {0}", ex.Message)`.

I have no idea where any duplication of this string is coming from.

In your logs, it does not look like the exception message is duplicated to me because there is a stack trace between the 2 strings, leading me to suspect that it is actually a bug in your logging code (if the text was duplicated in the Message string property of the Exception, then there would not be a stack trace in the middle).

Perhaps you are doing something like this:

```csharp
Log.WriteLine (ex);
Log.WriteLine (ex.Message);
```

That's the only way I can think of that would produce the output you've pasted.
