### ISSUE TITLE
System.ArgumentNullException throwed on NTLM authentication

### ISSUE THREAD

**Issue by experdot** [jstedfast/MailKit#1683]
**Describe the bug**
Send mail failed if the SMTP server is using NTLM.

**Platform**
 - OS: Windows
 - .NET 6
 - MailKit Version: 4.3.0

**Exception**
```json
{
  "ClassName": "System.ArgumentNullException",
  "Message": "Value cannot be null.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at MailKit.Security.Ntlm.NtlmMessageBase.ValidateArguments(Byte[] message, Int32 startIndex, Int32 length)
   at MailKit.Security.Ntlm.NtlmChallengeMessage.Decode(Byte[] message, Int32 startIndex, Int32 length)
   at MailKit.Security.Ntlm.NtlmChallengeMessage..ctor(Byte[] message, Int32 startIndex, Int32 length)
   at MailKit.Security.SaslMechanismNtlm.GetChallengeResponse(String domain, String userName, String password, Byte[] token, Int32 startIndex, Int32 length)
   at MailKit.Security.SaslMechanismNtlm.Challenge(Byte[] token, Int32 startIndex, Int32 length, CancellationToken cancellationToken)
   at MailKit.Security.SaslMechanism.ChallengeAsync(Byte[] token, Int32 startIndex, Int32 length, CancellationToken cancellationToken)
   at MailKit.Security.SaslMechanism.ChallengeAsync(String token, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at CommonUtilities.SendMail.SendAsync(FgcMailMessage mailMessage, EmailSetting emailSettings)
   at CommonUtilities.SendMail.SendAsync(FgcMailMessage mailMessage, EmailSetting emailSettings)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2147467261,
  "Source": "MailKit",
  "WatsonBuckets": null,
  "ParamName": "message"
}
```
The reason for this exception is that the first parameter passed to the SaslMechanismNtlm.ChallengeAsync() method is null. 
Please check it in [AsyncSmtpClient.cs#L312](https://github.com/jstedfast/MailKit/blob/20334dde333e9d32070d75a535411fa8817d18a9/MailKit/Net/Smtp/AsyncSmtpClient.cs#L312)

```
				// send an initial challenge if the mechanism supports it
				if (sasl.SupportsInitialResponse) {
					challenge = await sasl.ChallengeAsync (null, cancellationToken).ConfigureAwait (false);
					command = string.Format ("AUTH {0} {1}\r\n", authmech, challenge);
				} else {
					command = string.Format ("AUTH {0}\r\n", authmech);
				}
```

**Comment by jstedfast** [comment]
That's not the problem.

**Comment by jstedfast** [comment]
If you are reusing the SaslMechanismNtlm instance, make sure to call the `Reset()` method before using it. Otherwise its internal state expects different inputs and that is what is causing this ArgumentNullException.
