### ISSUE TITLE
[Yandex] GetBodyPart() throws `Syntax error in BODY. Unexpected token: ')'` for MimeParts with empty content

### ISSUE THREAD

**Issue by sq5** [jstedfast/MailKit#1708]
### Discussed in https://github.com/jstedfast/MailKit/discussions/1707

<div type='discussions-op-text'>

<sup>Originally posted by **sq5** February 12, 2024</sup>
Mailkit Version 4.3.0, mail server - Yandex

Error:

Exception has occurred: CLR/MailKit.Net.Imap.ImapProtocolException
Exception thrown: 'MailKit.Net.Imap.ImapProtocolException' in System.Private.CoreLib.dll: 'Syntax error in BODY. Unexpected token: ')''
   at MailKit.Net.Imap.ImapFolder.<FetchStreamAsync>d__213.MoveNext()
   at MailKit.Net.Imap.ImapEngine.<ProcessUntaggedResponseAsync>d__189.MoveNext()
   at MailKit.Net.Imap.ImapCommand.<StepAsync>d__84.MoveNext()
   at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__190.MoveNext()
   at MailKit.Net.Imap.ImapEngine.<RunAsync>d__191.MoveNext()
   at MailKit.Net.Imap.ImapFolder.<GetBodyPartAsync>d__237.MoveNext()
   at MailKit.Net.Imap.ImapFolder.GetBodyPart(UniqueId uid, String partSpecifier, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Imap.ImapFolder.GetBodyPart(UniqueId uid, BodyPart part, CancellationToken cancellationToken, ITransferProgress progress)
</div>

**Comment by jstedfast** [comment]
These types if exceptions are typically due to a syntax error in the server response.

What I need from you is a protocol log. Specifically, the last response from the server when you get this exception.

You can get a protocol log by passing in a `new ProtocolLogger ("imap.log")` to the ImapClient constructor like this:

```csharp
var client = new ImapClient (new ProtocolLogger ("imap.log"));
```

**Comment by sq5** [comment]
Please, find it in attachment 
[imap.log](https://github.com/jstedfast/MailKit/files/14256582/imap.log)
