### ISSUE TITLE
Unexpected response from server: +OK

### ISSUE THREAD

**Issue by mrjozo** [jstedfast/MailKit#171]
Hi,

just using Pop3Client Connect and Authenticate to server and get Exception "Unexpected response from server: +OK\r\n":
```
   at MailKit.Net.Pop3.Pop3Client.<>c__DisplayClass79.<Authenticate>b__76(Pop3Engine pop3, Pop3Command cmd, String text)
   at MailKit.Net.Pop3.Pop3Engine.ReadResponse(Pop3Command pc)
   at MailKit.Net.Pop3.Pop3Engine.Iterate()
   at MailKit.Net.Pop3.Pop3Client.Authenticate(ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
```

Log:
```
Connected to pop://poczta.o2.pl:110/?starttls=when-available
S: +OK POP3 ready
C: CAPA
S: +OK Capability list follows
S: LAST
S: TOP
S: USER
S: PIPELINING
S: UIDL
S: SASL LOGIN PLAIN
S: STLS
S: .
C: STLS
S: +OK
C: CAPA
S: +OK Capability list follows
S: LAST
S: TOP
S: USER
S: PIPELINING
S: UIDL
S: SASL LOGIN PLAIN
S: .
C: AUTH PLAIN
S: + 
C: AGdhY2VrLndlbG9uZQB6eGN6eGMxMg==
S: +OK

```

**Comment by jstedfast** [comment]
Thanks! Should be fixed in latest source code.
