### ISSUE TITLE
MailKit crashes from headers in Korean

### ISSUE THREAD

**Issue by SviatoslavRazmyslov** [jstedfast/MailKit#1796]
**Describe the bug**

I received an email from Korean student and saw a MailKit exception in my service.

**Platform:**
 - OS: Linux
 - .NET Runtime: .NET 8
 - MailKit Version:  last release

**Exception**

```
System.FormatException: Failed to parse headers.
   at MimeKit.MimeParser.ParseHeaders(Byte* inbuf, CancellationToken cancellationToken)
   at MimeKit.MimeParser.ParseHeaders(CancellationToken cancellationToken)
   at MimeKit.HeaderList.Load(ParserOptions options, Stream stream, CancellationToken cancellationToken)
   at MimeKit.HeaderList.Load(Stream stream, CancellationToken cancellationToken)
   at MimeKit.MessageDispositionNotification.get_Fields()
```

**To Reproduce**

I guess the reason is this:

```
From: "=?UTF-8?B?7ZmN7KeE6re8?=" <jkhong@bu.ac.kr>
```

or that:

```
Reporting-UA: mail.bu.ac.kr; 백석대학교
```

**Expected behavior**

A mail is loaded without exceptions.

**Comment by jstedfast** [comment]
It's neither of those.

**Comment by jstedfast** [comment]
Moving this to MimeKit since, if it is a bug, then it's a bug in my MimeKit library and not MailKit.
