### ISSUE TITLE
ImapClient.Authenticate Failed

### ISSUE THREAD

**Issue by ctechid** [jstedfast/MailKit#1808]
I want to read **verification code** from **gmail.com** but get error when calling process **client.Authenticate(email, password);**

 - OS: Windows 11
 - .NET Runtime: 8.0.304
 - .NET Framework: .NET 8.0
 - MailKit: 4.7.1.1 

```
**Exception**
   at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(Encoding encoding, String userName, String password, CancellationToken cancellationToken)
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at CustomerCardServer.Ext.Mod.Email.GmailManager.ReadVerificationCode(String email, String password) in F:\2022\CustomerCard\CustomerCard\Server\PresentationLayer\Ext\Mod\Email\GmailManager.cs:line 50

```
**Code Snippets**
```
using CardData.Ext.Logger;
using MailKit;
using MailKit.Net.Imap;
using MailKit.Search;
using System.Text.RegularExpressions;

namespace CustomerCardServer.Ext.Mod.Email
{
    public class GmailManager
    {
        private static GmailManager? _instance;
        private static object _instanceLocker = new object();

        private String _imapServer = "imap.gmail.com";
        private int _imapPort = 993; // imap over SSL

        private GmailManager()
        {
        }

        public static GmailManager GetInstance()
        {
            if (_instance is null)
            {
                lock (_instanceLocker)
                {
                    _instance = new GmailManager();
                }
            }
            return _instance;
        }

        public String ReadVerificationCode(String email, String password)
        {
            try
            {
                if (String.IsNullOrEmpty(email) || String.IsNullOrEmpty(password))
                {
                    return String.Empty;
                }

                using (var client = new ImapClient())
                {
                    // Connect to the server
                    client.Connect(_imapServer, _imapPort, true);

                    // Authenticate
                    //client.AuthenticationMechanisms.Remove("XOAUTH2");
                    //client.AuthenticationMechanisms.Remove("NTLM");
                    client.Authenticate(email, password);  // BUG IN HERE

                    // Open the inbox
                    var inbox = client.Inbox;
                    inbox.Open(FolderAccess.ReadOnly);

                    // Search for emails from the specific sender
                    var query = SearchQuery.FromContains("noreply@github.com");
                    var uids = inbox.Search(query);

                    // Fetch the details of the found messages
                    var messages = inbox.Fetch(uids, MessageSummaryItems.Full | MessageSummaryItems.UniqueId | MessageSummaryItems.InternalDate);

                    // Define the current time
                    DateTime currentDate = DateTime.UtcNow;

                    // Filter messages that contain "Device verification" in the subject
                    var filteredMessages = messages
                    .Where(msg => msg.NormalizedSubject != null && msg.NormalizedSubject.Contains("[GitHub] Please verify your device", StringComparison.OrdinalIgnoreCase))
                    .OrderByDescending(msg => Math.Abs((msg.Date.DateTime - currentDate).TotalSeconds))
                    .ToList();

                    if (filteredMessages.Any())
                    {
                        var nearestMessage = filteredMessages.First();
                        var message = inbox.GetMessage(nearestMessage.UniqueId);

                        // Define the regex pattern to match the verification code
                        string pattern = @"Verification code:\s*(\d+)";

                        // Create a Regex object with the specified pattern
                        Regex regex = new Regex(pattern);

                        // Perform the regex match
                        Match match = regex.Match(message.Body.ToString());
                        if (match.Success)
                        {
                            // Extract the verification code from the match groups
                            return match.Groups[1].Value;
                        }
                    }

                    // Disconnect and dispose
                    client.Disconnect(true);
                }
            }
            catch (Exception ex)
            {
                Log.Exception(ex);
            }
            return String.Empty;
        }
    }
}

```

**Comment by jstedfast** [comment]
Are you using your normal password  or an app-specific password?

Have you configured gmail to allow "Less secure apps"?

**Comment by ctechid** [comment]
> Are you using your normal password or an app-specific password?
> 
> Have you configured gmail to allow "Less secure apps"?

I use normal password.
I set gmail to allow "Less secure apps".

**Comment by jstedfast** [comment]
You have to use an app-specific password. Google won't allow you to use your normal password with GMail over IMAP or SMTP anymore.
