### ISSUE TITLE
Make Mailkit AOT/Net9 compatible

### ISSUE THREAD

**Issue by PaulTaro** [jstedfast/MailKit#1844]
I am using Mailkit in my app for Windows, Android, and iOS. For iOS I must target SDK V17 now. This is supported by Microsoft.iOS only, not more by Xamarin. To produce a release with VS2022, all assemblies should be AOT compatible. Currently I can't release my app for iOS because  MailKit is not AOT compatible.

**Comment by jstedfast** [comment]
D'oh, I was just hanging out with the Microsoft.iOS and Android team leads for the past 3 days. Wish I had gotten this request a day or two ago.

Oh well. It's probably as simple as adding net-9.0 to the tfm's?

**Comment by PaulTaro** [comment]
Look at this: https://devblogs.microsoft.com/dotnet/creating-aot-compatible-libraries/

**Comment by jstedfast** [comment]
I'm moving this to MimeKit because MimeKit is where all of the AOT compatibility issues are.

I'm not seeing any AOT warnings in MailKit itself.

**Comment by jstedfast** [comment]
actually, meh, I'm going to leave this here because some MimeKit commits already link to this.

**Comment by rosen-vladimirov** [comment]
Hey @jstedfast ,
I see you've added AOT compatibility test, which seems to be passing, so is AOT supported at the moment?

**Comment by jstedfast** [comment]
Only if you use the MimeKitLite and MailKitLite packages.

**Comment by PaulTaro** [comment]
I am now using MailKitLite with AOT compilation for iOS and it functions well. Unfortunally this is not true for Android The following exception occurs when SendMailAsync is called both in release mode and in debug mode even that the same code is used as for iOS:

MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The server's SSL certificate could not be validated for the following reasons:
• The server certificate has the following errors:
  • The certificate's revocation status could not be determined.
• An intermediate certificate has the following errors:
  • Unable to determine revocation status due to network error

 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__157`1[[System.Net.Security.SyncReadWriteAdapter, System.Net.Security, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at MailKit.Net.Smtp.SmtpClient.SslHandshake(SslStream ssl, String host, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Smtp\SmtpClient.cs:line 1309
   at MailKit.Net.Smtp.SmtpClient.PostConnect(Stream stream, String host, Int32 port, SecureSocketOptions options, Boolean starttls, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Smtp\SmtpClient.cs:line 1359
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.PostConnect(Stream stream, String host, Int32 port, SecureSocketOptions options, Boolean starttls, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Smtp\SmtpClient.cs:line 1376
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken) in D:\src\MailKit\MailKit\Net\Smtp\SmtpClient.cs:line 1507
   at KubiConsult.Mail.MailKit.SendMessage(MimeMessage message) in ...

**Comment by PaulTaro** [comment]
PS: When I use the same code and the same MailkitLite version with the NetStandard version of my app sending an e-mail functions well.

**Comment by jstedfast** [comment]
That exception doesn't have any thing to do with AOT issues - it looks like an SSL certificate revocation check error (due to some sort of network error). This makes sense that it's different on Android vs iOS because the underlying SSL implementation is being used for this afaik (by the System.Security SslStream class).

Try `client.CheckCertificateRevocation = false;`
