### ISSUE TITLE
Syntax error in BODYSTRUCTURE. Unexpected token: ')'

### ISSUE THREAD

**Issue by cm4ker** [jstedfast/MailKit#1861]
Hello! Thank you for your library!

**Describe the bug**

On ```IEmailFolder.FetchAsync``` throw error ```Syntax error in BODYSTRUCTURE. Unexpected token: ')'```

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: CoreCLR
 - .NET Framework: .NET Core 9.0
 - MailKit Version: 4.9.0

**Exception**
If you got an exception, please include the exception Message *and* StackTrace.

```
Syntax error in BODYSTRUCTURE. Unexpected token: ')'
   at MailKit.Net.Imap.ImapEngine.AssertToken(ImapToken token, ImapTokenType type, String format, Object[] args)
   at MailKit.Net.Imap.ImapEngine.ParseNumber(ImapToken token, Boolean nonZero, String format, Object[] args)
   at MailKit.Net.Imap.ImapUtils.ParseNumberToken(ImapToken token, String format)
   at MailKit.Net.Imap.ImapUtils.ReadNumberAsync(ImapEngine engine, String format, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseBodyAsync(ImapEngine engine, String format, String path, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.ParseSummaryItemsAsync(ImapEngine engine, MessageSummary message, FetchSummaryItemsCompletedCallback completed, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponseAsync(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.StepAsync()
   at MailKit.Net.Imap.ImapEngine.IterateAsync()
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic)
   at MailKit.Net.Imap.ImapFolder.FetchAsync(IList`1 indexes, IFetchRequest request, CancellationToken cancellationToken)
```

**Additional context**
I tryied MessageSummaryItems.BodyStructure and MessageSummaryItems.Body
```
  var fetch = await client.Inbox.FetchAsync([510],
                MessageSummaryItems.Full | MessageSummaryItems.BodyStructure);
```

[imap.log](https://github.com/user-attachments/files/18262940/imap.log)

**Comment by jstedfast** [comment]
Exact same issue as QQMail in issue #1076.

**Comment by cm4ker** [comment]
@jstedfast I faced this error when trying to sync a mail folder. Maybe there is a workaround so I can skip failed emails and continue parsing the response from the IMAP server?

**Comment by jstedfast** [comment]
Looks like the imap.yandex.ru BODYSTRUCTURE response is invalid:

```
BODYSTRUCTURE ( "mixed" ("boundary" "----=_NextPart_000_0031_01C47829.F770E34D") NIL NIL NIL)
```

There should be a list of children before `"mixed"` but there isn't.

**Comment by jstedfast** [comment]
Above commit should fix the issue. Also fixed for QQMail.

**Comment by cm4ker** [comment]
@jstedfast Checked. The issue has gone. Thank you!
