### ISSUE TITLE
The buffers supplied to a function was too 

### ISSUE THREAD

**Issue by MattAfflek** [jstedfast/MailKit#197]
From time to time I receive this error message.
```
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The buffers supplied to a function was too small
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.<>c__DisplayClass3.<ConnectAsync>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at DownloadAndUpdatePrices.Email.EmailService.<DownloadFileAsync>d__0.MoveNext() in d:\ProjectIS-3\WebProjectAutosouz\DownloadAndUpdatePrices\DownloadAndUpdatePrices\Email\EmailService.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DownloadAndUpdatePrices.BLL.DownloadService.<DownloadFileAsync>d__0.MoveNext() in d:\ProjectIS-3\WebProjectAutosouz\DownloadAndUpdatePrices\DownloadAndUpdatePrices\BLL\DownloadService.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DownloadAndUpdatePrices.Program.<Process>d__d.MoveNext() in d:\ProjectIS-3\WebProjectAutosouz\DownloadAndUpdatePrices\DownloadAndUpdatePrices\Program.cs:line 48
```

**Comment by jstedfast** [comment]
Since MailKit.Net.Imap.ImapClient.Connect() does not supply any buffers to System.Net.Security.SslStream.AuthenticateAsClient(), this seems like it is probably a bug in the .NET class libraries.

**Comment by migig** [comment]
@MattAfflek I'm getting this error as well. How did you solve it?

**Comment by MattAfflek** [comment]
[jstedfast](https://github.com/jstedfast):
> seems like it is probably a bug in the .NET class libraries.
I think the same.

I created new issue in the .NET category
https://github.com/dotnet/corefx/issues/1854
And similar error, you can get:
https://github.com/dotnet/corefx/issues/1894
So, we can only wait...

**Comment by migig** [comment]
@MattAfflek Thanks for update. But I hazard a guess if problem is in the BCL then we won't get a bug fix anytime soon.

Besides, I can't repro the problem. Can you? I get this as you put it, "from time to time". It's weird.

**Comment by MattAfflek** [comment]
@migig I can't see any regularity.
My service has loop, which use ImapClient.ConnectAsync(string host, int port, bool useSsl, CancellationToken cancellationToken = null).
This params no changing.
But I recieve sometimes error.

I think can create something like this:

``` c#
var i = 0;
var success = false;
while (!success && i < 3)
{
  i++;
  try
  {
     ... // Connect to Email
     success = true;
   }
   catch { }
}
```

**Comment by MattAfflek** [comment]
@migig 
Good news everyone!
I solved this problem.
One day without error.

My method had two return statement.
I didn't used ```ImapClient.DisconnectAsync(true)``` in one of the cases.
The error has gone after modification.

You should always call this method.

Tell me if it help, I'll close issue in .NET library.

**Comment by migig** [comment]
@MattAfflek Thanks for the feedback. Doesn't seem to work for me. But then again I can't anticipate the error, I can't repro it.

**Comment by migig** [comment]
@MattAfflek Actually, you are calling `DisconnectAsync` and I'm calling `Disconnect`. What is the difference? I'm not creating/using anything async (that I know of)?

Do you know why this makes a difference?

**Comment by MattAfflek** [comment]
@migig I'm sorry, error is come back, but appear a less often.
I can't repro it too.
And I think has no difference async or not.

**Comment by jstedfast** [comment]
Are you possibly accessing the SmtpClient from multiple threads?

**Comment by MattAfflek** [comment]
@jstedfast I don't think so.
My code is very simple.
If it help, here it is:
``` c#
public static async Task<DownloadResult> DownloadFileAsync(EmailModel emailModel, bool notSetFlagSeen)
        {
            var result = new DownloadResult();
            if (emailModel != null)
            {
                using (var client = new ImapClient())
                {
                    await client.ConnectAsync(emailModel.Host, emailModel.Port, emailModel.Secure);

                    // Note: since we don't have an OAuth2 token, disable
                    // the XOAUTH2 authentication mechanism.
                    client.AuthenticationMechanisms.Remove("XOAUTH");

                    await client.AuthenticateAsync(emailModel.UserName, emailModel.Password);

                    var inbox = client.Inbox;
                    await inbox.OpenAsync(FolderAccess.ReadWrite);

                    await DeleteOldMessageAsync(inbox);

                    var orderBy = new[] { OrderBy.ReverseDate };
                    var messagesIds = await inbox.SearchAsync(SearchQuery.FromContains(emailModel.FromEmail).And(SearchQuery.NotSeen), orderBy);

                    var fileNameFilter = FileNameReg.GetPatternFilter(emailModel.FileNamePattern);

                    foreach (var uid in messagesIds)
                    {
                        Task error = null;
                        try
                        {
                            var message = await inbox.GetMessageAsync(uid);
                            if (!notSetFlagSeen)
                                inbox.SetFlags(uid, MessageFlags.Seen, true);

                            foreach (var attach in message.Attachments)
                            {
                                if (attach.IsAttachment)
                                {
                                    if (!string.IsNullOrWhiteSpace(attach.FileName))
                                    {
                                        if (fileNameFilter.IsMatch(attach.FileName))
                                        {
                                            var saveFilePath = DirectoryService.CreateDateCatalogDirectory(Config.SavePathEmail) + attach.FileName;
                                            if (FileService.IsExist(saveFilePath))
                                                saveFilePath = FileService.GetAlternativeFileName(saveFilePath);

                                            if (!string.IsNullOrEmpty(saveFilePath))
                                                using (var stream = File.Create(saveFilePath))
                                                    attach.ContentObject.DecodeTo(stream);

                                            result.FullPath = saveFilePath;

                                            if (!notSetFlagSeen)
                                            {
                                                await inbox.SetFlagsAsync(messagesIds, MessageFlags.Seen, true);
                                            }
                                            //return result;
                                        }
                                    }
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            error = ErrorHandler.HandleAsync(ex);
                        }
                        if (error != null)
                            await error;
                    }
                    await client.DisconnectAsync(true);
                }
            }
            return result;
        }
        private static async Task DeleteOldMessageAsync(IMailFolder folder)
        {
            var date = DateTime.Now.AddMonths(-2);
            var messagesIds = await folder.SearchAsync(SearchQuery.DeliveredBefore(date));
            if (messagesIds.Count > 0)
            {
                await folder.SetFlagsAsync(messagesIds, MessageFlags.Deleted, true);
                await folder.ExpungeAsync();
            }
        }
```
This method may be called few times. 
``` c#
await EmailService.DownloadFileAsync(emailModel, severalPrices);
```
All of my async methods has await statement.
So I don't know why it happens.

**Comment by jstedfast** [comment]
Yea, there shouldn't be a race condition in that code that I can see. It was just an idea - I thought maybe another thread might be doing something with the ImapClient while it was connecting or something that caused corruption in the SslStream.AuthenticateAsClient() method, but it doesn't look like it.

**Comment by migig** [comment]
@MattAfflek @jstedfast Yes me too - no async code. It's running within an ASP.NET MVC HttpContext, but since I dispose of everything properly, and call `Disconnect(true)`, I don't believe there are threading issues. I don't use the async functions in the library, only the regular ones.

**Comment by migig** [comment]
@MattAfflek I'm trying to compare my experience to yours, to isolate the problem:

- You're using the async functions, I'm using sync. But our exceptions and stacktraces are identical other than that.

- My web app is running in shared hosting, 32-bit. How about you? In other words, a memory-limited environment. Works perfectly in all other respects though.

- I think this problem only happens after a site restart - after inactivity, the app is stopped, and is restarted once the next request hits the server. I think that when the next request is me, triggering the MailKit code, then the error happens.

- The bit of code in which this error occurs, seems to be one that checks multiple mailboxes for new mail. It checks them one by one, and disconnects and disposes each in turn properly. I dont think theres a race condition, but it's worth noting. It only happens for `ImapClient`, and I think, only when I access multiple mailboxes this way. I think. I don't think I've ever received this error for any SMTP stuff.

- When the error occurs, I can retry immediately, and it works. So it only happens the first time.

**Comment by MattAfflek** [comment]
@migig 
I'm using console application.
My application downloads some files from ftp, url links and emails.
Application has next settings:
Platform target: Any CPU
Prefer 32 bit (check)
Application starts by Task Scheduler.
In the theory, application can use different logins for email's connecting .
On the practice, application use just one login for connecting.
When application is working it is connecting to the email more then eight times.
I see few errors with same time in the log file sometimes.
May be you can try cancel recycle application pool?
http://serverfault.com/questions/333907/what-should-i-do-to-make-sure-that-iis-does-not-recycle-my-application#answer-333948
I did it in all my applications.

**Comment by migig** [comment]
@MattAfflek If I understand you correctly, you get the error when you access multiple mailboxes, or make multiple connections... something like that?

**Comment by MattAfflek** [comment]
@migig There are several connections for single mailbox.

**Comment by migig** [comment]
@MattAfflek I was hoping that was the reason...

But, I just got this error again, and this time it was for one connection.

Back to square one! :sob:

**Comment by migig** [comment]
@MattAfflek Been a while, and still getting these two errors ("buffers too small", and "message signature altered") from time to time. Have you discovered the cause?

**Comment by MattAfflek** [comment]
@migig No. I still get this error and don't know how to fix it.

**Comment by migig** [comment]
@MattAfflek I see on corefx that they are investigating it.

Do you find that if you RETRY what you were doing immediately, it works the second time? *I'm not 100% sure*, but a few times what happened is once what I'm doing fails, I retry immediately, and it works.

If this is a real pattern and not just me, I will maybe wrap the bad code in try-catch, look for the exception message ("buffers too small", and "message signature altered") and then retry once. Then log if it fails again.

**Comment by MattAfflek** [comment]
@migig I didn't try.

I think this trick will be working.

**Comment by migig** [comment]
@MattAfflek The next time you run into this problem and don't know what to do, use the two-try idea above. If it works for you, let us know. I'm using it now and will monitor results.

I'll update the thread when I know more.

**Comment by migig** [comment]
@MattAfflek Good news been using this trick for a while and it seems to work. Look for the exception message in the stacktrace (important to search the entire stack trace, not just the thrown exception), and if it matches one of the two weird exceptions, then just try the operation again. It always works the second time. Why I don't know, but I don't care anymore.

For anyone else having this problem, just do as I did, and wait for MS to fix the bug in the framework!

**Comment by MattAfflek** [comment]
@migig Thanks. It's really good news.

**Comment by migig** [comment]
Seems like [this trick works for other people too](https://github.com/dotnet/corefx/issues/1854#issuecomment-160513245). And its dependable. For others stumbling onto this problem, don't waste any time on it, as it's not in this library, it's in the framework. Just do a retry and move on.
