### ISSUE TITLE
Exception after update to version 1.2.2 

### ISSUE THREAD

**Issue by pascalberger** [jstedfast/MailKit#201]
After update to version 1.2.2 I get the following exception in my code:

    System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
       at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
       at MailKit.Net.Imap.ImapFolder.FetchMessageBody(ImapEngine engine, ImapCommand ic, Int32 index)
       at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponse(CancellationToken cancellationToken)
       at MailKit.Net.Imap.ImapCommand.Step()
       at MailKit.Net.Imap.ImapEngine.Iterate()
       at MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)
       at MailKit.Net.Imap.ImapFolder.GetBodyPart(UniqueId uid, String partSpecifier, Boolean headersOnly, CancellationToken cancellationToken)
       at MailKit.Net.Imap.ImapFolder.GetBodyPart(UniqueId uid, BodyPart part, Boolean headersOnly, CancellationToken cancellationToken)
       at MailKit.Net.Imap.ImapFolder.GetBodyPart(UniqueId uid, BodyPart part, CancellationToken cancellationToken)

The exception is thrown after a call to `ImapClient.Inbox.GetBodyPart()` for an email message containing a calendar invitation reply.

**Comment by jstedfast** [comment]
Thanks! I guess I'll have to release an emergency 1.2.3 when I get back from the gym.
