### ISSUE TITLE
MailKit.Net.Imap.ImapFolder.Fetch crashes on invalid date

### ISSUE THREAD

**Issue by sbukhtiyarov** [jstedfast/MailKit#254]
Hello!

I are faced with the following problem:
MailKit.Net.Imap.ImapFolder.Fetch crashes on invalid date.

Line from protocol log
* 4034 FETCH (UID 8589 MODSEQ (5252505) ENVELOPE (**"6/31/2005"** "It's time to ....
Date is 31 Jun, but this month have 30 day only.

I think that method TryParseUnknownDateFormat must handle this exception and return false in this case

System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at MimeKit.Utils.DateUtils.TryParseUnknownDateFormat(IList`1 tokens, Byte[] text, DateTimeOffset& date)
   at MimeKit.Utils.DateUtils.TryParse(String text, DateTimeOffset& date)
   at MailKit.Net.Imap.ImapUtils.ParseEnvelopeDate(ImapEngine engine, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseEnvelope(ImapEngine engine, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.FetchSummaryItems(ImapEngine engine, ImapCommand ic, Int32 index)
   at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponse(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.Step()
   at MailKit.Net.Imap.ImapEngine.Iterate()
   at MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)
   at MailKit.Net.Imap.ImapFolder.Fetch(Int32 min, Int32 max, MessageSummaryItems items, CancellationToken cancellationToken)

Thanks you!
Slava

**Comment by jstedfast** [comment]
Thanks!
