### ISSUE TITLE
SslStream.Read exception?

### ISSUE THREAD

**Issue by vnwind** [jstedfast/MailKit#335]
Hi Jeffrey
Do you know what can cause this exception when reading the email?
at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
  at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
  at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken)
  at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken)
  at MailKit.Net.Imap.ImapStream.ReadToken(CancellationToken cancellationToken)
  at MailKit.Net.Imap.ImapCommand.Step()
  at MailKit.Net.Imap.ImapEngine.Iterate()
  at MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)
  at MailKit.Net.Imap.ImapFolder.Search(SearchQuery query, CancellationToken cancellationToken)

I am trying to replicate the problem it but unable to. 

Thanks

**Comment by jstedfast** [comment]
No clue. That error is inside of the System.Net.Security code which is outside of my knowledge.
