### ISSUE TITLE
The IMAP server has unexpectedly disconnected

### ISSUE THREAD

**Issue by basile-laderchi** [jstedfast/MailKit#349]
I am trying to read the messages from our exchange server using the IMAP protocol.
Some times I get this error.
After trying again it usually works.

This is the exception thrown:
MailKit.Net.Imap.ImapProtocolException: The IMAP server has unexpectedly disconnected.
   at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.Step()
   at MailKit.Net.Imap.ImapEngine.Iterate()
   at MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)
   at MailKit.Net.Imap.ImapEngine.QueryCapabilities(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at SI.Dms.Classes.ProcessMailDocuments.ProcessRequest(HttpContext context) in C:\projects\DMS\Source\SI.DMS.Classes\Handlers\ProcessMailDocuments.vb:line 64

This is the code I am using:
Dim client As ImapClient = Nothing
Try
  client = New ImapClient(New ProtocolLogger("imap.log"))
  ' the following line has been added because the server's ssl certificate had a problem.
  ServicePointManager.ServerCertificateValidationCallback = AddressOf CertificateValidationCallBack
  client.Timeout = 200000 ' <---- I added this line just in case it was a timeout problem
  client.Connect("xxx.xx.gr", 993, True) ' <---- This is line 64 that throws the error.
  ...
  client.Disconnect(True)
  context.Response.Write("OK")
Catch ex As Exception
  context.Response.Write("NOK")
Finally
  If (client IsNot Nothing) Then
    client.Dispose()
  End If
End Try

Private Function CertificateValidationCallBack(ByVal sender As Object, ByVal certificate As X509Certificate, ByVal chain As X509Chain, ByVal policyErrors As SslPolicyErrors) As Boolean
  Return True
End Function

This is the imap.log:
Connected to imaps://xxx.xx.gr:993/
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * BYE Connection is closed. 13

I am using MailKit v1.2.23 installed through NuGet.

**Comment by jstedfast** [comment]
This isn't a bug in MailKit, it's just that you either:

1. lost network connectivity
2. the server dropped the connection (possibly due to being under high load)

**Comment by basile-laderchi** [comment]
Thank you.
So, all I can do is trap the error and try again later on, right?

**Comment by jstedfast** [comment]
Yep, that's all you can do :-\
