### ISSUE TITLE
Syntax error in BODYSTRUCTURE. Unexpected token: [atom: -2]

### ISSUE THREAD

**Issue by Gonkers** [jstedfast/MailKit#385]
Hello,

I'm currently having an issue with a particular message that I cannot seem to resolve or work around. After reading the other issues, I figure the mail server isn't behaving according to the spec, but I figured I'd ask anyway.

Thanks

**Error**
> Syntax error in BODYSTRUCTURE. Unexpected token: [atom: -2]

**Protocol Log**
```
Connected to imap://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
S: * OK IMAP4rev1 SmarterMail
C: R00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 AUTH=CRAM-MD5 UIDPLUS XLIST
S: R00000000 OK CAPABILITY completed
C: R00000001 AUTHENTICATE CRAM-MD5
S: + XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
C: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
S: R00000001 OK CRAM authentication successful
C: R00000002 CAPABILITY
S: * CAPABILITY IMAP4rev1 AUTH=CRAM-MD5 UIDPLUS XLIST
S: R00000002 OK CAPABILITY completed
C: R00000003 LIST "" ""
S: * LIST (\Noselect) "/" ""
S: R00000003 OK LIST completed
C: R00000004 LIST "" "INBOX"
S: * LIST (\Marked) "/" "Inbox"
S: R00000004 OK LIST completed
C: R00000005 XLIST "" "*"
S: * XLIST (\Unmarked \Trash) "/" "Deleted Items"
S: * XLIST (\Marked \Inbox) "/" "Inbox"
S: * XLIST (\Unmarked \Spam) "/" "Junk E-Mail"
S: * XLIST (\Unmarked \Sent) "/" "Sent Items"
S: R00000005 OK XLIST completed
C: R00000006 EXAMINE Inbox
S: * 1029 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 1] Message 1 is first unseen
S: * OK [UIDVALIDITY 1] UIDs valid
S: * OK [UIDNEXT 1035] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * OK [PERMANENTFLAGS ()]
S: R00000006 OK [READ-ONLY] EXAMINE completed
C: R00000007 FETCH 635 (UID FLAGS INTERNALDATE RFC822.SIZE ENVELOPE BODYSTRUCTURE)
S: * 635 FETCH (UID 640 FLAGS () INTERNALDATE "5-Aug-2016 17:01:49 -0400" RFC822.SIZE 130625 ENVELOPE ("Fri, 5 Aug 2016 21:01:26 GMT" "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" ((NIL NIL "XXXXXX" "XXXXXX.com")) ((NIL NIL "XXXXXX" "XXXXXX.com")) NIL ((NIL NIL "XXXXXX" "XXXXXX.com") (NIL NIL "XXXXXX" "XXXXXX.com")) NIL NIL NIL "<201608052101.u75L1QMs012457@billing1-vl.dfwx>") BODYSTRUCTURE (("text" "plain" NIL NIL NIL "7bit" -2 0 NIL NIL NIL)("application" "octet-stream" ("name" "XXXXXX.csv" "filename" "XXXXXX.csv") NIL NIL "base64" 60604 NIL ("attachment" ("filename" "XXXXXX.csv")) NIL)("application" "octet-stream" ("name" "XXXXXX.pdf" "filename" "XXXXXX.pdf") NIL NIL "base64" 65872 NIL ("attachment" ("filename" "XXXXXX.pdf")) NIL)("application" "octet-stream" ("name" "XXXXXX.txt" "filename" "XXXXXX.txt") NIL NIL "base64" 808 NIL ("attachment" ("filename" "XXXXXX.txt")) NIL) "mixed" ("boundary" "DMW.Boundary.605592468") NIL NIL))
S: R00000007 OK FETCH completed
) NIL NIL "quoted-printable" 1117 25 NIL NIL NIL) "alternative" ("boundary" "MCBoundary=_11608051706083731") NIL NIL)("application" "pdf" ("name" "XXXXXX.pdf" "filename" "XXXXXX.pdf" "size" "73916" "creation-date" "Fri, 05 Aug 2016 20:56:39 GMT" "modification-date" "Fri, 05 Aug 2016 20:56:39 GMT") "<B1227A2B0E8FFF4EA384F3A915B75312@namprd06.prod.outlook.com>" "XXXXXX.pdf" "base64" 101148 NIL ("attachment" ("filename" "XXXXXX.pdf" "size" "73916" "creation-date" "Fri, 05 Aug 2016 20:56:39 GMT" "modification-date" "Fri, 05 Aug 2016 20:56:39 GMT")) NIL) "mixed" ("boundary" "_002_SN1PR06MB228808C2647E242E4EE357F494180SN1PR06MB2288namp_") NIL NIL))
S: N00000007 OK FETCH completed
C: N00000008 UID FETCH 641 (BODY.PEEK[1.2.MIME] BODY.PEEK[1.2])
S: * 636 FETCH (BODY[1.2.MIME] {145}
S: Content-Transfer-Encoding: quoted-printable
S: Content-Type: text/html; charset=UTF-8
S: X-WatchGuard-AntiVirus: part scanned. clean action=allow
S: 
S:  BODY[1.2] {1117}
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S: XXXXXX
S:  UID 641)
S: N00000008 OK UID completed
```

**Stack Trace**
```
   at MailKit.Net.Imap.ImapUtils.ReadNumber(ImapEngine engine, String format, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseBody(ImapEngine engine, String format, String path, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseMultipart(ImapEngine engine, String format, String path, String subtype, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapUtils.ParseBody(ImapEngine engine, String format, String path, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapFolder.FetchSummaryItems(ImapEngine engine, ImapCommand ic, Int32 index)
   at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponse(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.Step()
   at MailKit.Net.Imap.ImapEngine.Iterate()
   at MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)
   at MailKit.Net.Imap.ImapFolder.Fetch(Int32 min, Int32 max, MessageSummaryItems items, CancellationToken cancellationToken)
   at MailKit.MailFolder.<>c__DisplayClass195_0.<FetchAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EAAP.InvoiceProcessing.Mail.IMapMessageService.<GetMessagesAsync>d__5.MoveNext()
```

**Comment by jstedfast** [comment]
Well, I have to admit the `Unexpected token: [atom: -2]` error is .... unexpected :)

I thought for sure there must be a bug in the way MailKit was serializing the token to a string to use in the error message, but alas, it was not:

    ... BODYSTRUCTURE (("text" "plain" NIL NIL NIL "7bit" -2 0 NIL NIL NIL ...

The -2 value in that response represents the message size in octets (aka bytes). You can't have a message size that is less than 0 :)

Awkwardly, MailKit's structures all use a uint value to represent these properties, so I can't realistically store a -2 value in them even if I modify the parser to not error out when it runs into them.

Could you submit a bug about this to SmarterMail and see what they have to say? Hopefully they can fix the bug and get a patch out to you.

**Comment by Gonkers** [comment]
Thanks for the quick response! I saw the -2 in the response and figured that what it was causing the issue, but didn't know what it represented. I'll reach out to smarter mail. Thank you.

**Comment by jstedfast** [comment]
I should make a correction - it's not the message size, it's the size of the text/plain content. I misspoke :)

**Comment by Gonkers** [comment]
I'm leaving this here for notes in case anyone else runs into this. 

The message was copied from another mailbox using Microsoft Outlook and I think that was the root cause. Once the message was re-copied using the SmarterMail web client, it worked just fine. So it appears it was the Outlook client, or how SmarterMail deals with copied messages from a 3rd party client. Who knew?

**Comment by jstedfast** [comment]
Interesting...
