### ISSUE TITLE
Upgrade to ASP.NET Core 1.1.0 breaks MailKit.Net.Smtp.SmtpClient

### ISSUE THREAD

**Issue by bottomup** [jstedfast/MailKit#426]
Since the upgrade of the latest ASP.NET Core release (1.1.0), the SmtpClient breaks on Connect.

An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll

My guess is that it has to do with "ASP.NET Core 1.1" Kestrel webserver decided to use LibUV DllImpor [1] instead of .NET Asynchronous Server Socket (System.Net.Sockets).

Is this a known issue, and might there ba a workaround? Thanks.

Stacktrace:

Microsoft.AspNetCore.Server.Kestrel [Warning] Unable to bind to http://localhost:31390 on the IPv6 loopback interface.
System.AggregateException: One or more errors occurred. (Error -4089 EAFNOSUPPORT address family not supported) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<StartAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.<

**Comment by jstedfast** [comment]
Why do you think this has something to do with MailKit? MailKit doesn't show up in the stack trace and it appears that the error is HTTP related?

**Comment by bottomup** [comment]
Well, the application suddenly breaks on the call to Connect. This is not te case using ASP.NET Core 1.0.1. 
When debugging there is not a stacktrace. And when runing local, nothing useful is logged. When running on Azure, the logfile contains some trace, as posted.

Hope this helps.

**Comment by jstedfast** [comment]
Unfortunately it doesn't help :(

**Comment by bottomup** [comment]
Ok, I will try to dig deeper then first.

**Comment by bottomup** [comment]
@jstedfast I don't know the reason why it fails, it works in a testscenario. If relevant, I will post the reason here, but this issue can be closed for now.

**Comment by h3smith** [comment]
@bottomup i am hoping to upgrade to 1.1 next week I'll report back.

**Comment by bottomup** [comment]
@h3smith my guess it is a threading issue.
Because this is an exact similar thing: http://stackoverflow.com/questions/20262388/when-it-occurs-an-unhandled-exception-of-type-system-reflection-targetinvocati

However, by removing all async and await operators the same issue arises...

**Comment by bottomup** [comment]
The following piece of code seems to be the problem: SslStream.AuthenticateAsClientAsync.
When stepping through the MimeKit source however, the same issue remains, which is that there is no stacktrace.
@jstedfast this might be related to #341?
Hope this helps.

**Comment by jstedfast** [comment]
I think you'll need to ask for help from the .NET Core team because I don't think I have any way to fix that from MailKit.

**Comment by bottomup** [comment]
For your reference, this is the thread at the aspnet core team: https://github.com/dotnet/corefx/issues/13814

**Comment by jstedfast** [comment]
Thanks!

**Comment by bartonjs** [comment]
Ah, then I think you've run into https://github.com/dotnet/coreclr/issues/8148.  As a way to confirm you can change your debugger launch settings to set the `COMPlus_ReadyToRunExcludeList` enviornment variable to `System.Security.Cryptography.X509Certificates`.  If the exception(s) go away then that's the culprit.

**Comment by bartonjs** [comment]
(Oops, I meant to send that on the corefx issue... ::whistles innocently::)

**Comment by bottomup** [comment]
Ok, found the solution, see the corefx thread
