### ISSUE TITLE
Exception : System.IO.IOException: Authentication failed because the remote party has closed the transport stream

### ISSUE THREAD

**Issue by vijayinga** [jstedfast/MailKit#427]
I have trying to read gmail mail but while for intial time it works fine and after some time it gives exception System.IO.IOException: Authentication failed because the remote party has closed the transport stream

Exception is throw at line : connect
 client.ServerCertificateValidationCallback = (s, c, h, e) => true;
 client.AuthenticationMechanisms.Clear();
 client.Connect("imap.gmail.com", 993, true);

Detail exception 

Result1 Message:	
Assert.Fail failed. Exception System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)

**Comment by jstedfast** [comment]
What is happening is that your connection to the IMAP server is timing out. It's not a bug in MailKit.
