### ISSUE TITLE
MailService Connect SocketException not documented

### ISSUE THREAD

**Issue by Mats391** [jstedfast/MailKit#434]
If you enter something stupid as host for the Connect function of a MailService (e.g. SmtpClient), it can throw a ExtendedSocketException, but that one is not documented here: http://www.mimekit.net/docs/html/M_MailKit_MailService_Connect_1.htm
There is not issue with the exception being thrown, it should get thrown, but it should be listed in the documentation so you can catch and deal with it.

Example:
`client.Connect("123", 123, false)`

will cause
```
{System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Ein Socketvorgang bezog sich auf ein nicht verfügbares Netzwerk 0.0.0.123:123
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at BookhitMail.Service.Mail.WebOutbox..ctor(MailAccountEntity account) in D:\Schoenke\VisualStudio Projects\BookhitMail\src\BookhitMail.Service\Mail\WebOutbox.cs:line 22
   at BookhitMail.Service.Services.MailSendService.SendMailsOfAccount(MailAccountEntity account, IEnumerable`1 mails) in D:\Schoenke\VisualStudio Projects\BookhitMail\src\BookhitMail.Service\Services\MailSendService.cs:line 70
   at BookhitMail.Service.Services.MailSendService.Run(String connectionString) in D:\Schoenke\VisualStudio Projects\BookhitMail\src\BookhitMail.Service\Services\MailSendService.cs:line 36
   at BookhitMail.Service.Program.<>c__DisplayClass0_0.<Main>b__0() in D:\Schoenke\VisualStudio Projects\BookhitMail\src\BookhitMail.Service\Program.cs:line 26
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)}
```
I am using .net Core 1.1 with MimeKit/MailKit versions:
"MimeKit": "1.10.0"
"MailKit": "1.10.0"

**Comment by jstedfast** [comment]
Thanks.

**Comment by jstedfast** [comment]
I updated the website's docs this morning.
