### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by Dafnafrank** [jstedfast/MailKit#453]
Hi,
We've been using your code and it's been a great help for us! Thanks!
Lately, we got a "Connection timed out" exception (see below) when sending an email. Same email can be sent again with success.

We work with exchange and gmail, didn't have any connection issues with them, and were wondering whether this is a known issue? OR maybe there is a workaround for this error.

Thank you for your help.

SmtpSender: Error sending message MailKit.Net.Smtp.SmtpCommandException: 4.4.1 Connection timed out
   at MailKit.Net.Smtp.SmtpClient.ProcessMailFromResponse(SmtpResponse response, MailboxAddress mailbox)
   at MailKit.Net.Smtp.SmtpClient.FlushCommandQueue(MailboxAddress sender, IList`1 recipients, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, MailboxAddress sender, IEnumerable`1 recipients, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.MailTransport.Send(MimeMessage message, MailboxAddress sender, IEnumerable`1 recipients, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.MailTransport.<>c__DisplayClass4_0.<SendAsync>b__0()
   at System.Threading.Tasks.Task.Execute()

**Comment by jstedfast** [comment]
The error is coming from your SMTP server.

```
4.4.1 Connection timed out
```

That's an SMTP server error.
