### ISSUE TITLE
I am getting this error "The IMAP server has unexpectedly disconnected."

### ISSUE THREAD

**Issue by shahbazvora** [jstedfast/MailKit#540]
Message : The IMAP server has unexpectedly disconnected.

Stacktrace:
   at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken) in D:\Projects\CancelCRM\Cancel\MailKit\Net\Imap\ImapStream.cs:line 357
   at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken) in D:\Projects\CRM\Cancel\MailKit\Net\Imap\ImapStream.cs:line 737
   at MailKit.Net.Imap.ImapStream.ReadToken(CancellationToken cancellationToken) in D:\Projects\CRM\Cancel\MailKit\Net\Imap\ImapStream.cs:line 784
   at MailKit.Net.Imap.ImapEngine.ReadToken(CancellationToken cancellationToken) in D:\Projects\CRM\Cancel\MailKit\Net\Imap\ImapEngine.cs:line 730
   at MailKit.Net.Imap.ImapCommand.Step() in D:\Projects\CRM\Cancel\MailKit\Net\Imap\ImapCommand.cs:line 661
   at MailKit.Net.Imap.ImapEngine.Iterate() in D:\Projects\CRM\Cancel\MailKit\Net\Imap\ImapEngine.cs:line 1783
   at MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic) in D:\Projects\CRM\Cancel\MailKit\Net\Imap\ImapEngine.cs:line 1803
   at MailKit.Net.Imap.ImapEngine.QueryCapabilities(CancellationToken cancellationToken) in D:\Projects\CRM\Cancel\MailKit\Net\Imap\ImapEngine.cs:line 1862
   at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken) in D:\Projects\CRM\Cancel\MailKit\Net\Imap\ImapClient.cs:line 1063
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken) in D:\Projects\CRM\Cancel\MailKit\MailService.cs:line 1045

**Comment by jstedfast** [comment]
This happens when the IMAP server drops the connection and can happen at any time if the server is overloaded and drops your connection, if you lose your connection to the internet momentarily, or a variety of other reasons.

During the Authentication stage, it's also possible that the server is disconnecting you due to "too many" (or even just 1) bad login attempt.

If your server supports NTLM authentication, try disabling that using the following code:

```csharp
client.AuthenticationMechanisms.Remove ("NTLM");
```

Call that before authenticating.

Some users have reported a bug in MailKit's NTLM authentication logic and so I have disabled it in the latest code but I'm not sure if that made it into a release yet.
