### ISSUE TITLE
Exception "Unable to read data from the transport connection: An established connection was aborted by the software in your host machine."

### ISSUE THREAD

**Issue by dushii** [jstedfast/MailKit#567]
I am trying to read emails via IMAP using below code.

using (var client = new ImapClient(new ProtocolLogger("imap.log")))
{
                    //accept all SSL certificates
                    client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                    client.Connect ("mailServer", 993, true);
                    client.AuthenticationMechanisms.Remove("XOAUTH2");
                    client.Authenticate("userId", "Password");

                    var folder = client.Inbox;
                    IMailFolder ctbtoFolder = null;
                    IMailFolder inFolder = null;
                    IMailFolder processedFolder = null;

                    IEnumerable<IMailFolder> subFolders = folder.GetSubfolders();
                    foreach (IMailFolder subFolder in subFolders)
                    {
                        //Process folder
                    }     
}

At line "client.Connect("mailServer", 993, true);" below exception is thrown. I tried removing SSL certificates accepting line. Still the exception is same. And nothing is printed in imap.log file.

Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.

HResult -2146232800

Inner exception
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)

Strack Trace
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object st...
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.<>c.<ReadAsync>b__58_0(Byte[] bufferArg, Int32 offsetArg, Int32 sizeArg, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3,TResult](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
   at System.Net.Sockets.NetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.FixedSizeReader.StartReading()
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c__DisplayClass21_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at ctbto.Parser.EmailReader.ReadMailBox() in W:\Projects\CTBTOMonitoring\ctbto.Parser\EmailReader.cs:line 36

I tried the same code on port 143 with below change.
//client.ServerCertificateValidationCallback = (s, c, h, e) => true;
client.Connect ("mailServer", 143, false);

Then I receive below exception with imap.log content as "Connected to imap://mailServer:143/?starttls=when-available"

The IMAP server has unexpectedly disconnected.
   at MailKit.Net.Imap.ImapStream.ReadAhead(Int32 atleast, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadToken(String specials, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapEngine.Connect(ImapStream stream, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at ctbto.Parser.EmailReader.ReadMailBox() in W:\Projects\CTBTOMonitoring\ctbto.Parser\EmailReader.cs:line 35

I am working in a Windows 10 Virtual Machine and I have both Firewall and Antivirus Protection disabled. What could be the issue here?

**Comment by jstedfast** [comment]
Sounds like your virtual machine is misconfigured for network support.
