### ISSUE TITLE
Error only when project is published

### ISSUE THREAD

**Issue by fatjoni** [jstedfast/MailKit#588]
Hi,

I am using an smtp from mailgun and everything works great on my project except when it is published.
When i publish the project and then call the same api i get the following error and email is not sent.
Please help me.
Thanks in advance 

 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
    at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
  at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
  at rfaBack.Controllers.EmailController.<sendMail>d__2.MoveNext() in

**Comment by jstedfast** [comment]
Sounds like a problem with your setup on your public machine. Perhaps some Root CA certificates not added? Perhaps a firewall issue? You'll have to ask someone else because I don't know what the problem is, all I can tell you is that it's not a MailKit issue.
