### ISSUE TITLE
Domain size limit exceeded

### ISSUE THREAD

**Issue by Clockfoot** [jstedfast/MailKit#591]
When I send an email (smtp) in a VisualStudio C# class using MailKit and Core 2 framework, I get the error "Domain size limit exceeded". The error occurs when calling emailClient.Send(message);

I understand that with a correct implementation of the smtp protocol, this error should be raised.

But, other email/smtp clients such as Outlook, the old .net smtpclient, and the webmail for the current domain ignores this message, and sends the mail anyway. The mailserver I am using allows sending emails despite the fact that the domain limit is surpassed.
 
I cant find a way to work around this error and continue sending the mail. I Think I need a property/flag in MailKit to override this exception. Changing the domain limit would be the obvious answer, but that's not under my Control, and should not be needed as it works with other smpt clients

I dont find anything on stackoverflow or elsewhere on this matter. I am sorry if this is a trivial issue and if it's my lack of understanding that is the cause.

The error I get is:
MailKit.Net.Smtp.SmtpCommandException: '<xxx@yyy.se> Domain size limit exceeded'

Stacktrace:
{MailKit.Net.Smtp.SmtpCommandException: <xxx@yyy.se> Domain size limit exceeded
   at MailKit.Net.Smtp.SmtpClient.ProcessRcptToResponse(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
   at MailKit.Net.Smtp.SmtpClient.RcptTo(FormatOptions options, MimeMessage message, MailboxAddress mailbox, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.MailTransport.Send(MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at MyProject.Mail.EmailService.Send(EmailMessage emailMessage) in C:\Users\xxx\Documents\Visual Studio 2017\Projects\MyProject\MyProject\Logic\mailClass.cs:line 64
   at MyProject.Controllers.ApiController.ForgetPW(IEmailService Mailer, IEmailConfiguration MailConfig, ForgetPWReqModel req) in C:\Users\xxx\Documents\Visual Studio 2017\Projects\MyProject\MyProject\Controllers\ApiController.cs:line 261
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()}

Best regards
Fredrik

**Comment by jstedfast** [comment]
Is `yyy.se` really long or something? I don't understand.

Also: can you get me a protocol log so I can see what the actual error code is?

**Comment by Clockfoot** [comment]
I don't know if this is a very strange coincidence or if the using of MailKit triggered something on the smtp-server, but the second I tried to send a mail with MailKit, sending mail with Outlook also stopped working, returning the same response "Domain size limit exceeded". I cleaned some e-mail accounts and released space on the domain account, and got It working. There is probably nothing wrong with your Components, and you can close the issue.

The yyy.se domain was 10 chars, no strange symbols within it. Sorry to have bothered you.

**Comment by jstedfast** [comment]
Ah, so Domain limit was meaning the limit of the hard drive space used on your mail server domain. I was assuming it was referring to the yyy.se domain name ;)

Cool, glad you got things working.
