### ISSUE TITLE
Direct connect to mx.zoho.eu - SSPI error

### ISSUE THREAD

**Issue by andy250** [jstedfast/MailKit#601]
I am creating a small custom smtp server. I find out recipient email server (mx lookup) then use MailKit to connect and send message directly. I am pretty successful with some providers (gmail, yahoo, mail.com, outlook.com) but when connecting to mx.zoho.eu I am getting this error:

**Message**
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message received was unexpected or badly formatted

**Stack trace**
at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.<>c__DisplayClass45_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyCustomSmtpServer.DirectEmailSender.<Send>d__9.MoveNext()

**Protocol log:**
Connected to smtp://mx.zoho.eu.:25/?starttls=when-available
S: 220 mx.zoho.eu SMTP Server ready December 18, 2017 3:31:43 PM CET
C: EHLO [my ip]
S: 250-mx.zoho.eu Hello [my ip and host name]
S: 250-STARTTLS
S: 250 SIZE 53477376
C: STARTTLS
S: 220 Ready to start TLS.

**Code**
```
var logger = new ProtocolLogger("C:\\Logs\\SMTPprotocol.log");
using (var client = new SmtpClient(logger))
{
  client.ServerCertificateValidationCallback = (c, h, s, e) => true;
  try
  {
    await client.ConnectAsync("mx.zoho.eu", 25, SecureSocketOptions.StartTlsWhenAvailable);
  }
  catch (Exception e) { ... }
}
```

I am also able to connect to mx.zoho.eu from command line using openssl:
`openssl s_client -connect mx.zoho.eu:25 -starttls smtp`
and execute HELO/EHLO afterwards.

What can be wrong? Is this a problem with my server configuration? Do I need a client certificate here? Is this a MailKit bug inside?

**Comment by jstedfast** [comment]
The problem appears to be a bug in System.Security's SslStream or else a bug in the server's SSL implementation.

You can work around this by using `SecureSocketOptions.None`

**Comment by jstedfast** [comment]
You might also try fixing your hostname - you appear to be using `"mx.zoho.eu."` (notice the trailing `.`).

**Comment by andy250** [comment]
Thanks! Removing that trailing dot solved the problem. Strange, I thought the trailing dot is fine in a FQDN. And it comes directly from a MX record lookup.

**Comment by jstedfast** [comment]
That string is used by SslStream to compare the hostname in the certificate with the expected hostname (i.e.the one provided in the Connect call).
