### ISSUE TITLE
Gmail Client.Authenticate Invalid credentials (Failure)

### ISSUE THREAD

**Issue by linhth1929** [jstedfast/MailKit#623]
Dear, Please help.
I try to run your sample (ImapClientDemo) with Gmail but keep getting Invalid credential error. I already have the access token using following code.

public static async Task Reconnect()
{
Client.ServerCertificateValidationCallback = (s, c, ch, e) => true;
string ClientID = "my-client-id";
string ClientSecret = "my-client-secret";
var credential = GoogleWebAuthorizationBroker.AuthorizeAsync(new ClientSecrets
{
ClientId = ClientID,
ClientSecret = ClientSecret
},
new[] { "https://mail.google.com/" },
((NetworkCredential)Credentials).UserName,
CancellationToken.None,
new FileDataStore("Mail2.Auth.Store")).Result;
await Client.ConnectAsync("imap.gmail.com", 993, SecureSocketOptions.SslOnConnect).ConfigureAwait(false);

//--failed here--
Client.Authenticate(((NetworkCredential)Credentials).UserName, credential.Token.AccessToken);

STACK TRACE
at MailKit.Net.Imap.ImapClient.d__76.MoveNext() in D:\WIP\MailKit\MailKit\MailKit\Net\Imap\ImapClient.cs:line 1055
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken) in D:\WIP\MailKit\MailKit\MailKit\Net\Imap\ImapClient.cs:line 1127
at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken) in D:\WIP\MailKit\MailKit\MailKit\MailService.cs:line 1029
at ImapClientDemo.Program.d__8.MoveNext() in D:\WIP\MailKit\MailKit\samples\ImapClientDemo\ImapClientDemo\Program.cs:line 154

I also tried this method but can not get the access token
var certificate = new X509Certificate2 (@"C:\path\to\certificate.p12", "password", X509KeyStorageFlags.Exportable);
var credential = new ServiceAccountCredential (new ServiceAccountCredential
.Initializer ("your-developer-id@developer.gserviceaccount.com") {
// Note: other scopes can be found here: https://developers.google.com/gmail/api/auth/scopes
Scopes = new[] { "https://mail.google.com/" },
User = "user@gmail.com"
}.FromCertificate (certificate));

bool result = await credential.RequestAccessTokenAsync (CancellationToken.None);
--ERROR--
Google.Apis.Auth.OAuth2.Responses.TokenResponseException occurred
HResult=0x80131500
Message=Error:"unauthorized_client", Description:"Client is unauthorized to retrieve access tokens using this method.", Uri:""
Source=
StackTrace:
at Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.d__0.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Google.Apis.Auth.OAuth2.ServiceAccountCredential.d__19.MoveNext()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at ImapClientDemo.Program.d__8.MoveNext() in D:\WIP\MailKit\MailKit\samples\ImapClientDemo\ImapClientDemo\Program.cs:line 118
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at ImapClientDemo.LoginWindow.d__7.MoveNext() in D:\WIP\MailKit\MailKit\samples\ImapClientDemo\ImapClientDemo\LoginWindow.cs:line 97

**Comment by jstedfast** [comment]
Starting with MailKit 2.0, using `client.Authenticate (username, access_token);` will no longer try the XOAUTH2 SASL mechanism.

Instead, you now have to do this:

```csharp
var uri = new Uri ("imap://imap.gmail.com");
var oauth2 = new SaslMechanismOAuth2 (uri, new NetworkCredential (username, access_token));

client.Authenticate (oauth2);
```

Note: I'm planning to make a new release of MailKit 2.0.1 which will not require the Uri argument to the SaslMechanismOAuth2 .ctor because I recognize this as being awkward. In fact, for OAuth2, the Uri isn't even used at all anyway (it's only used for DigestMd5 I think).

Hope that helps.
