### ISSUE TITLE
Getting an error on UpdateUnreadCount

### ISSUE THREAD

**Issue by rashiddear** [jstedfast/MailKit#675]
Hi,
I downloaded the latest source and trying to run samples under directory "\MailKit-2.0.1\samples\ImapClientDemo". I am getting an error on line 145, await folder.StatusAsync (StatusItems.Unread); in procedure async void UpdateUnreadCount (object sender, EventArgs e)

Error:
The ImapClient is currently busy processing a command in another thread. Lock the SyncRoot property to properly synchronize your threads.

StackTrace:
at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__169.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<RunAsync>d__170.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapFolder.<StatusAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ImapClientDemo.FolderTreeView.<UpdateUnreadCount>d__10.MoveNext() in D:\MailKit-2.0.1\samples\ImapClientDemo\ImapClientDemo\FolderTreeView.cs:line 145

As you mentioned in the issue https://github.com/jstedfast/MailKit/issues/653, this is the same error which I was getting prior to update the source. Then I downloaded the latest source but getting the same.

Please help.

**Comment by jstedfast** [comment]
You clearly didn't update the code because there is no longer ANY call to StatusAsync() in the sample program at all.

**Comment by rashiddear** [comment]
Thanks for reply. I updated the code again and run the sample, ImapClientDemo but still I am getting error.
I tried to run code and also execution file but do'nt know why it gives me error on first load, and error on any folder click. If I click the folder again (which was previously clicked) then no error.
I am using Server: smtp.office365.com Port: 993 and checked on Enable SSL/TLS

Please help.

Thanks

StackTrace:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: The ImapClient is currently busy processing a command in another thread. Lock the SyncRoot property to properly synchronize your threads.
   at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__168.MoveNext() in D:\Mailkit\MailKit\Net\Imap\ImapEngine.cs:line 1973
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MailKit.Net.Imap.ImapEngine.<RunAsync>d__169.MoveNext() in D:\Mailkit\MailKit\Net\Imap\ImapEngine.cs:line 2019
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MailKit.Net.Imap.ImapFolder.<StatusAsync>d__54.MoveNext() in D:\Mailkit\MailKit\Net\Imap\ImapFolder.cs:line 1805
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MailKit.Net.Imap.ImapFolder.Status(StatusItems items, CancellationToken cancellationToken) in D:\Mailkit\MailKit\Net\Imap\ImapFolder.cs:line 1859
   at ImapClientDemo.FolderTreeView.UpdateUnreadCount(Object sender, EventArgs e) in D:\Mailkit\samples\ImapClientDemo\ImapClientDemo\FolderTreeView.cs:line 142
   at MailKit.MailFolder.OnCountChanged() in D:\Mailkit\MailKit\MailFolder.cs:line 14610
   at MailKit.Net.Imap.ImapFolder.OnExists(Int32 count) in D:\Mailkit\MailKit\Net\Imap\ImapFolder.cs:line 5092
   at MailKit.Net.Imap.ImapEngine.<ProcessUntaggedResponseAsync>d__167.MoveNext() in D:\Mailkit\MailKit\Net\Imap\ImapEngine.cs:line 1915
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MailKit.Net.Imap.ImapCommand.<StepAsync>d__68.MoveNext() in D:\Mailkit\MailKit\Net\Imap\ImapCommand.cs:line 709
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__168.MoveNext() in D:\Mailkit\MailKit\Net\Imap\ImapEngine.cs:line 1998
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MailKit.Net.Imap.ImapEngine.<RunAsync>d__169.MoveNext() in D:\Mailkit\MailKit\Net\Imap\ImapEngine.cs:line 2019
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MailKit.Net.Imap.ImapFolder.<OpenAsync>d__21.MoveNext() in D:\Mailkit\MailKit\Net\Imap\ImapFolder.cs:line 449
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MailKit.Net.Imap.ImapFolder.Open(FolderAccess access, CancellationToken cancellationToken) in D:\Mailkit\MailKit\Net\Imap\ImapFolder.cs:line 511
   at ImapClientDemo.MessageList.OpenFolder(IMailFolder folder) in D:\Mailkit\samples\ImapClientDemo\ImapClientDemo\MessageList.cs:line 84
   at ImapClientDemo.MainWindow.FolderSelected(Object sender, FolderSelectedEventArgs e) in D:\Mailkit\samples\ImapClientDemo\ImapClientDemo\MainWindow.cs:line 25
   at ImapClientDemo.FolderTreeView.OnAfterSelect(TreeViewEventArgs e) in D:\Mailkit\samples\ImapClientDemo\ImapClientDemo\FolderTreeView.cs:line 179
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2115.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ImapClientDemo
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/UsersProfile/rhussain/Desktop/ImapClientDemo/ImapClientDemo/bin/Debug/ImapClientDemo.exe
----------------------------------------
MailKit
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///D:/UsersProfile/rhussain/Desktop/ImapClientDemo/ImapClientDemo/bin/Debug/MailKit.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2634.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2634.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MimeKit
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.2.0
    CodeBase: file:///D:/UsersProfile/rhussain/Desktop/ImapClientDemo/ImapClientDemo/bin/Debug/MimeKit.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
