### ISSUE TITLE
The BeginRead method cannot be called when another read operation is pending.

### ISSUE THREAD

**Issue by PoissonPS** [jstedfast/MailKit#699]
Hi, I am getting error during sending email.
I have an receiver - it is listening queue for messages and send emails.

listener is registered as 
`services.AddSingleton<IHostedService, EmailListener>();`

my email client is registered as
`services.AddTransient<IEmailClient, EmailClient>();`

I am using IServiceScopeFactory to get instance of email client inside singleton listener

```
  using (var scope = scopeFactory.CreateScope())
 {       
      var client = scope.ServiceProvider.GetRequiredService<IEmailClient>();
      await client.Send(message);
 } 
```

So listener receive first message and send it successfully and during sending second message I am getting this error

> The BeginRead method cannot be called when another read operation is pending.

```
at System.Net.Security.SslStreamInternal.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, BufferAsyncResult asyncResult)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MailKit.Net.Smtp.SmtpStream.<ReadAheadAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpStream.<ReadResponseAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.<FlushCommandQueueAsync>d__58.MoveNext()
```

Also , here is implementation of mine email client
```
public class EmailClient : IEmailClient
    {
        /// <summary>
        /// smtp settings
        /// </summary>
        private SmtpCredentials Options { get; }

        private SmtpClient SmtpClient { get; }

        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="optionsAccessor"></param>
        public EmailClient(IOptions<SmtpCredentials> optionsAccessor)
        {
            Options = optionsAccessor.Value;
            SmtpClient = new SmtpClient();
            SmtpClient.Connect(Options.Host, Options.Port, SecureSocketOptions.StartTlsWhenAvailable);            
            SmtpClient.AuthenticateAsync(Options.Username, Options.Password);
        }

        /// <summary>
        /// Send email
        /// </summary>
        /// <param name="message"></param>
        /// <returns></returns>
        public async Task Send(MimeMessage message)
        {
           await SmtpClient.SendAsync(message);
        }

        /// <summary>
        /// Dispose
        /// </summary>
        public void Dispose()
        {
            SmtpClient?.Disconnect(true);         
        }
    }
```
I am attaching 2 log files - for the first success and second. Logs contains sensitive information and that is why I removed email body and replaces sender and receiver addresses, but I can mail you original.

Please have a look on this.

**Comment by PoissonPS** [comment]
[1_smtp.log](https://github.com/jstedfast/MailKit/files/1908752/1_smtp.log)
[2_smtp.log](https://github.com/jstedfast/MailKit/files/1908753/2_smtp.log)

**Comment by jstedfast** [comment]
Since you're the only person who can reproduce this, you'll have to debug this yourself.

Unfortunately the logs do not provide any useful hints that I can see.

It sounds like you are accessing the client from multiple threads at the same time.

**Comment by jstedfast** [comment]
n/m, I see the bug in your code:

```csharp
public EmailClient(IOptions<SmtpCredentials> optionsAccessor)
        {
            Options = optionsAccessor.Value;
            SmtpClient = new SmtpClient();
            SmtpClient.Connect(Options.Host, Options.Port, SecureSocketOptions.StartTlsWhenAvailable);            
            SmtpClient.AuthenticateAsync(Options.Username, Options.Password);
        }
```

You are calling AuthenticateAsync() instead of Authenticate(). This is why you get accesses from multiple threads.

**Comment by PoissonPS** [comment]
Hi @jstedfast  ! You are right , bug in constructor. My inattention ... 
Btw, thanks for quick response !
