### ISSUE TITLE
GreenMail IMAP Testing Server - Open Folder - Syntax error in UIDVALIDITY response code. Unexpected token: [atom: 1528896777421]

### ISSUE THREAD

**Issue by AlanFlaherty** [jstedfast/MailKit#723]
I was trying to use GreenMail to isolate tests and avoid connecting to a live server. Couldn't find a similar tool in .net

http://www.icegreen.com/greenmail/

## Commandline Args
>java -Dgreenmail.startup.timeout=1200  -Dgreenmail.setup.test.all -Dgreenmail.users=foo:pwd@bar.com -jar greenmail-standalone-1.5.7.jar

## Stack trace 
```
ERROR 2018-06-13 15:54:30,118 [4    ] Mvc.ExceptionHandling.AbpExceptionFilter - Syntax error in UIDVALIDITY response code. Unexpected token: [atom: 1528896777421]
MailKit.Net.Imap.ImapProtocolException: Syntax error in UIDVALIDITY response code. Unexpected token: [atom: 1528896777421]
   at MailKit.Net.Imap.ImapEngine.ParseResponseCode(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapEngine.ProcessUntaggedResponse(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.Step()
   at MailKit.Net.Imap.ImapEngine.Iterate()
   at MailKit.Net.Imap.ImapEngine.Wait(ImapCommand ic)
   at MailKit.Net.Imap.ImapFolder.Open(FolderAccess access, CancellationToken cancellationToken)
   at AbpCompanyName.AbpProjectName.Email.EmailAppService.<GetEmailListAsync>d__3.MoveNext() in C:\git\abp-email-sampleapp\aspnet-core\src\AbpCompanyName.AbpProjectName.Application\EMail\EmailAppService.cs:line 70 
```

## Protocol Log
```
Connected to imaps://localhost:3993/
S: * OK IMAP4rev1 Server GreenMail v1.5.7 ready
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS QUOTA
S: A00000000 OK CAPABILITY completed.
C: A00000001 LOGIN foo pwd
S: A00000001 OK LOGIN completed.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4rev1 LITERAL+ SORT UIDPLUS QUOTA
S: A00000002 OK CAPABILITY completed.
C: A00000003 LIST "" ""
S: * LIST (\Noselect) "." ""
S: A00000003 OK LIST completed.
C: A00000004 LIST "" "INBOX"
S: * LIST () "." "INBOX"
S: A00000004 OK LIST completed.
C: A00000005 EXAMINE INBOX
S: * FLAGS (\Answered \Deleted \Draft \Flagged \Seen)
S: * 1 EXISTS
S: * 1 RECENT
S: * OK [UIDVALIDITY 1528896777421]
```

**Comment by jstedfast** [comment]
Well... the syntax for the UIDVALIDITY response-code is defined as `"UIDVALIDITY" SP nz-number` and `nz-number` is defined as:

```
nz-number       = digit-nz *DIGIT
                    ; Non-zero unsigned 32-bit integer
                    ; (0 < n < 4,294,967,296)
```

Do you see the problem? `1528896777421` is larger than `4294967295`.

This is a bug in the server, not MailKit.

**Comment by jstedfast** [comment]
Submitted bug to greenmail: https://github.com/greenmail-mail-test/greenmail/issues/247

**Comment by AlanFlaherty** [comment]
Fixed in greenmail and built a jar file to test with last night!

**Comment by jstedfast** [comment]
Awesome :)
