### ISSUE TITLE
Only one usage of each socket address permitted

### ISSUE THREAD

**Issue by jag43** [jstedfast/MailKit#743]
We have started getting this error on our web server. We have multiple applications that need to send emails. I believe the error makes sense as only 1 application can use the socket at a time, but do you have any advice for how to allow multiple applications to send emails?

Our setup has been running ok for some months and we believe we started getting the error after upgrading to `dotnet core 2.1`, but it may also be due to increased load.

Stack trace
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted
at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
at CustomAssembly.Services.EmailService.SendAsync(MimeMessage message) in D:\a\1\s\WinApps\CustomAssembly\Services\EmailService.cs:line 116
```

**Comment by jstedfast** [comment]
Are you setting a `SmtpClient.LocalEndPoint`?

**Comment by jag43** [comment]
No, I'm guessing I should be setting that with a different port for each application?

**Comment by jag43** [comment]
I've found port 0 which can be used to automatically assign a free port.

I highly suspect this will solve the error, so I will close the issue.

Thank you for nudging me in the right direction!
