### ISSUE TITLE
Cannot open mail folder

### ISSUE THREAD

**Issue by FishTailTea6** [jstedfast/MailKit#746]
I'm using MailKit for some time now getting to IceWarp mail folders. Up till now succesfully! :)

Recently the storage directrory on the server has been moved to F: (from C:) and also the IceWarp on the server has been updated to newest version. The IP has not changed.

From than I have problem accessing the folders on the client. One folder is called "odchozi".
I can connect, authenticate and if I loop through the GetSubfolders I can see that folder.
However once I call mailFolder.Open(FolderAccess.ReadOnly) I get an error "The IMAP server replied to the 'EXAMINE' command with a 'NO' response: EXAMINE Mailbox does not exist"
If I call mailFolder.Open(FolderAccess.ReadWrite) I get an error "The IMAP server replied to the 'SELECT' command with a 'NO' response: SELECT Mailbox does not exist"

We have the IceWarp outsourced and I'm first trying to ask you if you would not know what could be wrong. I'm not sure if maybe some user rights should be applied to the folders on the server?

=============================
   at MailKit.Net.Imap.ImapFolder.<OpenAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapFolder.Open(FolderAccess access, CancellationToken cancellationToken)
   at SyncIceWarp.Module1.ProcessMail(ImapClient client, DateTime qDate, MailTypeType messageType) in C:\Users\Jitka Maudrová\Documents\Visual Studio 2015\Projects\Oresi.ICT\SyncIceWarp\Module1.vb:line 136
   at SyncIceWarp.Module1.Main(String[] args) in C:\Users\Jitka Maudrová\Documents\Visual Studio 2015\Projects\Oresi.ICT\SyncIceWarp\Module1.vb:line 103

**Comment by jstedfast** [comment]
It sounds like the folder doesn't exist anymore.

If the server has changed the storage format and if the "odchozi" folder did not contain any messages, but was instead a folder that contained other folders, it is entirely possible that this folder is *now* a non-existent "ghost" folder.

Hope that helps.
