### ISSUE TITLE
Uncachable OperationCanceledException in MailKit.Net.Imap.ImapStream.Poll

### ISSUE THREAD

**Issue by ccvca** [jstedfast/MailKit#750]
I want to cancel an idle Request. Due to the fact, that the cancellationToken do not  help (as described in #374), I've created the doneToken as a child of the cancellationToken, so it gets fired when the cancellationToken gets fired. But cancelling the cancellingToken crashes the application with an uncatchable exception.

Minimal example: (Press Ctrl + C to get the error)
```
static void Main(string[] args)
        {
            var imapClient = new ImapClient(new ProtocolLogger(System.Console.OpenStandardOutput()));
            imapClient.Connect(imapDomain);
            imapClient.Authenticate(username, password);

            var cancellationTokenSource = new CancellationTokenSource();
            // Dependend token, to quit when any of the tokens are fired
            var idleDone = CancellationTokenSource.CreateLinkedTokenSource(cancellationTokenSource.Token);

            Console.CancelKeyPress += (sender, e) =>
            {
                Console.WriteLine("Cancel idle.");
                try
                {
                    cancellationTokenSource.Cancel(); // <-- Crash occures here
                }
                catch (SystemException)
                {
                    Console.WriteLine("SystemException Cancel");
                }
                Console.WriteLine("Idle canceled.");
            };            

            var inbox = imapClient.Inbox;
            inbox.Open(FolderAccess.ReadOnly);
            inbox.CountChanged += (sender, e) =>
            {
                Console.WriteLine("Inbox count changed.");
                idleDone.Cancel();
            };

            try
            {
                if (!imapClient.Capabilities.HasFlag(ImapCapabilities.Idle))
                {
                    Console.WriteLine("NoOp");
                    imapClient.NoOp(cancellationTokenSource.Token);
                    WaitHandle.WaitAny(new[] { cancellationTokenSource.Token.WaitHandle, idleDone.Token.WaitHandle });
                }
                else
                {
                    Console.WriteLine("Idle");
                    imapClient.Idle(idleDone.Token, cancellationTokenSource.Token);
                }
            }
            catch (OperationCanceledException)
            {
                Console.WriteLine("OperationCanceledException");
            }
            catch (SystemException)
            {
                Console.WriteLine("SystemException");
            }

            Console.WriteLine("Done");
        }
```

Output:
```
Connected to imap://[--------------------]:143/?starttls=when-available
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] [--------------------]
C: A00000000 STARTTLS
S: A00000000 OK Begin TLS negotiation now.
C: A00000001 CAPABILITY
S: * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN
S: A00000001 OK Pre-login capabilities listed, post-login capabilities have more.
C: A00000002 AUTHENTICATE PLAIN [--------------------]
S: A00000002 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SPECIAL-USE QUOTA] Logged in
C: A00000003 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000003 OK Namespace completed (0.000 + 0.000 secs).
C: A00000004 LIST "" "INBOX"
S: * LIST (\HasChildren) "/" INBOX
S: A00000004 OK List completed (0.000 + 0.000 secs).
C: A00000005 LIST (SPECIAL-USE) "" "*"
S: * LIST (\Drafts) "/" Drafts
S: * LIST (\Trash) "/" Trash
S: * LIST (\Sent) "/" Sent
S: * LIST (\Junk) "/" Spam
S: A00000005 OK List completed (0.000 + 0.000 secs).
C: A00000006 EXAMINE INBOX (CONDSTORE)
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * OK [PERMANENTFLAGS ()] Read-only mailbox.
S: * 0 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 1534705621] UIDs valid
S: * OK [UIDNEXT 36] Predicted next UID
S: * OK [HIGHESTMODSEQ 92] Highest
S: A00000006 OK [READ-ONLY] Examine completed (0.000 + 0.000 secs).
Idle
C: A00000007 IDLE
S: + idling
Cancel idle.

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (The operation was canceled.)) ---> System.AggregateException: One or more errors occurred. (The operation was canceled.) ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at MailKit.Net.Imap.ImapStream.Poll(SelectMode mode, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.FlushAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.Flush(CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.IdleComplete(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Mailkit_Idle.Mailkit_Idle_Main.<>c__DisplayClass3_0.<Main>b__0(Object sender, ConsoleCancelEventArgs e) in D:\Mailkit_Idle\Mailkit_Idle_Main.cs:line 26
   at System.Console.HandleBreakEvent(ConsoleSpecialKey controlKey)
   at System.ConsolePal.ControlCHandlerRegistrar.BreakEvent(Int32 controlType)
Drücken Sie eine beliebige Taste . . . (German, "Press any key")
```

**Comment by jstedfast** [comment]
You need to catch `AggregateException`

**Comment by ccvca** [comment]
Thank you, (I mixed up Exception and SystemException as BaseClass).

**Comment by ccvca** [comment]
Is it possible to change idle that it do not hang up, when cancellationTokenSource is _canceled_ before _done_?

This hangs up (Exception from above occured and then everything blocks):
````
cancellationTokenSource.Cancel();
idleDone.Cancel();
```

This works fine:
````
cancellationTokenSource.Cancel();
idleDone.Cancel();
```

**Comment by jstedfast** [comment]
That was the very first thing I looked into doing, but that won't work.
