### ISSUE TITLE
"Cannot assign requested address" with GMail from docker

### ISSUE THREAD

**Issue by grayver** [jstedfast/MailKit#767]
**Describe the bug**
I have a backend application with microservice architecture. One of microservice is email gateway which is .NET Core 2.1 application with MailKit library. This gateway works well on my developer machine (Windows 10 without docker). But on my staging server with docker infrastructure I get following error when I try to send email via GMail:

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (99): Cannot assign requested address [2a00:1450:400c:c0c::6d]:465
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
   at Dzing.Gateway.Email.Services.EmailService.SendMessageAsync(String to, String templateName, Dictionary`2 arguments, String locale, CancellationToken cancellationToken) in /src/Dzing.Gateway.Email/Services/EmailService.cs:line 42
   at Dzing.Utils.WorkerBase.<>c_DisplayClass29_0`2.<<ConsumeMessage>b_0>d.MoveNext() in /src/Dzing.Utils/WorkerBase.cs:line 117
```

Here is my gateway code:

```
            using (var client = new SmtpClient())
            {
                await client.ConnectAsync(this.Configuration.Host, this.Configuration.Port ?? 0, this.Configuration.UseSsl, cancellationToken);
                client.AuthenticationMechanisms.Remove("XOAUTH2");
                if (!string.IsNullOrEmpty(this.Configuration.Username))
                    await client.AuthenticateAsync(this.Configuration.Username, this.Configuration.Password, cancellationToken);

                var message = new MimeMessage();
                message.From.Add(MailboxAddress.Parse(this.Configuration.From));
                message.To.Add(new MailboxAddress(to));

                if (string.IsNullOrEmpty(templateName))
                    templateName = _defaultTemplateName;
                if (string.IsNullOrEmpty(locale))
                    locale = _defaultLocale;

                var template = File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Resources", string.Format("{0}.{1}.html", templateName, locale)));
                var messageBody = template;
                if (arguments != null)
                {
                    foreach (var keyValuePair in arguments)
                        messageBody = messageBody.Replace(string.Format("{{{0}}}", keyValuePair.Key), keyValuePair.Value);
                }

                message.Body = new TextPart(TextFormat.Html)
                {
                    Text = messageBody
                };

                var subjectMatch = Regex.Match(template, "<title>([^<]+)</title>");
                if (subjectMatch.Success)
                    message.Subject = subjectMatch.Groups[1].Value;

                await client.SendAsync(message, cancellationToken);
                await client.DisconnectAsync(true, cancellationToken);
            }
```

And here is configuration parameters I use:

```
    "Host": "smtp.gmail.com",
    "Port": 465,
    "UseSsl": true,
    "Username": "...",
    "Password": "***",
```

**To Reproduce**
Run specified code with .NET Core 2.1 application inside docker container on Ubuntu machine.

**Expected behavior**
No exception expected.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-24-generic x86_64)
 - Docker version: 18.03.1-ce, build 9ee9f40
 - .NET Core 2.1
 - MailKit v2.0.4

**Comment by jstedfast** [comment]
Can you write a test application that connects a socket to that server / port and does that work?

In other words, try something like this:

```csharp
using System;
using System.Net;
using System.Text;
using System.Net.Sockets;
using System.Net.Security;
using System.Security.Authentication;

namespace SslConnect
{
	class Program
	{
		const SslProtocols DefaultSslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;

		public static void Main (string[] args)
		{
			var host = "smtp.gmail.com";
			int port = 465;

			IPAddress[] ipAddresses;
			Socket socket = null;

			ipAddresses = Dns.GetHostAddressesAsync (host).GetAwaiter ().GetResult ();

			for (int i = 0; i < ipAddresses.Length; i++) {
				socket = new Socket (ipAddresses[i].AddressFamily, SocketType.Stream, ProtocolType.Tcp);

				try {
					socket.Connect (ipAddresses[i], port);
					break;
				} catch {
					socket.Dispose ();
					socket = null;

					if (i + 1 == ipAddresses.Length)
						throw;
				}
			}

			if (socket == null) {
				Console.WriteLine ("Failed to resolve host: {0}", host);
				return;
			}

			using (var network = new NetworkStream (socket, true)) {
				using (var ssl = new SslStream (network, true)) {
					ssl.AuthenticateAsClientAsync (host, null, DefaultSslProtocols, true).GetAwaiter ().GetResult ();

					var buffer = new byte[1024];
					int nread;

					nread = ssl.Read (buffer, 0, buffer.Length);

					Console.WriteLine ("S: {0}", Encoding.UTF8.GetString (buffer, 0, nread));
				}
			}
		}
	}
}
```

**Comment by grayver** [comment]
Here is what I get:

```
Unhandled Exception: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Cannot assign requested address [2a00:1450:400c:c07::6c]:465
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at SslConnect.Program.Main(String[] args) in /src/Docker.Test/Program.cs:line 28
```

**Comment by grayver** [comment]
So, it's not a MailKit problem? It seems to be Dns client doesn't see any IPv4 address and fails while connecting to IPv6 address?

**Comment by jstedfast** [comment]
Yea, that seems to be the problem.

**Comment by grayver** [comment]
Thanks. It was DigitalOcean issue. They are silently block email activity on my droplet.
