### ISSUE TITLE
office365 An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by tvcsantos** [jstedfast/MailKit#811]
Hey,

I'm running into the following exception when connecting to an office365 account.

``2019-01-29 21:28:20.0421 ERROR System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MailKit.Net.Imap.ImapStream.<ReadAheadAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapStream.<ReadTokenAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Imap.ImapCommand.<StepAsync>d__79.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__170.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<RunAsync>d__171.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<QueryCapabilitiesAsync>d__175.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Imap.ImapClient.<ConnectAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at MailKit.MailService.Connect(String host, Int32 port, Boolean useSsl, CancellationToken cancellationToken)
   at MailKitDemo.Program.IMAPConnect(Action`1 action, EmailSettings set) in D:\Users\tvcsa\OneDrive\Documents\Visual Studio 2017\Projects\MailKitDemo\MailKitDemo\Program.cs:line 28
   at MailKitDemo.Program.<>c__DisplayClass3_0.<Main>b__0(Object x) in D:\Users\tvcsa\OneDrive\Documents\Visual Studio 2017\Projects\MailKitDemo\MailKitDemo\Program.cs:line 67 System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host``

This appears to be quite random and it is not always happening :S. Can you please help me try to figure out what is the possible cause of the exception. I've made a simple demo test case in order to reproduce this behaviour

```csharp
using MailKit.Net.Imap;
using System;
using System.Threading;

namespace MailKitDemo
{
    public class EmailSettings
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string Token { get; set; }
        public string SMTPURL { get; set; }
        public int SMTPPort { get; set; }
        public bool SMTPRequireSSL { get; set; }
        public string IMAPURL { get; set; }
        public int IMAPPort { get; set; }
        public bool IMAPRequireSSL { get; set; }
    }

    class Program
    {
        protected static NLog.ILogger logger = NLog.LogManager.GetCurrentClassLogger();

        private static void IMAPConnect(Action<ImapClient> action, EmailSettings set)
        {
            using (var imapClient = new ImapClient())
            {
                imapClient.Connect(set.IMAPURL, set.IMAPPort, set.IMAPRequireSSL);

                if (string.IsNullOrEmpty(set.Token))
                {
                    imapClient.AuthenticationMechanisms.Remove("XOAUTH2");
                    imapClient.Authenticate(set.Email, set.Password);
                }
                else
                {
                    imapClient.Authenticate(set.Email, set.Token);
                }

                action(imapClient);

                imapClient.Disconnect(true);
            }
        }

        private static void DummyAction(ImapClient client)
        {
            logger.Info("DummyAction Executed!");
        }

        static void Main(string[] args)
        {
            EmailSettings emailSettings = new EmailSettings
            {
                Email = "xxx@yyy.com",
                Password = "password",
                IMAPURL = "outlook.office365.com",
                IMAPPort = 993,
                IMAPRequireSSL = true
            };

            ;

            var timer = new Timer(x => {
                try
                {
                    IMAPConnect(DummyAction, emailSettings);
                } catch(Exception e)
                {
                    logger.Error(e);
                }
            });
            timer.Change(0, 60000);

            bool exit = false;
            do
            {
                string s = Console.ReadLine();
                switch (s)
                {
                    case "exit":
                        exit = true;
                        break;
                }
            } while (!exit);
        }
    }
}
```
Sometimes the exception changes to `System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

Thanks

Best,
Tiago

**Comment by jstedfast** [comment]
This is just standard TCP/IP errors when the network is congested. There's no fix for this other than to handle the exception and reconnect and try again.
