### ISSUE TITLE
Syntax error in BODYSTRUCTURE. Unexpected token: [atom: -1]

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MailKit#823]
I cloned your latest mailkit sourcecode and compiled a new version. The original error in the header is gone but now I get another error... see below. It also fails on one of the X- .... headers

**Describe the bug**
Syntax error in BODYSTRUCTURE. Unexpected token: [atom: -1]

**Expected behavior**
Parse the message

**Additional context**
`S: * 5 FETCH (UID 581 FLAGS (\Seen) RFC822.SIZE 35149 ENVELOPE ("Mon, 5 Dec 2016 12:13:08 +0100" "No subject" (("...." NIL "...." "....")) NIL NIL (("..." NIL "....." "...")) NIL NIL NIL "<....>") BODYSTRUCTURE ((("text" "plain" ("charset" "US-ASCII") NIL NIL "7bit" 6 3 NIL NIL NIL NIL)("text" "html" ("charset" "US-ASCII") NIL NIL "quoted-printable" 314 5 NIL NIL NIL NIL) "alternative" ("boundary" "B_8345248387_336787") NIL NIL)("multipart" "appledouble" ("boundary" "B_8145297380_164091") NIL NIL "7BIT" -1 NIL NIL NIL NIL) "mixed" ("boundary" "B_7193419875_891207") NIL NIL) BODY[HEADER.FIELDS (IMPORTANCE X-SAR-E2S-MAIL-ID X-`

**Comment by Sicos1977** [comment]
at MailKit.Net.Imap.ImapFolder.<FetchAsync>d__201.MoveNext() in C:\tfs\MailKit\MailKit\Net\Imap\ImapFolderFetch.cs:line 2470
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MailKit.Net.Imap.ImapFolder.Fetch(Int32 min, Int32 max, MessageSummaryItems items, CancellationToken cancellationToken) in C:\tfs\MailKit\MailKit\Net\Imap\ImapFolderFetch.cs:line 2655
   at Email2Storage.Server.BusinessLogic.MailBox.get_ListMessages() in C:\tfs\ECM\Email2Storage\Server\BusinessLogic\MailBoxes.cs:line 1622

**Comment by Sicos1977** [comment]
Nevermind.. It seems this issue is caused because there was a malformed SPAM mail in the mailbox.

**Comment by jstedfast** [comment]
The problem was the `-1` value for the octet count or line count (I forget which value that is without looking at the spec).
