### ISSUE TITLE
The SmtpClient is not connected. (sporadically)

### ISSUE THREAD

**Issue by stevenrobertsvortextanalytics** [jstedfast/MailKit#841]
**Describe the bug**
I'm not convinced this is MailKit bug but since it's the only error in the stack trace I'll have to rely on your experience to tell me if it's MailKit or not.  

The host is hosted Outlook 365 (smtp.office365.com).  The problem is sporadic and always works immediately after restarting the app pool on IIS.  This leads be to think maybe I should scope my object differently, currently using Scoped but maybe Singleton?  Or perhaps I should create, connect, Authenticate, and close for each message sent (seems really inefficient).  Do you have any suggestions as to what the cause might be?

I have the following class which I use to send emails from my .NET Core Web application.

    public class SmtpEmailProcessor : IEmailProcessor, IDisposable
    {
        private readonly SmtpClient _client = new SmtpClient();
        private readonly EmailSettingsAccessor _emailSettings;

        public SmtpEmailProcessor(EmailSettingsAccessor emailSettingsAccessor)
        {
            _emailSettings = emailSettingsAccessor;
            _client.Connect(_emailSettings.Host, _emailSettings.Port, SecureSocketOptions.StartTls);
            _client.Authenticate(_emailSettings.UserName, _emailSettings.Password);
        }

        public async Task SendEmailAsync(EmailDataModel email)
        {
            var emailMessage = ToMimeMessage(email);
            await _client.SendAsync(emailMessage);
        }

        private MimeMessage ToMimeMessage(EmailDataModel email)
        {
            var mailMessage = new MimeMessage();
            mailMessage.From.Add(new MailboxAddress(_emailSettings.From));
            mailMessage.To.Add(new MailboxAddress(email.SendTo));
            mailMessage.Subject = email.Subject;
            var bodyBuilder = new BodyBuilder
            {
                HtmlBody = email.BodyHTMLVersion
            };
            mailMessage.Body = bodyBuilder.ToMessageBody();
            return mailMessage;
        }

        public void Dispose()
        {
            _client.Disconnect(quit: true);
            _client.Dispose();
        }
    }

I configure this class in my .NETCore application as Scoped.
`services.AddScoped<IEmailProcessor, SmtpEmailProcessor>();`

Periodically I get the following error:

	System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
	   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
	   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
	   --- End of inner exception stack trace ---
	   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
	   at System.Net.Sockets.NetworkStream.<>c.<WriteAsync>b__59_0(Byte[] bufferArg, Int32 offsetArg, Int32 sizeArg, AsyncCallback callback, Object state)
	   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
	   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
	   at System.Net.Sockets.NetworkStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
	   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
	   at System.Net.Security.SslStreamInternal.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslStreamInternal.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
	   at System.Net.Security.SslStreamInternal.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
	   at System.Net.Security.SslStream.<>c.<WriteAsync>b__86_0(Byte[] bufferArg, Int32 offsetArg, Int32 sizeArg, AsyncCallback callback, Object state)
	   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
	   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
	   at System.Net.Security.SslStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
	   at MailKit.Net.Smtp.SmtpStream.<FlushAsync>d__58.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at MailKit.Net.Smtp.SmtpClient.<FlushCommandQueueAsync>d__59.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at MailKit.Net.Smtp.SmtpClient.<SendAsync>d__106.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Data.SmtpEmailProcessor.<SendEmailAsync>d__3.MoveNext()

**Desktop (please complete the following information):**
 - Windows Server 2016 Standard
 - .NETCore 1.1

**Comment by jstedfast** [comment]
One thing to keep in mind is that SMTP connections will time out after a period of idleness. How long that time out is depends on the server, but I doubt many will keep it open longer than about 10 minutes.

All of the SMTP/POP3/IMAP clients have a method called `NoOp()` which essentially just pings the server with a dummy command to keep the connection alive. What you can do is have a timeout event that has the SmtpClient call that method every few minutes.

I think that should fix your issue.

**Comment by stevenrobertsvortextanalytics** [comment]
since this is a web app and it is set to Scoped in the DI (per web request) it seems unlikely to have timed out since our web requests only take a few seconds at most.  Should I be creating a new client every time I need it rather than letting DI control this?

**Comment by jstedfast** [comment]
I haven't done much with web apps, so I don't really know the architecture, but if the SmtpClient object is being kept alive between web requests, then yes, you're going to want to create/connect a new instance of the SmtpClient for each email you want to send.

**Comment by stevenrobertsvortextanalytics** [comment]
Thank you.  I guess we'll need to add a protocol logger so we can see what's happening., I am suspicious of the built in DI container for Core, especially 1.0.  Thank you for your comments.

**Comment by jstedfast** [comment]
I'm not sure that a protocol logger will help in this case. When an SMTP server drops your connection due to the timeout, it won't send the client any warning - it'll just close the socket.
