### ISSUE TITLE
SocketException thrown during Connect: "A non-recoverable error occurred during a database lookup"

### ISSUE THREAD

**Issue by nguyen-k** [jstedfast/MailKit#871]
The error with message 'A non-recoverable error occurred during a database lookup' is thrown during the `Connect` call of `MailKit.Net.Imap.ImapClient`.

**To Reproduce**
This code throws:

    var client = new ImapClient();
    client.ServerCertificateValidationCallback = (s, c, h, e) => true;
    client.Connect("outlook.office365.com", 993, MailKit.Security.SecureSocketOptions.SslOnConnect);

**Error Screenshots**
![image](https://user-images.githubusercontent.com/20841242/59287857-86456080-8c40-11e9-9498-e1325018685d.png)

![image](https://user-images.githubusercontent.com/20841242/59287874-8e050500-8c40-11e9-852a-57d84d37d9ff.png)

**Expected behavior**
I used another Powershell to test.  The cmdlet `Connect-JIMAP` was used.  More info: https://www.jamsscheduler.com/doc/JAMSHelp/JAMSPowerShellCmdlets.html

I confirmed I'm able to connect and get messages.
![image](https://user-images.githubusercontent.com/20841242/59287755-51d1a480-8c40-11e9-8a7c-c5f72b120b71.png)

**Screenshots**
Test-NetConnection screenshot.
![image](https://user-images.githubusercontent.com/20841242/59287590-f7384880-8c3f-11e9-92bd-3f73b61d2116.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio 2015 debugger, x64 build

**Stack Trace**

   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.SocketUtils.<ConnectAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.SocketUtils.<ConnectAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.MailService.<ConnectSocket>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.<ConnectAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at WAM.EmailExtractor.get_ImapClient() in U:\projects\WAM\src\WAM\Core\Email\EmailExtractor.cs:line 51
   at WAM.EmailExtractor.get_Inbox() in U:\projects\WAM\src\WAM\Core\Email\EmailExtractor.cs:line 69
   at WAM.EmailExtractor.GetMessages(DateTime cutoff, List`1 subjects) in U:\projects\WAM\src\WAM\Core\Email\EmailExtractor.cs:line 392
   at WAM.EmailExtractor.GetCommentary(DateTime cutoff, Boolean markRead) in U:\projects\WAM\src\WAM\Core\Email\EmailExtractor.cs:line 116
   at WAM.ExtractorBase.SaveCommentary(DateTime cutoff, Boolean markRead) in U:\projects\WAM\src\WAM\Core\Email\ExtractorBase.cs:line 70
   at WAM.Commentary.Program.Main(CommentaryOptions options) in U:\projects\WAM\src\WAM.Commentary\Program.cs:line 36
   at WAM.Commentary.Program.<>c.<Main>b__1_0(CommentaryOptions opts) in U:\projects\WAM\src\WAM.Commentary\Program.cs:line 20
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at WAM.Commentary.Program.Main(String[] args) in U:\projects\WAM\src\WAM.Commentary\Program.cs:line 19
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by jstedfast** [comment]
The exception is thrown by System.Net.Dns.HostResolutionEndHelper which is part of the .NET libraries and not part of MailKit.

**Comment by jstedfast** [comment]
I would suggest trying again. Most likely it is a temporary DNS error.

**Comment by nguyen-k** [comment]
Thanks.  It looks like a common issue when the solution is launched from a network shared drive.  Google-fu:

- https://social.msdn.microsoft.com/Forums/vstudio/en-US/4ffd2bcb-00fd-4518-a77d-a5825a3a9d7a/error-using-the-functions?forum=wcf
- https://stackoverflow.com/questions/4368877/net-process-failing-dns-lookup-with-windows-7
- http://forums.codeguru.com/showthread.php?538249-SocketException-When-Connection-to-MYSQL-DB-From-Shared-Drive-C-Drive-No-Problem

Our network team is investigating.  Really weird... :S
