### ISSUE TITLE
MailKit.Net.Imap.ImapProtocolException: Autologout

### ISSUE THREAD

**Issue by Fr1z2r** [jstedfast/MailKit#938]
We've experienced the following problem:
`MailKit.Net.Imap.ImapProtocolException: Autologout; idle for too long`

Example log:
```
2019-10-18 07:41:00,359 DEBUG Connect: imaps://imap.yandex.ru:993/
2019-10-18 07:41:00,376 DEBUG Server: * OK Yandex IMAP4rev1 at sas8-bccc92f57f23.qloud-c.yandex.net:993 ready to talk with ::ffff:xxx:51447, 2019-Oct-18 07:41:00, 0fHtH613ZiE1
2019-10-18 07:41:00,376 DEBUG Client: A00000000 CAPABILITY
2019-10-18 07:42:00,386 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:43:00,386 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:44:00,386 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:45:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:46:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:47:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:48:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:49:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:50:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:51:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:52:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:53:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:54:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:55:00,386 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:56:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:57:00,386 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:58:00,386 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 07:59:00,386 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:00:00,385 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:01:00,385 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:02:00,385 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:03:00,385 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:04:00,388 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:05:00,384 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:06:00,383 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:07:00,383 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:08:00,382 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:09:00,382 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:10:00,381 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:11:00,381 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:12:00,380 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:13:00,380 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:14:00,379 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:15:00,378 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:16:00,378 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:17:00,377 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:18:00,376 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:19:00,377 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:20:00,377 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:21:00,379 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:22:00,380 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:23:00,381 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:24:00,381 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:25:00,382 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:26:00,383 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:27:00,384 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:28:00,384 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:29:00,385 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:30:00,386 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:31:00,386 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:32:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:33:00,387 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:34:00,388 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:35:00,389 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:36:00,389 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:37:00,389 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:38:00,389 DEBUG Server: * BYE Autologout; idle for too long
2019-10-18 08:38:30,141 ERROR 
MailKit.Net.Imap.ImapProtocolException: Autologout; idle for too long
   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.QueryCapabilitiesAsync(Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)
```

This error occurs several times a day. 
Why does the client wait an hour before disconnecting and ignore server response?

**Comment by jstedfast** [comment]
MailKit only sends commands when you ask it to, and it doesn't read responses from the server except when it reads replies to commands that you've sent.

The only exception to this is if you put the client into IDLE mode, which you presumably did not.

**Comment by Fr1z2r** [comment]
This problem occurs when a client calls MailKit.Net.Imap.ImapClient.ConnectAsync. This is the first client call and it hanging for an hour, although the timeout is set to 2 minutes.

**Comment by jstedfast** [comment]
I can't reproduce the issue. You'll need to debug it and tell me what the issue is. You'll notice that it works fine in the unit tests that I just committed.

**Comment by Fr1z2r** [comment]
Here is example of the client hangup: 
https://github.com/Fr1z2r/MailKitTest/blob/master/MailKitTest/Program.cs

I expect to get exception after first BYE response, but the client is waiting for disconnection.
Example output:
```
Connected to imap://127.0.0.1:12345/?starttls=when-available
S: * OK Yandex IMAP4rev1 at sas8-bccc92f57f23.qloud-c.yandex.net:993 ready to talk with, 2019-Oct-18 07:41:00, 0fHtH613ZiE1
C: A00000000 CAPABILITY
S: * BYE Autologout; idle for too long
S: * BYE Autologout; idle for too long
S: * BYE Autologout; idle for too long
S: * BYE Autologout; idle for too long
S: * BYE Autologout; idle for too long
S: * BYE Autologout; idle for too long
S: * BYE Autologout; idle for too long
S: * BYE Autologout; idle for too long
S: * BYE Autologout; idle for too long
S: * BYE Autologout; idle for too long
```

**Comment by jstedfast** [comment]
Take a look at the unit tests that I just committed yesterday. They test that MailKit throws the exception after the first `* BYE` response.

What MailKit version are you using?

**Comment by jstedfast** [comment]
I found the problem. MailKit will keep reading responses hoping to get a response with a command tag (usually a NO or BAD).

Here's the problem: MailKit is doing the Right Thing(tm). Your server should not be keeping the connection open after it sends `* BYE` *unless* it is going to disconnect after sending a tagged response and *then* drop the connection.

Your server is sending a new `* BYE` response every minute, this is why your timeout value never kicks off - essentially your IMAP server is making sure to keep your connection alive.

I can add a hack to make MailKit throw an exception if it receives a `* BYE` after having already received one, but that will still mean you'll have to wait 2 minutes.

**Comment by jstedfast** [comment]
I was able to detect if the server was Yandex and implemented a special case for Yandex.

Now go harass Yandex to fix their bug.

**Comment by jstedfast** [comment]
From rfc3501:

```
7.1.5.  BYE Response

   Contents:   OPTIONAL response code
               human-readable text

      The BYE response is always untagged, and indicates that the server
      is about to close the connection.  The human-readable text MAY be
      displayed to the user in a status report by the client.  The BYE
      response is sent under one of four conditions:

         1) as part of a normal logout sequence.  The server will close
            the connection after sending the tagged OK response to the
            LOGOUT command.

         2) as a panic shutdown announcement.  The server closes the
            connection immediately.

         3) as an announcement of an inactivity autologout.  The server
            closes the connection immediately.

         4) as one of three possible greetings at connection startup,
            indicating that the server is not willing to accept a
            connection from this client.  The server closes the
            connection immediately.
```

Take special note of item **#3**:

*3) as an announcement of an inactivity autologout.  The server  closes the connection **immediately.***

**Comment by Fr1z2r** [comment]
Thanks for the solution. I reported an issue to the Yandex support.
