### ISSUE TITLE
Unable to parse status code returned by the server

### ISSUE THREAD

**Issue by carlhoogstoel** [jstedfast/MailKit#987]
MailKit.Net.Smtp.SmtpProtocolException: 'Unable to parse status code returned by the server.'

log:

Connected to smtp://xx.xx.com:1800/?starttls=when-available
S: +OK Welcome to MailEnable POP3 Server

stack:

   at MailKit.Net.Smtp.SmtpStream.<ReadResponseAsync>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.<ConnectAsync>d__74.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at xx.SendEmailAsync(String email, String subject, String message) in xx\EmailSender.cs:line 34

**Comment by jstedfast** [comment]
That's because you are trying to connect to a POP3 server using the SmtpClient.

You need to use the Pop3Client to connect to a POP3 server.

**Comment by carlhoogstoel** [comment]
Ok, it is official. I am an idiot:P
