### ISSUE TITLE
MailKit.Net.Imap.ImapProtocolException: Syntax error in ENVELOPE. Unexpected token: NIL

### ISSUE THREAD

**Issue by gold22** [jstedfast/MailKit#991]
**Describe the bug**
MailKit 2.3.1.6 fails to parse FETCH response like

```
A00000008 UID FETCH 1:17207 (UID FLAGS INTERNALDATE ENVELOPE)
...
* 3001 FETCH (UID 3001 FLAGS (\Seen) INTERNALDATE "18-Jun-2019 01:20:56 -0300" ENVELOPE ("Thu, 18 Jul 2019 01:29:32 -0300" "Xxx xxx xxx xxx.." (NIL ({123}
_XXXXXXXX_xxxxxx_xxxx_xxx_?= =?iso-8859-1?Q?xxxx_xx_xxxxxxx_xxxxxxxxxx.Xxxxxxxx_xx_xxx=Xxxxxx_xx_xx_Xx?= =?iso-8859-1?Q?s?= NIL "xxxxxxx" "xxxxxxxxxx.xxx")) (NIL ({123}
_XXXXXXXX_xxxxxx_xxxx_xxx_?= =?iso-8859-1?Q?xxxx_xx_xxxxxxx_xxxxxxxxxx.Xxxxxxxx_xx_xxx=Xxxxxx_xx_xx_Xx?= =?iso-8859-1?Q?s?= NIL "xxxxxxx" "xxxxxxxxxx.xxx")) ((NIL NIL "xxxxxxx" "xxxxx.xxx.xx")) ((NIL NIL "xxxxxxx" "xxxxxxx.xxx.xx")) NIL NIL NIL "<0A9F01100712011D213C15B6D2B6DA@XXXXXXX-XXXXXXX>"))
```

**Actual behavior**

> Syntax error in ENVELOPE. Unexpected token: NIL

**Expected behavior**
Response is parsed successfully

**Desktop (please complete the following information):**
 - OS: Microsoft Windows Server 2019
 - Version: 2.3.1.6

**Additional context**

MailKit.Net.Imap.ImapProtocolException: Syntax error in ENVELOPE. Unexpected token: NIL
   at MailKit.Net.Imap.ImapUtils.<ParseEnvelopeAddressListAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapUtils.<ParseEnvelopeAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Imap.ImapFolder.<FetchSummaryItemsAsync>d__172.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapFolder.<FetchSummaryItemsAsync>d__173.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Imap.ImapEngine.<ProcessUntaggedResponseAsync>d__169.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Imap.ImapCommand.<StepAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<IterateAsync>d__170.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapEngine.<RunAsync>d__171.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapFolder.<FetchAsync>d__180.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Imap.ImapFolder.Fetch(IList`1 uids, MessageSummaryItems items, CancellationToken cancellationToken)

**Comment by jstedfast** [comment]
Have you tried 2.5.1?

**Comment by jstedfast** [comment]
Can you paste the actual log instead of quoting it? The problem with quoting it the way you quoted it is that it destroys the actual syntax.

For future reference, to quote things like logs correctly, put 3 back-ticks on a line by themselves, then paste the contents, then place 3 more back-ticks on a line by themselves.

**Comment by gold22** [comment]
I'll try to use 2.5.1, but as I understand there is an issue with first NIL in records like

```
(NIL ({123}_XXXXXXXX_xxxxxx_xxxx_xxx_?= =?iso-8859-1?Q?xxxx_xx_xxxxxxx_xxxxxxxxxx.Xxxxxxxx_xx_xxx=Xxxxxx_xx_xx_Xx?= =?iso-8859-1?Q?s?= NIL "xxxxxxx" "xxxxxxxxxx.xxx"))
 ___
```

**Comment by jstedfast** [comment]
Yes, it looks like you are right.

The problem is that the syntax used by your IMAP server doesn't match the spec.

```
envelope        = "(" env-date SP env-subject SP env-from SP
                  env-sender SP env-reply-to SP env-to SP env-cc SP
                  env-bcc SP env-in-reply-to SP env-message-id ")"

env-from        = "(" 1*address ")" / nil

address         = "(" addr-name SP addr-adl SP addr-mailbox SP
                  addr-host ")"
```

`env-date` = `"Thu, 18 Jul 2019 01:29:32 -0300"`
`env-subject` = `"Xxx xxx xxx xxx.."`
`env-from` = `"("` + `NIL` <-- oops, this is illegal, expected another `"("` as the first token of an `address`

Anyway, added a work-around and a unit test to make sure this is fixed/stays fixed.

Thanks for the bug report!

**Comment by jstedfast** [comment]
BTW, for my own statistics (and in case I ever need to wrap the work-around logic in something server-specific), do you know what server this is? If you could paste the very first line (aka the server greeting) from the log, that would be awesome.

**Comment by gold22** [comment]
SmarterMail 100.0.7242

**Comment by jstedfast** [comment]
Thanks!

**Comment by gold22** [comment]
The work-around works fine, thank you for a fast solution! We use the library as NuGet package. Could you publish the fixed version?

**Comment by jstedfast** [comment]
Yea, I'll likely try to push a new release this weekend.

Question for you - do you target net46/47/48? If so, would it break things if I changed the BouncyCastle dependency to Portable.BouncyCastle instead?

To answer that question, you would need to check if any other package(s) you depend on *also* use BouncyCastle. If you do, then it would break.

**Comment by gold22** [comment]
Our target is net45 and as I see we use MailKit.dll and MimeKit.dll only.

**Comment by jstedfast** [comment]
Ok, I'm planning on not changing anything for net45 anyway
